
SELECT

HF.codcurso,
STD.codturma,
STD.codturno,
STD.coddisc,
PT.codprof,
STD.tipo,
STD.codpredio,
STD.codbloco,
STD.codsala

FROM SHABILITACAOFILIAL AS HF


JOIN STURMADISC AS STD ON STD.IDHABILITACAOFILIAL = HF.IDHABILITACAOFILIAL
JOIN SPROFESSORTURMA AS PT ON PT.IDTURMADISC = STD.IDTURMADISC




--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPROFESSORTURMA' AND CHILDTABLE = 'STURMADISC'