/*SELECT CODPERLET,SMATRICPL.* FROM SMATRICPL 
JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
WHERE RA='00005613'
*/

SET LANGUAGE PORTUGUÊS   
SET DATEFORMAT DMY      
DECLARE @DTFIM AS DATE = '18/09/2018'--CONVERT(VARCHAR,CONVERT(VARCHAR,DATEPART(DD,CONVERT(DATE,:DTFINAL,103)))+'/'+CONVERT(VARCHAR,DATEPART(MM,CONVERT(DATE,:DTFINAL,103)))+'/'+:CODPERLET,103);
DECLARE @RA AS VARCHAR(10) = '00005613'


; WITH TABA AS (
SELECT 
SMATRICPL.RA,
SMATRICPL.CODTURMA SERIE,
COUNT(*) ALUNOSEM,
sum(case SMATRICPL.CODTIPOMAT when 1 then 1 else 0 end) MATRICULAS,
sum(case SMATRICPL.CODTIPOMAT when 2 then 1 else 0 end) REMATRICULAS,
STURMA.MAXALUNOS NUMVAGAS,
STURMA.MAXALUNOS - COUNT(*) FALTA
--,(CASE WHEN CONVERT(VARCHAR,AA.DTALTERACAO,103) <= @DTFIM  THEN 'MENOR IGUAL '+CONVERT(VARCHAR,AA.DTALTERACAO) WHEN CONVERT(VARCHAR,AA.DTALTERACAO,103) > @DTFIM  THEN 'MAIOR' END ) TESTEDT
,(CASE WHEN (SSTATUS.DESCRICAO NOT LIKE 'MAT%' OR SSTATUS.DESCRICAO NOT LIKE 'PRE%')
						-- THEN (SELECT MAX(CODSTATUS) AS CODSTATUS FROM SLOGMATRICULA  WHERE  SMATRICPL.RA=SLOGMATRICULA.RA AND IDTURMADISC = DISC.IDTURMADISC AND CONVERT(VARCHAR,DTALTERACAO,103) <= @DTFIM)
					   THEN (SELECT MAX(AA.CODSTATUS) WHERE CONVERT(VARCHAR,AA.DTALTERACAO,103) <= @DTFIM  AND AA.IDTURMADISC = DISC.IDTURMADISC)--SMATRICPL.CODSTATUS)
					   ELSE 'SMATRICPL.CODSTATUS' END) CODSTATUS2
--LOGMAT.DTALTERACAO,
,DISC.CODDISC,
@DTFIM DATAFIM,
SPLETIVO.CODPERLET
,SMATRICPL.CODSTATUS
,DISC.IDTURMADISC
,(CASE WHEN (SSTATUS.DESCRICAO NOT LIKE 'MAT%' OR SSTATUS.DESCRICAO NOT LIKE 'PRE%') 
						-- THEN (SELECT TOP 1 DTALTERACAO FROM SLOGMATRICULA WHERE SMATRICPL.RA=SLOGMATRICULA.RA AND IDTURMADISC = DISC.IDTURMADISC AND CONVERT(VARCHAR,DTALTERACAO,103) <= @DTFIM )	
					   THEN ISNULL((SELECT MAX(AA.DTALTERACAO) WHERE CONVERT(VARCHAR,AA.DTALTERACAO,103) <= @DTFIM  AND AA.IDTURMADISC = DISC.IDTURMADISC),SMATRICPL.DTMATRICULA)
					   ELSE SMATRICPL.DTMATRICULA END) DTMATRICULA2
,SMATRICPL.DTMATRICULA
,AA.DTALTERACAO
													
FROM SMATRICPL

INNER JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SSTATUS ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
INNER JOIN SCURSO ON SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
INNER JOIN STURMA ON STURMA.CODTURMA = SMATRICPL.CODTURMA
	   AND STURMA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	   AND STURMA.IDPERLET = SMATRICPL.IDPERLET

	   JOIN SMATRICULA ON SMATRICULA.RA = SMATRICPL.RA AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET AND SMATRICULA.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	   JOIN STURMADISC DISC ON DISC.IDTURMADISC = SMATRICULA.IDTURMADISC AND DISC.IDPERLET = SMATRICPL.IDPERLET AND DISC.CODTURMA = SMATRICPL.CODTURMA
	   
	  LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY IDTURMADISC ORDER BY IDTURMADISC) AS N,IDTURMADISC,RA,MAX(DTALTERACAO) DTALTERACAO,CODSTATUS FROM SLOGMATRICULA LOGMAT WHERE CONVERT(VARCHAR,DTALTERACAO,103) <= @DTFIM  AND LOGMAT.IDTURMADISC = IDTURMADISC GROUP BY DTALTERACAO,IDTURMADISC,RA,CODSTATUS) AS AA 
	  ON AA.RA = SMATRICPL.RA AND AA.IDTURMADISC = DISC.IDTURMADISC AND SPLETIVO.CODPERLET = /*:CODPERLET*/'2018' 
	  
WHERE SPLETIVO.CODPERLET = /*:CODPERLET*/'2018' 
AND SMATRICPL.RA= @RA -- RA='00007298' -- TIRAR DEPOIS
AND SMATRICPL.CODFILIAL IN ('5','19')
--AND SSTATUS.DESCRICAO LIKE '%MAT%' OR SSTATUS.DESCRICAO LIKE 'PRE%' -- TIRAR ESSA LINHA
AND SMATRICPL.CODTURMA NOT LIKE 'PAN%' AND SMATRICPL.CODTURMA NOT LIKE 'PAE%' AND SMATRICPL.CODTURMA NOT LIKE 'PSA%'
AND SMATRICPL.CODTURMA NOT LIKE 'SCHOOL%' AND SMATRICPL.CODTURMA NOT LIKE 'PABER%'
--AND AA.CODSTATUS = SMATRICPL.CODSTATUS
AND SCURSO.NOME NOT LIKE 'VOLEI%' AND SCURSO.NOME NOT LIKE 'HAND%' AND SCURSO.NOME NOT LIKE 'FUTS%' AND SCURSO.NOME NOT LIKE 'BASQ%'


GROUP BY SMATRICPL.RA,SMATRICPL.CODTURMA,DISC.IDTURMADISC,STURMA.MAXALUNOS, SMATRICPL.CODSTATUS
,SSTATUS.DESCRICAO,SMATRICPL.DTMATRICULA,SPLETIVO.CODPERLET,DISC.CODDISC,AA.N,AA.DTALTERACAO,AA.CODSTATUS,AA.RA,AA.IDTURMADISC

),

TABB AS (
SELECT TOP 1 ROW_NUMBER() OVER(PARTITION BY IDTURMADISC ORDER BY IDTURMADISC) AS N,IDTURMADISC,RA,DTALTERACAO,CODSTATUS FROM SLOGMATRICULA LOGMAT WHERE RA = @RA AND CONVERT(VARCHAR,DTALTERACAO,103) <= @DTFIM  AND LOGMAT.IDTURMADISC = IDTURMADISC GROUP BY DTALTERACAO,IDTURMADISC,RA,CODSTATUS
ORDER BY DTALTERACAO DESC	--  AA.RA = SMATRICPL.RA AND AA.IDTURMADISC = DISC.IDTURMADISC AND SPLETIVO.CODPERLET = /*:CODPERLET*/'2018'
)

SELECT 
 RA
,SERIE
,ALUNOSEM
,MATRICULAS
,REMATRICULAS
,NUMVAGAS
,FALTA
,CODSTATUS2
,(SELECT CODSTATUS2 FROM TABA B WHERE A.RA=B.RA AND A.IDTURMADISC = B.IDTURMADISC AND DTALTERACAO < = @DTFIM) AS DTTESTE
,CODDISC
,DATAFIM
,CODPERLET
,CODSTATUS
,IDTURMADISC
,DTMATRICULA2
,DTMATRICULA
 FROM TABA A (NOLOCK) 



--SELECT * FROM TABA WHERE CODSTATUS2 IN (SELECT CODSTATUS FROM SSTATUS WHERE DESCRICAO LIKE 'MAT%')

--ORDER BY TABA.SERIE,TABA.RA





----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
IDTURMADISC	 RA			IDLOGMATRICULA			DTALTERACAO					CODMOTIVO			CODSTATUS
45539	     00005613	4336446					2018-01-09 15:38:47.000		NULL				1
45539	     00005613	4436252					2018-09-17 10:05:05.000		1					8
*/



/*
SELECT TOP 1 STURMA.NOME,SPLETIVO.CODPERLET,STURMADISC.IDPERLET,SLOGMATRICULA.* FROM SLOGMATRICULA    
JOIN STURMADISC	ON STURMADISC.IDTURMADISC = SLOGMATRICULA.IDTURMADISC
JOIN STURMA ON STURMA.IDHABILITACAOFILIAL = STURMADISC.IDHABILITACAOFILIAL
JOIN SPLETIVO ON SPLETIVO.IDPERLET = STURMADISC.IDPERLET

WHERE RA = '00005613' AND CODPERLET = '2018' AND SLOGMATRICULA.CODSTATUS=8
*/

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'STURMADISC' AND (MASTERFIELD LIKE '%IDTURMADISC%' OR CHILDFIELD LIKE '%IDTURMADISC%')