
SET LANGUAGE PORTUGUÍS
SELECT @@LANGUAGE ;

select @@VERSION,@@ROWCOUNT,@@SERVERNAME,@@SPID,@@TEXTSIZE, @@SERVICENAME


SELECT HOST_NAME(), USER_NAME()


-- PEGAR DADOS
 select  *,SESSIONID from fn_GetContext()

-- VER USERS
 --SELECT * from sys.sysusers


 SELECT SYSTEM_USER

 -- ALTERAR NOME DE TABELA POR PROCEDURE = sp_RENAME '[Tabela.NomeColuna]', '[NovoNomeColuna]' , 'COLUMN'
-- SP_RENAME 'LOGFLAN.DESCRICAO', 'APPNAME','COLUMN'