SELECT SMATRICULA.CODCOLIGADA, SMATRICULA.RA, SMATRICULA.IDHABILITACAOFILIAL, 1 AS C
FROM SMATRICULA (NOLOCK)
JOIN SSTATUS (NOLOCK)
ON SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA
AND SMATRICULA.CODSTATUS = SSTATUS.CODSTATUS
JOIN SHABILITACAOFILIAL (NOLOCK)
ON SMATRICULA.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
AND SMATRICULA.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE SHABILITACAOFILIAL.CODTIPOCURSO <> SSTATUS.CODTIPOCURSO

UNION

SELECT SMATRICPL.CODCOLIGADA,SMATRICPL.RA, SMATRICPL.IDHABILITACAOFILIAL, 2 AS C
FROM SMATRICPL (NOLOCK)
JOIN SSTATUS (NOLOCK)
ON SMATRICPL.CODCOLIGADA = SSTATUS.CODCOLIGADA
AND SMATRICPL.CODSTATUS = SSTATUS.CODSTATUS
JOIN SHABILITACAOFILIAL (NOLOCK)
ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE SHABILITACAOFILIAL.CODTIPOCURSO <> SSTATUS.CODTIPOCURSO

UNION

SELECT SMATRICULA.CODCOLIGADA, SMATRICULA.RA, SMATRICULA.IDHABILITACAOFILIAL, 3 AS C
FROM SMATRICULA (NOLOCK)
JOIN SSTATUS (NOLOCK)
ON SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA
AND SMATRICULA.CODSTATUSRES = SSTATUS.CODSTATUS
JOIN SHABILITACAOFILIAL (NOLOCK)
ON SMATRICULA.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
AND SMATRICULA.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE SHABILITACAOFILIAL.CODTIPOCURSO <> SSTATUS.CODTIPOCURSO

UNION

SELECT SMATRICPL.CODCOLIGADA,SMATRICPL.RA, SMATRICPL.IDHABILITACAOFILIAL, 4 AS C
FROM SMATRICPL (NOLOCK)
JOIN SSTATUS (NOLOCK)
ON SMATRICPL.CODCOLIGADA = SSTATUS.CODCOLIGADA
AND SMATRICPL.CODSTATUSRES = SSTATUS.CODSTATUS
JOIN SHABILITACAOFILIAL (NOLOCK)
ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE SHABILITACAOFILIAL.CODTIPOCURSO <> SSTATUS.CODTIPOCURSO


UNION

SELECT SHABILITACAOALUNO.CODCOLIGADA,SHABILITACAOALUNO.RA, SHABILITACAOALUNO.IDHABILITACAOFILIAL, 5 AS C
FROM SHABILITACAOALUNO (NOLOCK)
JOIN SSTATUS (NOLOCK)
ON SHABILITACAOALUNO.CODCOLIGADA = SSTATUS.CODCOLIGADA
AND SHABILITACAOALUNO.CODSTATUS = SSTATUS.CODSTATUS
JOIN SHABILITACAOFILIAL (NOLOCK)
ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL

WHERE SHABILITACAOFILIAL.CODTIPOCURSO <> SSTATUS.CODTIPOCURSO

ORDER BY RA