SELECT NROCENCUSTOCONT,* FROM PSECAO



SELECT PFUNC.*, PSECAO.NROCENCUSTOCONT FROM PFUNC 
JOIN PSECAO ON PSECAO.CODIGO = PFUNC.CODSECAO
WHERE CODSECAO ='1.06.02.05.02'



SELECT * FROM PESFUNC WHERE CHAPA = '050038'



SELECT PPESSOA.NOME,CODPESSOA,* FROM PFUNC 
JOIN PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
WHERE CHAPA IN ('050086','050093','050204','110004','150006','150009')



SELECT * FROM PFRATEIOFIXO

SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'PFRATEIOFIXO'


SELECT * FROM IPARTIDAOPERACAO