DECLARE @ACC AS INT
SET @ACC = 39525

SELECT 

ISNULL((SELECT MAX(FACORDO.idacordo) FROM FACORDO WHERE  CODCFO = CC.CODCFO AND QTD_ACORDOS > 1 AND IDACORDO < CC.IDACORDO ),0) AS ACORDO_ANT
,*

FROM

(
SELECT DENSE_RANK()OVER(/*PARTITION BY IND*/ ORDER BY VERIFICADOR ASC)-1 AS QTD_ACORDOS, BB.* 

FROM

(
 SELECT AA.*,RIGHT(CODESP,2) CODAA
,CASE RIGHT(CODESP,2) WHEN '2A' THEN CONVERT(VARCHAR,IND)+'2A' ELSE '0' END AS VERIFICADOR

 FROM
(
	SELECT  B.IDACORDO,A.IDLAN,A.NUMERODOCUMENTO,A.CLASSIFICACAO CLASFLAN,B.CLASSIFICACAO CLASSACORDO,A.STATUSLAN,FORMAT(A.MESDECOMPETENCIA,'MM/yyyy') MES_COMP,A.VALORORIGINAL,A.VALORBAIXADO,A.CODCFO ,
	CASE WHEN A.CLASSIFICACAO = 15 THEN B.IDACORDO ELSE 0 END IND
	,E.IDPARCELA, E.TIPOPARCELA ,E.PARCELA
	,CONVERT(VARCHAR,B.IDACORDO)+CONVERT(VARCHAR,B.CLASSIFICACAO)+E.TIPOPARCELA CODESP
	,B.RECCREATEDON,
	(SELECT  COUNT (DISTINCT IDACORDO) FROM FACORDOREL WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL WHERE IDACORDO = B.IDACORDO)) AS CONTA
	
	FROM FLAN A (NOLOCK)
	JOIN FACORDOREL B (NOLOCK) ON (B.IDLAN=A.IDLAN)
	JOIN FACORDO C (NOLOCK) ON (C.IDACORDO=B.IDACORDO)
	JOIN SLAN D (NOLOCK) ON (D.IDLAN = A.IDLAN)
	JOIN SPARCELA E (NOLOCK) ON (E.IDPARCELA=D.IDPARCELA)
	WHERE /*E.IDPARCELA=1837086*/ B.IDACORDO IN (SELECT DISTINCT IDACORDO FROM FACORDOREL WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL WHERE IDACORDO = @ACC))

)AA
 )BB 
  )CC 

 
-- RA 00008963
--IDACORDO = 39525

--SELECT COUNT(DISTINCT IDACORDO) FROM FACORDOREL WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL WHERE IDACORDO = 39525)

--select * from FACORDOrel where IDACORDO in (39524,39525)

--select * from flan where codcfo=013022 --IDLAN=1541006


-- sELECT * FROM FACORDOREL WHERE IDLAN = 1541006

--SELECT TOP 1 IDACORDO FROM FACORDOREL WHERE IDLAN  = 1541042


/*
CODCFO PERLETIVO
2018
013022

*/

--SELECT * FROM FACORDO