;WITH
TABA AS
(
	SELECT SMATRICULA.RA,
	SHABILITACAOFILIAL.CODTIPOCURSO, SPLETIVO.CODPERLET, SCURSO.CODCURSO, 
	SCURSO.NOME CURSO, STURMADISC.CODTURMA,STURMADISC.CODDISC,
	SDISCIPLINA.NOME AS DISCIPLINA, ISNULL(PPESSOA.NOME,'') PROFESSOR
	/*ISNULL(PPESSOA.SEXO,'') SEXO, 
	ISNULL(CAST(CASE WHEN PPESSOA.SEXO = 'F' THEN 1 WHEN PPESSOA.SEXO = 'M' THEN 2 END AS VARCHAR), '')  SEXONUMERAL,
	ISNULL(CONVERT(VARCHAR, PPESSOA.DTNASCIMENTO, 103), '') DTNASCIMENTO,
	ISNULL(CAST(MONTH(PPESSOA.DTNASCIMENTO) AS VARCHAR) + '/' + CAST(YEAR(PPESSOA.DTNASCIMENTO) AS VARCHAR), '') NASCMESANO */
	FROM STURMADISC
	LEFT JOIN SPROFESSORTURMA ON STURMADISC.IDTURMADISC = SPROFESSORTURMA.IDTURMADISC
	LEFT JOIN SPROFESSOR ON SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
	LEFT JOIN PPESSOA ON SPROFESSOR.CODPESSOA = PPESSOA.CODIGO
	INNER JOIN SPLETIVO ON STURMADISC.IDPERLET = SPLETIVO.IDPERLET
		AND STURMADISC.CODTIPOCURSO = SPLETIVO.CODTIPOCURSO
		AND STURMADISC.CODFILIAL = SPLETIVO.CODFILIAL
	INNER JOIN SDISCIPLINA ON SDISCIPLINA.CODDISC = STURMADISC.CODDISC
	INNER JOIN SHABILITACAOFILIAL ON STURMADISC.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
		AND STURMADISC.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
	INNER JOIN SCURSO ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	JOIN SMATRICULA ON SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC AND SMATRICULA.IDPERLET = STURMADISC.IDPERLET
	WHERE SPLETIVO.CODPERLET = '2018/1'--:CODPERLETIVO_S
	AND SPLETIVO.CODFILIAL = 18 --:CODFILIAL_N
	AND SHABILITACAOFILIAL.CODTIPOCURSO =  4
	AND SMATRICULA.CODSTATUS IN (42, 48, 40, 43, 105, 49, 122)
	GROUP BY STURMADISC.CODTURMA,STURMADISC.CODDISC,SMATRICULA.RA, SHABILITACAOFILIAL.CODTIPOCURSO, SPLETIVO.CODPERLET, SCURSO.CODCURSO, 
	SCURSO.NOME, SDISCIPLINA.NOME, PPESSOA.NOME

	
	
)

  SELECT TABA.CODTURMA,TABA.CODDISC,TABA.DISCIPLINA, (COUNT (TABA.RA)) AS CONTA FROM TABA 
  GROUP BY TABA.CODTURMA,TABA.CODDISC,TABA.DISCIPLINA, CODTIPOCURSO, CODPERLET, CODCURSO, 
	 CODTURMA,CODDISC

  ORDER BY CODCURSO, CODTURMA, CODDISC


