--SELECT * FROM MAT WHERE ALUNO LIKE 'ADASSA%'

SET LANGUAGE BRAZILIAN

SELECT DISTINCT
 L.CODFILIAL,
 L.CODTIPOCURSO,
 P.RA,
 PES.NOME,
 CONVERT(VARCHAR,P.DTCOMPETENCIA,103) DTCOMP,
 CONVERT(VARCHAR,P.DTVENCIMENTO,103) DTVENC,
 L.CODPERLET,
 P.VALOR,
 SB.CODBOLSA
 --SLAN.IDLAN


 FROM SPARCELA P

JOIN SPLETIVO L ON L.IDPERLET = P.IDPERLET AND CODTIPOCURSO = 4
JOIN SLAN ON SLAN.IDPARCELA = P.IDPARCELA
JOIN SBOLSALAN SB ON SB.IDLAN = SLAN.IDLAN 
JOIN SALUNO AL ON AL.RA = P.RA 
JOIN PPESSOA PES ON PES.CODIGO = AL.CODPESSOA
JOIN FLAN ON FLAN.IDLAN = SLAN.IDLAN

WHERE DTCOMPETENCIA	BETWEEN '01/09/2020' AND '30/09/2020' AND  NOT EXISTS (SELECT IDLAN FROM SBOLSALAN AS SB1 WHERE SB1.IDPARCELA = P.IDPARCELA AND SB1.CODBOLSA = 104)

ORDER BY NOME


--SELECT * FROM FLAN WHERE IDLAN = 1752508