--    VALORES DOS CURSOS PARA TABELA PG7 REL CONTRATO FIL 19  SQL - 1901515
SELECT 
FORMAT(BERC,'C','PT-BR') AS BERC,
FORMAT(NIVEL,'C','PT-BR') AS NIVEL,
FORMAT(ESPORTE,'C','PT-BR') AS ESPORTE,
FORMAT(PERADD_II_V,'C','PT-BR') AS PERADD_II_V,
FORMAT(PERADD_BER,'C','PT-BR') AS PERADD_BER,
FORMAT(SEMIADD_BER,'C','PT-BR') AS SEMIADD_BER,
FORMAT(SEMIADD_II_V,'C','PT-BR') AS SEMIADD_II_V,

BERC AS BER,
NIVEL AS NIV,
ESPORTE AS ESP,
PERADD_II_V AS ADD_II_V,
PERADD_BER AS ADD_BER,
SEMIADD_BER AS SEMIADD_BER,
SEMIADD_II_V AS SEMIADD_II_V

 FROM (
	SELECT * FROM(
		SELECT 
		BERC,NIVEL,ESPORTE,PERADD_II_V,PERADD_BER,SEMIADD_BER,SEMIADD_II_V
		FROM (

				SELECT DISTINCT PGO.CODPLANOPGTO,PL.CODPERLET,PGO.NOME AS NOME_PLANOPGTO,
				(PLA.VALOR*MAX(PARCELA)) AS VALOR, MAX(PARCELA) AS QTD_PARC
				--,REPLACE(SUBSTRING(PGO.CODPLANOPGTO,0,4),'_','')
				,
				CASE REPLACE(SUBSTRING(PGO.CODPLANOPGTO,0,4),'_','') WHEN 'EI1' THEN 'BERC' 
																	 WHEN 'EI2' THEN 'NIVEL' 
																	 WHEN 'ESP' THEN 'ESPORTE'
																	 WHEN 'PA1' THEN 'PERADD_II_V'
																	 WHEN 'PAB' THEN 'PERADD_BER'
																	 WHEN 'PSA' THEN 'SEMIADD_BER'
																	 WHEN 'SA2' THEN 'SEMIADD_II_V'
																	 END AS SERIE

				 FROM SPLANOPGTO AS PGO
				JOIN SPARCPLANO AS PLA ON PLA.CODPLANOPGTO = PGO.CODPLANOPGTO AND PLA.IDPERLET = PGO.IDPERLET
				JOIN SPLETIVO AS PL ON PL.IDPERLET = PGO.IDPERLET
				JOIN SSERVICO ON SSERVICO.CODSERVICO = PLA.CODSERVICO AND SSERVICO.NOME NOT LIKE 'LIVRO%'

				WHERE PGO.IDPERLET = 292  AND PGO.NOME NOT LIKE '%FILANTROPIA%' AND PL.CODFILIAL = 19

				GROUP BY PGO.CODPLANOPGTO,PL.CODPERLET,PGO.NOME,PLA.PARCELA,PLA.VALOR

				HAVING SUM(PARCELA) = 12 
			

		) AS TAB
		PIVOT (MAX(VALOR) FOR SERIE IN ([BERC],[NIVEL],[ESPORTE],[PERADD_II_V],[PERADD_BER],[SEMIADD_BER],[SEMIADD_II_V])
		) AS COL
		) TABB

		UNPIVOT (VALOR FOR SERIE IN ([BERC],[NIVEL],[ESPORTE],[PERADD_II_V],[PERADD_BER],[SEMIADD_BER],[SEMIADD_II_V])) AS UNPIVOT1
		) TABC

		PIVOT (MAX(VALOR) FOR SERIE IN ([BERC],[NIVEL],[ESPORTE],[PERADD_II_V],[PERADD_BER],[SEMIADD_BER],[SEMIADD_II_V])
		) AS DDD