SELECT 
FORMAT(EF1,'C','PT-BR') AS EF1,
FORMAT(EF2,'C','PT-BR') AS EF2,
FORMAT(EM,'C','PT-BR') AS EM,
FORMAT(EM3,'C','PT-BR') AS EM3,
FORMAT(PRV,'C','PT-BR') AS PRV,
FORMAT(ADD_FI,'C','PT-BR') AS ADD_FI,
FORMAT(ADD_FII,'C','PT-BR') AS ADD_FII,
FORMAT(SEMIADD_FI,'C','PT-BR') AS SEMIADD_FI,
FORMAT(SEMIADD_FII,'C','PT-BR') AS SEMIADD_FII,
FORMAT(ESPORTE,'C','PT-BR') AS ESPORTE

,EF1 AS P_EF1
,EF2 AS P_EF2
,EM AS P_EM
,EM3 AS P_EM3
,PRV AS P_PRV
,ADD_FI AS P_ADD_FI
,ADD_FII AS P_ADD_FII
,SEMIADD_FI AS P_SEMIADD_FI
,SEMIADD_FII AS P_SEMIADD_FII
,ESPORTE AS P_ESPORTE

 FROM (
	SELECT * FROM(
		SELECT 
		EF1,EF2,EM,EM3,PRV,ADD_FI,ADD_FII,SEMIADD_FI,SEMIADD_FII,ESPORTE
		FROM (

				SELECT DISTINCT PGO.CODPLANOPGTO,PL.CODPERLET,PGO.NOME AS NOME_PLANOPGTO,
				(PLA.VALOR*MAX(PARCELA)) AS VALOR, MAX(PARCELA) AS QTD_PARC
				--,REPLACE(SUBSTRING(PGO.CODPLANOPGTO,0,4),'_','') AS SERIE
				,
				CASE REPLACE(SUBSTRING(PGO.CODPLANOPGTO,0,4),'_','') WHEN 'PA1' THEN 'ADD_FI' 
																	 WHEN 'PA2' THEN 'ADD_FII' 
																	 WHEN 'ESP' THEN 'ESPORTE'													
																	 WHEN 'PSA' THEN 'SEMIADD_FI'
																	 WHEN 'SA2' THEN 'SEMIADD_FII'
																	 ELSE REPLACE(SUBSTRING(PGO.CODPLANOPGTO,0,4),'_','')
																	 END AS SERIE

				 FROM SPLANOPGTO AS PGO
				JOIN SPARCPLANO AS PLA ON PLA.CODPLANOPGTO = PGO.CODPLANOPGTO AND PLA.IDPERLET = PGO.IDPERLET
				JOIN SPLETIVO AS PL ON PL.IDPERLET = PGO.IDPERLET
				JOIN SSERVICO ON SSERVICO.CODSERVICO = PLA.CODSERVICO AND SSERVICO.NOME NOT LIKE 'LIVRO%'

				WHERE PGO.IDPERLET = 289  AND PGO.NOME NOT LIKE '%FILANTROPIA%' AND PL.CODFILIAL = 5

				GROUP BY PGO.CODPLANOPGTO,PL.CODPERLET,PGO.NOME,PLA.PARCELA,PLA.VALOR

				HAVING SUM(PARCELA) = 12 
			

		) AS TAB
		PIVOT (MAX(VALOR) FOR SERIE IN ([EF1],[EF2],[EM],[EM3],[PRV],[ADD_FI],[ADD_FII],[SEMIADD_FI],[SEMIADD_FII],[ESPORTE])
		) AS COL
		) TABB

		UNPIVOT (VALOR FOR SERIE IN ([EF1],[EF2],[EM],[EM3],[PRV],[ADD_FI],[ADD_FII],[SEMIADD_FI],[SEMIADD_FII],[ESPORTE])) AS UNPIVOT1
		) TABC

		PIVOT (MAX(VALOR) FOR SERIE IN ([EF1],[EF2],[EM],[EM3],[PRV],[ADD_FI],[ADD_FII],[SEMIADD_FI],[SEMIADD_FII],[ESPORTE])
		) AS DDD