/**********************************APROVAITAMENTO DE ESTUDOS***************************************/
-- OK

SELECT 
	SHISTDISCFAC.CODCOLIGADA
	,SHISTDISCFAC.RA
	,'' AS CODGRADE
	,SHISTDISCFAC.IDHABILITACAOFILIAL
	,SDISCGRADE.CODPERIODO
	,SDISCIPLINA.NOME AS DISCIPLINAS
	,'' AS DISCEQQUIV
	,'' AS DISCIPLINA
	,'' AS NOMEEQUIVALENTE
	,SPLETIVO.CODPERLET
	,SHISTDISCFAC.CARGAHORARIA
	,SHISTDISCFAC.FALTAS	
	,100 PERCPRESENCA
	,0.001 MYASS
	,CAST (SHISTDISCFAC.NOTA AS NUMERIC (10,2)) AS NOTA
	,SSTATUS.DESCRICAO AS STATUS
	,SSTATUS.CODEXTERNO
	,'' AS PROFTIT
	
	
	FROM 
		SHISTDISCFAC (NOLOCK)
	 JOIN 
		SSTATUS (NOLOCK)
			ON
				SHISTDISCFAC.CODCOLIGADA = SSTATUS.CODCOLIGADA
			AND 
				SHISTDISCFAC.CODSTATUS = SSTATUS.CODSTATUS
	JOIN 
		SHABILITACAOFILIAL (NOLOCK)
			ON 
				SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND 
				SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCFAC.IDHABILITACAOFILIAL
				
	JOIN 
		SDISCGRADE (NOLOCK)
			ON 
				SDISCGRADE.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SDISCGRADE.CODCURSO=SHABILITACAOFILIAL.CODCURSO
			AND
				SDISCGRADE.CODGRADE=SHABILITACAOFILIAL.CODGRADE
			AND 
				SDISCGRADE.CODHABILITACAO=SHABILITACAOFILIAL.CODHABILITACAO
			AND 
				SDISCGRADE.CODDISC = SHISTDISCFAC.CODDISC
	JOIN 
		SDISCIPLINA (NOLOCK)
			ON 
				SDISCIPLINA.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND	
				SDISCIPLINA.CODDISC = SHISTDISCFAC.CODDISC
				
	JOIN 
		SPLETIVO (NOLOCK)
			ON 
				SPLETIVO.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND 
				SPLETIVO.IDPERLET = SHISTDISCFAC.IDPERLET 
				
				
			WHERE 
				SHISTDISCFAC.CODCOLIGADA = 1
			AND 
				SHISTDISCFAC.RA = '00001775' --@RA

				ORDER BY CODPERIODO,DISCIPLINAS