SELECT HB.CODLOCAL
 , HB.ABERTURA  AS DT_ABERTURA
 , HB.CODSTATUS
 , HB.ASSUNTOOC
 , HTA.DESCRICAO
 , HB.CODATENDIMENTO
 , HB.CODGRUPOATENDIMENTO
 , HTA.CODTIPOATENDIMENTO
 , HB.CODATENDENTE
 , HA.CODUSUARIO
 , P.NOME AS ATENDENTE1
 , HB.CODTAREFA
 , HB.CODTAREFAANTERIOR
 , HB.CODLOCALENTREGA
 --, HTA.*

 FROM HATENDIMENTOBASE AS HB

 JOIN HTAREFA AS HT ON HT.CODTAREFA = HB.CODTAREFA
 JOIN HTIPOATENDIMENTO AS HTA ON HTA.CODTIPOATENDIMENTO = HB.CODTIPOATENDIMENTO
 JOIN HATENDENTE AS HA ON HA.CODATENDENTE = HB.CODATENDENTE
 JOIN PPESSOA AS P ON P.CODIGO = HA.CODPESSOA

WHERE HB.CODATENDIMENTO = '25601'