--SELECT * FROM SATIVIDADE
--SELECT TOP 10 * FROM MAT WHERE CODFILIAL = 18 AND CODPERLET = '2019/2' AND STATUS LIKE '%MAT%' AND CODTURMA LIKE '%COMP%'

SELECT DISTINCT 
 SAT.IDOFERTA
,SPL.CODFILIAL
,SAT.IDHABILITACAOFILIAL
,SC.CODCURSO
,SC.NOME AS CURSO
,SAT.RA
,PES.NOME AS ALUNO
,SPL.IDPERLET
,SPL.CODPERLET
,SAT.CODMODALIDADE
,SAT.CARGAHORARIA
,AT.CARGAHORGRADE AS CH_APROVEITADA
,SAT.CREDITOS
,AT.VAGAS
,AT.LOCALINSCRICAO
,ISNULL(CONVERT(VARCHAR,SAT.DATAINICIO,103),'') AS DATA_INI
,ISNULL(CONVERT(VARCHAR,SAT.DATAFIM,103),'') AS DATA_FIM
,ISNULL(CONVERT(VARCHAR,AT.DTINICIALINSC,103),'') AS DT_INSC_INI
,ISNULL(CONVERT(VARCHAR,AT.DTFINALINSC,103),'') AS DT_INSC_FIM
,ISNULL(AT.DESCRICAO,'') AS DESCRICAO_ATIVIDADE
,CONVERT(VARCHAR(1000),AT.CONTEUDO) AS CONTEUDO
,CONVERT(VARCHAR(1000),AT.OBSERVACAO) AS OBS
,CONVERT(VARCHAR,SAT.RECCREATEDON,103) AS DT_INSCRICAO

 FROM SATIVIDADEALUNO (NOLOCK) AS SAT
 JOIN SHABILITACAOALUNO (NOLOCK) AS SHA ON SHA.RA = SAT.RA AND SHA.IDHABILITACAOFILIAL = SAT.IDHABILITACAOFILIAL AND  SHA.CODCOLIGADA = SAT.CODCOLIGADA
 JOIN SATIVIDADE (NOLOCK) AS AT ON AT.IDOFERTA = SAT.IDOFERTA
 JOIN SALUNO (NOLOCK) AS SA ON SA.RA = SAT.RA
 JOIN PPESSOA (NOLOCK) AS PES ON PES.CODIGO = SA.CODPESSOA
 JOIN SHABILITACAOFILIAL (NOLOCK) AS SHF ON SHF.IDHABILITACAOFILIAL = SHA.IDHABILITACAOFILIAL 
 JOIN SCURSO (NOLOCK) AS SC ON SC.CODCURSO = SHF.CODCURSO
 JOIN SPLETIVO (NOLOCK) AS SPL ON SPL.IDPERLET = SAT.IDPERLET

 WHERE SAT.IDOFERTA = 9
 --ORDER BY CURSO,CODCURSO,ALUNO

 --    SELECT * FROM GLINKSREL WHERE MASTERTABLE= 'SATIVIDADE'

-- SELECT * FROM SHABILITACAOFILIAL WHERE IDHABILITACAOFILIAL = 1630
