--SELECT * FROM TFFILIAL WHERE CODFILIAL=21

SELECT * FROM GCAMPOS WHERE COLUNA LIKE '%ATIVI%'

SELECT * FROM FCFO WHERE CODCFO = '53.416.921/0021-40'

SELECT* FROM PSECAO WHERE CGC = '53.416.921/0021-40'

SELECT CODIGOSERVICO, * FROM TMOV WHERE TMOV.CODFILIAL = 21 

 
SELECT * FROM GCAMPOS WHERE TABELA = 'TMOV' -- CODTDO	Código do tipo de documento  /  CODTMV	Código do Tipo de Movimento / CODTB1FAT Código Tabela Classificação1 Produto       

SELECT IDNAT,TIPOSERVICO,* FROM DLAF WHERE CODFILIAL = 21




SELECT * FROM TITMMOV WHERE CODFILIAL = 21

SELECT * FROM GFILIAL WHERE CODFILIAL = 21  --85.20-1-00 CODATIVIDPRINC CODMUNICIPIOSERV 06902

SELECT * FROM GLINKSREL WHERE MASTERFIELD = 'CODATIVIDPRINC'

SELECT * FROM DLAF WHERE CODFILIAL = 21

SELECT * FROM ZNFe WHERE CODFILIAL = 21

SELECT * FROM TMOV WHERE  CODFILIAL = 21 -- IDMOVCFO  CODCPG CODLAF CODIGOSERVICO CODMUNSERVICO  CODTDO	Código do tipo de documento

SELECT * FROM GCAMPOS WHERE TABELA IN ('TMOV')

SELECT CODUSUARIO,* FROM PPESSOA WHERE NOME LIKE 'fernando%'--NOME LIKE '%Fernando Bassaco de Almeida%' --CODUSUARIO ='210027'

SELECT * FROM PFUNC WHERE CHAPA = 210027

SELECT * FROM GUSUARIO WHERE NOME LIKE '%FERNANDO%BASSACO%' OR NOME LIKE '%DENNYSON%' --CODUSUARIO = 210027




