DECLARE @DATA_CORTE AS DATE , @DATA_INICIAL AS DATE , @DATA_FINAL AS DATE
DECLARE @CODPERLET AS VARCHAR(10), @CODFILIAL AS VARCHAR(2),  @NOME_SERVICO AS VARCHAR(20), @COD_TIPO_CURSO AS VARCHAR(2)

SET LANGUAGE PORTUGUÍS
SET DATEFORMAT DMY

SET @DATA_CORTE = '30/12/2018'--'30/12/2018' --'2018-12-30' --'2019-12-30'

SELECT  IDLAN, DATACANCELBAIXA
, (SELECT MAX(DATABAIXA) FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = BB.IDLAN AND CONVERT(VARCHAR(10),FLANBAIXA.DATABAIXA,103) < = @DATA_CORTE AND DATACANCELBAIXA IS NULL ) AS DATABAIXA1
, (SELECT MAX(STATUS) FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = BB.IDLAN AND CONVERT(VARCHAR(10),FLANBAIXA.DATABAIXA,103) < = @DATA_CORTE AND DATACANCELBAIXA IS NULL ) AS STATUS1
,CONVERT(MONEY,SUM(VALORORIGINAL)) AS VALORORIGINAL
,CONVERT(MONEY,SUM(VALORBAIXA)) AS VALORBAIXA

 FROM FLANBAIXA BB WHERE IDLAN = 932503 AND DATABAIXA < = @DATA_CORTE --AND DATACANCELBAIXA IS NULL

 GROUP BY IDLAN,DATACANCELBAIXA

 --valororiginalbx , valorbx,  valorliquido


 --SELECT * FROM FLANBAIXA WHERE IDLAN = 1518738 

 -- VL BX  = 5500 E VLORIGINAL  = 5456,73

 --SELECT * FROM FLAN WHERE IDLAN = 1518738

/* SELECT * 
 FROM SMATRICPL
 LEFT JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET WHERE SPLETIVO.DESCRICAO LIKE '%POS%'
 */