USE [Z.BaseTeste]

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPROVAS'


--SELECT * FROM SNOTAS WHERE RA='00019575' AND CODPROVA = 1   AND IDTURMADISC= 63486



--SELECT * FROM SMATRICPL WHERE RA= '00019575'

--SELECT CODPROVA ,IDTURMADISC,RA,

SELECT (SUM(NOTA) / COUNT(CODPROVA)) * 0.35 AS NOTA FROM SNOTAS WHERE RA = '00019575' AND  IDTURMADISC = 63486 AND CODETAPA = 2 --AND IDTURMADISC = 63486


--SELECT * FROM STURMADISC WHERE IDTURMADISC= 63486


--SELECT * FROM SPLETIVO WHERE IDPERLET = 286


--SELECT * FROM SNOTAETAPA WHERE RA='00019575' AND IDTURMADISC= 63486


--  SELECT * FROM SMODETAPAPLETIVO WHERE IDPERLET = 297 AND CODETAPA = 1


--SELECT * FROM SCODAVALIACAO


--SELECT * FROM GLINKSREL WHERE MASTERTABLE ='SPROVAS'

--SELECT * FROM SMODPROVAPLETIVO WHERE IDPERLET = 297 AND CODPROVA = 1

--SELECT * FROM SPROVAS WHERE IDTURMADISC = 63486 AND CODPROVA = 1

--  SELECT * FROM SNOTAS WHERE RA='00019575' AND IDTURMADISC = 63486

--SELECT * FROM MAT WHERE RA = '00019575'

  --DISABLE TRIGGER TR_LOCK_GER_PARC_F18 ON FLAN ;
  --GO

  --DISABLE TRIGGER TR_SCONTRATO_F18 ON SCONTRATO ;
  --GO