DECLARE @VAR AS INT

SET @VAR = 0

SELECT @VAR = (CASE WHEN @VAR > CONF THEN @VAR ELSE CONF  END)  FROM

(

SELECT CASE WHEN NOTA IS NULL THEN 999 ELSE 1 END AS CONF, (SUM(NOTA) / COUNT(CODPROVA))  AS NOTA

FROM SNOTAS 

WHERE RA = '00019575' /*:FRM_RA_AV*/
AND IDTURMADISC = 63486 /*:FRM_IDTD_AV*/
AND CODETAPA = 2 /*:FRM_PROV_AV1*/

GROUP BY NOTA
)AS TAB

GROUP BY NOTA,CONF

SELECT @VAR


SELECT CASE WHEN @VAR = 1 
            THEN (
			SELECT (SUM(NOTA) / COUNT(CODPROVA))  AS NOTA

			FROM SNOTAS 

			WHERE RA = '00019575' /*:FRM_RA_AV*/
			AND IDTURMADISC = 63486 /*:FRM_IDTD_AV*/
			AND CODETAPA = 2  ) 

			ELSE

			 NULL
            END