SELECT N.CODCOLIGADA
      ,N.CODPROVA
	  ,N.CODETAPA
	  ,N.TIPOETAPA
	  ,N.IDTURMADISC
	  ,N.RA
      --,ETP.DESCRICAO AS NOMEETAPA
	  --,MAT.NUMDIARIO
	  ,STD.CODDISC
	  ,SDISCIPLINA.NOME AS DISCIPLINA,PPESSOA.NOME
	  ,STD.CODTURMA


 FROM SNOTAS AS N
 JOIN SETAPAS AS ETP ON ETP.CODETAPA = N.CODETAPA AND ETP.IDTURMADISC = N.IDTURMADISC
 JOIN STURMADISC AS STD ON STD.IDTURMADISC = N.IDTURMADISC
 JOIN SMATRICULA AS MAT ON MAT.IDTURMADISC = N.IDTURMADISC AND MAT.RA = N.RA
 JOIN SPLETIVO AS PL ON PL.IDPERLET = MAT.IDPERLET
 JOIN SSTATUS ON SSTATUS.CODSTATUS = MAT.CODSTATUS
 JOIN SALUNO AS AL ON AL.RA = MAT.RA
 JOIN PPESSOA ON PPESSOA.CODIGO = AL.CODPESSOA
 JOIN SHABILITACAOFILIAL AS SHABFIL ON SHABFIL.IDHABILITACAOFILIAL = STD.IDHABILITACAOFILIAL
 JOIN SDISCGRADE AS DISCG ON SHABFIL.CODGRADE = DISCG.CODGRADE AND DISCG.CODDISC = STD.CODDISC AND DISCG.CODCURSO = SHABFIL.CODCURSO AND DISCG.CODHABILITACAO = SHABFIL.CODHABILITACAO --AND DISCG.POSHIST < 20
 JOIN SDISCIPLINA ON SDISCIPLINA.CODDISC = DISCG.CODDISC

 WHERE PL.CODPERLET = '2019' AND SSTATUS.DESCRICAO LIKE 'MAT%' AND N.TIPOETAPA = 'N' --AND MAT.RA ='00008105'

 ORDER BY RA,CODETAPA

 --   SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SHABILITACAOFILIAL'