
-----------------------------------------------------------------------------------
--************************************************************************************
DECLARE @FILIAL AS INT
DECLARE @DATA_INI AS DATE, @DATA_FIM AS DATE
DECLARE @CODPERLET AS VARCHAR(6)

SET LANGUAGE PORTUGUÍS


SET @FILIAL = 5
SET @CODPERLET = '2019'
SET @DATA_INI = '01/01/2018'
SET @DATA_FIM = '31/03/2019'

SELECT 
 SCONTRATO.CODCOLIGADA
,FLAN.CODFILIAL
,SPLETIVO.CODPERLET
,(SELECT NOME FROM STIPOCURSO WHERE CODTIPOCURSO = SPLETIVO.CODTIPOCURSO) AS CONTEXTO
,SPARCELA.RA
,PPESSOA.NOME
,SPLANOPGTO.CODPLANOPGTO
,SPARCELA.PARCELA
,SCONTRATO.STATUS STATUS_CONTRATO
,CONVERT(NVARCHAR,CONVERT(VARCHAR(10),SPARCELA.DTVENCIMENTO,103)) AS DTVENCIMENTO
,SCONTRATO.CODCONTRATO
,SSERVICO.NOME SERVICO
,SSTATUS.DESCRICAO AS STATUS_MATRICULA
,SMATRICPL.CODTURMA

,ISNULL(CONVERT(VARCHAR,(SELECT IDBOLETO FROM FBOLETO WHERE IDBOLETO = FLAN.IDBOLETO)),CONVERT(VARCHAR,'N√O EMITIDO')) AS VER_BOL
,FLAN.IDBOLETO
,FLAN.IDLAN
,SPARCELA.IDPARCELA 
,CASE FLAN.STATUSLAN
WHEN 0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
WHEN 3 THEN 'ACORDO'
WHEN 4 THEN 'BX_PARCIAL'  END AS STATUSLAN


FROM FLAN (NOLOCK)
LEFT JOIN SLAN (NOLOCK) ON SLAN.IDLAN = FLAN.IDLAN
LEFT JOIN SPARCELA (NOLOCK) ON SPARCELA.IDPARCELA = SLAN.IDPARCELA
LEFT JOIN SPLETIVO (NOLOCK) ON SPLETIVO.IDPERLET = SPARCELA.IDPERLET
LEFT JOIN SALUNO (NOLOCK) ON SALUNO.RA = SPARCELA.RA
LEFT JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA
LEFT JOIN SCONTRATO (NOLOCK) ON SCONTRATO.RA = SPARCELA.RA AND SCONTRATO.IDPERLET = SPARCELA.IDPERLET AND SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO 
LEFT JOIN SPLANOPGTO (NOLOCK) ON SPLANOPGTO.CODPLANOPGTO = SCONTRATO.CODPLANOPGTO
LEFT JOIN SSERVICO (NOLOCK) ON SSERVICO.CODSERVICO = SPARCELA.CODSERVICO 
LEFT JOIN SMATRICPL (NOLOCK) ON  SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET AND SMATRICPL.RA = SCONTRATO.RA
LEFT JOIN SSTATUS (NOLOCK) ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS

WHERE  FLAN.CODFILIAL = @FILIAL AND SPLETIVO.CODPERLET = @CODPERLET AND SPARCELA.DTVENCIMENTO BETWEEN @DATA_INI AND @DATA_FIM  
AND SPARCELA.IDPARCELA NOT IN (

select idparcela from slan left join flan on 
slan.idlan = flan.idlan where flan.statuslan <> 2
and idparcela = sparcela.IDPARCELA
) 
  --AND STATUSLAN = 2
--AND SPLANOPGTO.CODPLANOPGTO IS NOT NULL 
--AND FLAN.IDBOLETO IS NULL
--AND SSTATUS.DESCRICAO LIKE '%MAT%' --SMATRICPL.CODSTATUS NOT IN  (5,8)
--AND SPARCELA.RA = '00025565'
--AND FLAN.IDLAN = 1553622
--ORDER BY NOME,IDLAN
--AND SPARCELA.RA = '00024294'
-- 00025565	DAYVISON ESPINDULA PLASTER LAN 1565532
--************************************************************************************
-------------------------------------------------------------------------

/*
select * from FBOLETO

select * from FBOLETOHISTORICO

SELECT * FROM GCAMPOS WHERE TABELA LIKE '%FBOL%'

SELECT IDBOLETO,IDLAN,* FROM FLAN WHERE FLAN.CODFILIAL = 18 

SELECT * FROM FLANBOLETO

SELECT * FROM GLINKSREL WHERE  MASTERFIELD LIKE '%IDPERLET%'
SELECT * FROM FLANREMESSA WHERE IDLAN = 1547222

SELECT * FROM SPARCELA WHERE IDPARCELA = 1737720

SELECT * FROM FBOLETO

SELECT * FROM SMATRICPL WHERE CODFILIAL = 5

SELECT * FROM GCAMPOS WHERE TABELA LIKE '%SSERVICO%'--COLUNA LIKE '%TIPOCURSO%'

SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE '%SSERVICO%' --LIKE '%TIPOCURSO%'

SELECT * FROM STIPOCURSO

SELECT * FROM SPESSOA

SELECT * FROM SALUNO

SELECT * FROM SPLANOPGTO

SELECT * FROM SCONTRATO WHERE RA = '00025565'

SELECT * FROM SPLETIVO WHERE IDPERLET = 267
*/
--SELECT * FROM FLAN WHERE IDLAN=1565532


/*
SELECT * FROM FLAN 
LEFT JOIN SLAN ON SLAN.IDLAN = FLAN.IDLAN
LEFT JOIN SPARCELA ON SPARCELA.IDPARCELA = SLAN.IDPARCELA
LEFT JOIN SPLETIVO ON SPLETIVO.IDPERLET = SPARCELA.IDPERLET
WHERE IDBOLETO IS NULL AND FLAN.CODFILIAL = 5 AND SPLETIVO.CODPERLET='2019' AND FLAN.STATUSLAN <> 2
*/

--SELECT * FROM SLAN WHERE IDLAN=1553622

/*RA	IDPERLET	CODCONTRATO	IDHABILITACAOFILIAL	CODPLANOPGTO
00005083	265	186614	479	ESP_4_2019*/

--SELECT * FROM SCONTRATO WHERE CODCONTRATO IN (183675,186614)


--SELECT * FROM SPLANOPGTO WHERE CODPLANOPGTO IN ('EF2_19_P12','ESP_4_2019')

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SCONTRATO' 

--SELECT * FROM SLAN WHERE IDPARCELA=1855541

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'FLAN' AND CHILDTABLE = 'SPARCELA'

