-- ALTERAÇÃO ANUAL SOLICITADA PELO SR LUIZ

BEGIN TRAN

UPDATE CPARTIDA SET CODCCUSTO = '1.01.01.01.01' WHERE CODCCUSTO IS NULL

/* ***********CONFERENCIA************

SELECT C1.IDLANCAMENTO,C1.CODLOTE,C1.DESCRICAO,C2.IDPARTIDA,CONVERT(VARCHAR,C2.DATA,103) AS DATA,C2.CODCCUSTO,C2.DEBITO,C2.CREDITO FROM CLANCAMENTO AS C1

JOIN CPARTIDA AS C2 ON C2.IDLANCAMENTO = C1.IDLANCAMENTO AND C2.CODLOTE = C1.CODLOTE
 
 
 WHERE C2.CODCCUSTO IS NULL --CPARTIDA.IDLANCAMENTO = 2692082

 ORDER BY DATA
*/

--COMMIT