SET LANGUAGE PORTUGUÊS

SELECT A.CODCOLIGADA
,A.IDPERLET
,A.IDHABILITACAOFILIAL
,A.RA
,A.CODFILIAL
,F.CODCURSO
,F.NOME CURSO
,A.CODTURMA
,A.CODSTATUS
,B.DESCRICAO STATUS
,C.CODPERLET CODIPERIODOLET
,D.NOME ALUNO
,CONVERT(VARCHAR,DATEPART(DD,D.DTNASCIMENTO)) +' de '+ CONVERT(VARCHAR,DATENAME(M,D.DTNASCIMENTO)) + ' de '+ CONVERT(VARCHAR,DATEPART(YYYY,D.DTNASCIMENTO)) AS DATA_NASC
,D.NATURALIDADE CIDADE_NASC
,D.ESTADONATAL ESTADO_NASC
,I.NOME ESTADO_NOME
,D.CARTIDENTIDADE
,ISNULL(DPAI.NOME,'NÃO INFORMADO') PAINOME
,ISNULL(DMAE.NOME,'NÃO INFORMADO') MAENOME
,(CASE WHEN E.DECRETOHABILITACAO IS NULL THEN '.' ELSE ', '+ E.DECRETOHABILITACAO END) AS PORT_CURSO
,H.RECAUTORIZ AS PORT_INST
,G.DTCOLACAOGRAU
,DBO.INITCAP((SELECT NOME FROM PPESSOA WHERE CODIGO = J.CODPESSOASEC1)) AS SECRETARIA
,(CASE WHEN D.SEXO = 'F' THEN 'nascida' ELSE 'nascido' END) AS NASCIDO
,(CASE WHEN D.SEXO = 'F' THEN 'portadora' ELSE 'portador' END) AS PORTADOR
,(CASE WHEN D.SEXO = 'F' THEN 'filha' ELSE 'filho' END) AS FILHO

FROM SMATRICPL A (NOLOCK)

 LEFT JOIN SSTATUS B (NOLOCK) ON A.CODSTATUS= B.CODSTATUS
 LEFT JOIN SPLETIVO C (NOLOCK) ON C.IDPERLET = A.IDPERLET
 LEFT JOIN PPESSOA D (NOLOCK) ON D.CODUSUARIO = A.RA
 LEFT JOIN SPESSOA DSP (NOLOCK) ON DSP.CODIGO = D.CODIGO
 LEFT JOIN PPESSOA DPAI (NOLOCK) ON DPAI.CODIGO = DSP.CODPESSOAPAI
 LEFT JOIN PPESSOA DMAE (NOLOCK) ON DMAE.CODIGO = DSP.CODPESSOAMAE
 LEFT JOIN SHABILITACAOFILIAL E (NOLOCK) ON E.IDHABILITACAOFILIAL=A.IDHABILITACAOFILIAL
 LEFT JOIN SCURSO F (NOLOCK) ON F.CODCURSO = E.CODCURSO
 LEFT JOIN SHABILITACAOALUNO G (NOLOCK) ON G.RA = A.RA AND G.IDHABILITACAOFILIAL = A.IDHABILITACAOFILIAL
 LEFT JOIN SAUTORIZACAOFILIAL H (NOLOCK) ON H.CODCOLIGADA = 1
 LEFT JOIN GETD I (NOLOCK) ON I.CODETD = D.ESTADONATAL
 LEFT JOIN SDIRECAOFILIAL J (NOLOCK) ON J.CODFILIAL = 18 AND (J.DTFIM >= GETDATE() OR J.DTFIM IS NULL)
 
WHERE A.CODFILIAL=18
AND (A.RA='00015121') --OR (A.CODTURMA LIKE '%AD7%')
AND A.CODSTATUS = 46 /*CONCLUINTE*/
AND C.CODPERLET = '2018/1'
--or d.nome like '%eric jose%'