--  ADASSA FXCX COM OS CÓDIGOS 709 E 249
--  FLANBAIXA LIGA FLAN COM TABELA: FXCX CHAVE: IDXCX

SELECT PPESSOA.NOME,TAB.* FROM

(

		SELECT DISTINCT
		 C.RA
		,FX.CODFILIAL
		,FLAN.IDLAN
		,FX.NUMERODOCUMENTO
		,FX.HISTORICO
		,FX.CODCXA
		--, REPLACE(REPLACE(dbo.RemoveCaracteresNaoInteiros(SUBSTRING(FX.HISTORICO,CHARINDEX('.',FX.HISTORICO,1)+2, 8)),',',''),'"','') AS IDLANFXCX
		,FX.IDXCX

		FROM FXCX (NOLOCK) AS FX
		JOIN FLAN (NOLOCK) ON FLAN.IDLAN = REPLACE(REPLACE(dbo.RemoveCaracteresNaoInteiros(SUBSTRING(FX.HISTORICO,CHARINDEX('.',FX.HISTORICO,1)+2, 8)),',',''),'"','')
		JOIN SLAN (NOLOCK) ON SLAN.IDLAN = FLAN.IDLAN
		JOIN SPARCELA (NOLOCK) AS PA ON PA.IDPARCELA = SLAN.IDPARCELA
		JOIN SCONTRATO (NOLOCK) C ON C.CODCONTRATO = PA.CODCONTRATO AND C.RA = PA.RA AND C.IDPERLET = PA.IDPERLET
		-- JOIN SALUNO (NOLOCK) AS AL ON AL.RA = C.RA

		WHERE FX.CODCXA IN ('709','249') AND FX.CODFILIAL = 18
) TAB

JOIN SALUNO ON SALUNO.RA = TAB.RA
JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA