SELECT N.NOTAFALTA
, D.NUMCREDITOS
, D.CODDISC
, M.CODSTATUS
, M.CODSTATUSRES
, D.NOME
,M.IDHABILITACAOFILIAL
FROM SMATRICULA M
, STURMADISC T
, SDISCIPLINA D
, SETAPAS E
, SNOTAETAPA N
WHERE M.CODCOLIGADA = 1 --:FRM_CR.COL
AND M.RA = '00012745'--:FRM_CR.RA
AND M.IDTURMADISC = T.IDTURMADISC
AND M.CODSTATUSRES = 42

AND D.CODCOLIGADA = T.CODCOLIGADA
AND D.CODDISC = T.CODDISC
AND E.CODCOLIGADA = M.CODCOLIGADA
AND E.IDTURMADISC = M.IDTURMADISC
AND N.RA = M.RA
AND E.TIPOETAPA = 'N'
AND E.CODCOLIGADA = N.CODCOLIGADA
AND E.IDTURMADISC = N.IDTURMADISC
AND E.CODETAPA = N.CODETAPA
AND E.TIPOETAPA = N.TIPOETAPA
AND E.ETAPAFINAL = 'S'