-- 00020294    00019164
SELECT DISTINCT
-- MAT.CODFILIAL
--STD.CODTURMA
MAT.RA
,P.NOME AS ALUNO
,P.CPF
--,ST.CODSTATUS
--,ST.DESCRICAO AS STATUS
--,HABFIL.CODGRADE
--,GRD.DESCRICAO AS GRADE
--,MAT.IDHABILITACAOFILIAL
--,HABFIL.CODHABILITACAO
--,PER.CODPERLET AS CODPERLET
--,PER.IDPERLET
--,PER.CODTIPOCURSO 
,SCURSO.CODCURSO
,SCURSO.NOME AS CURSO
--,STD.CODDISC
--,DISCI.NOME AS DISCIPLINA
--,PEND.NOTA AS NOTA_PEND
--,HBALUNO.DTCOLACAOGRAU


 FROM SMATRICPL AS MAT (NOLOCK)
JOIN (SELECT  CODSTATUS,DESCRICAO FROM SSTATUS (NOLOCK)  WHERE SSTATUS.DESCRICAO LIKE '%MAT%' OR SSTATUS.DESCRICAO LIKE '%TRANC%') AS ST ON ST.CODSTATUS = MAT.CODSTATUS 
JOIN SHABILITACAOFILIAL AS HABFIL (NOLOCK) ON HABFIL.IDHABILITACAOFILIAL = MAT.IDHABILITACAOFILIAL
JOIN SCURSO (NOLOCK) ON SCURSO.CODCURSO = HABFIL.CODCURSO
JOIN SALUNO (NOLOCK) ON SALUNO.RA = MAT.RA
JOIN PPESSOA AS P (NOLOCK) ON P.CODIGO = SALUNO.CODPESSOA
LEFT JOIN STURMADISC AS STD (NOLOCK) ON STD.IDHABILITACAOFILIAL = HABFIL.IDHABILITACAOFILIAL --AND STD.CODTURMA = MAT.CODTURMA 
JOIN SDISCIPLINA AS DISCI (NOLOCK) ON DISCI.CODDISC = STD.CODDISC 
 JOIN (SELECT CODCURSO,CODHABILITACAO,CODGRADE,DESCRICAO FROM SGRADE (NOLOCK) WHERE SGRADE.DESCRICAO LIKE '%CONDOR%' OR SGRADE.DESCRICAO LIKE '%DISPEN%') AS GRD ON  GRD.CODCURSO = HABFIL.CODCURSO AND GRD.CODGRADE = HABFIL.CODGRADE --AND GRD.CODHABILITACAO = HABFIL.CODHABILITACAO 
LEFT JOIN SHISTDISCPENDENTES AS PEND (NOLOCK) ON PEND.RA = MAT.RA AND PEND.CODDISC = STD.CODDISC AND PEND.IDHABILITACAOFILIAL = HABFIL.IDHABILITACAOFILIAL 
--LEFT JOIN SHISTDISCCONCLUIDAS AS CONC (NOLOCK) ON  CONC.RA = MAT.RA AND CONC.CODDISC = STD.CODDISC AND CONC.IDHABILITACAOFILIAL = HABFIL.IDHABILITACAOFILIAL AND CONC.NOTA IS NULL
 JOIN SPLETIVO AS PER (NOLOCK) ON PER.IDPERLET = STD.IDPERLET
 JOIN SHABILITACAOALUNO AS HBALUNO (NOLOCK) ON HBALUNO.IDHABILITACAOFILIAL = HABFIL.IDHABILITACAOFILIAL AND HBALUNO.RA = MAT.RA AND HBALUNO.DTCOLACAOGRAU IS NULL
 --JOIN SMATRICULA (NOLOCK) ON SMATRICULA.RA = MAT.RA AND SMATRICULA.IDHABILITACAOFILIAL = HABFIL.IDHABILITACAOFILIAL AND SMATRICULA.IDPERLET = MAT.IDPERLET AND SMATRICULA.IDTURMADISC = STD.IDTURMADISC
 --LEFT JOIN (SELECT CODSTATUS,DESCRICAO FROM SSTATUS (NOLOCK) /*WHERE DESCRICAO NOT IN ('CAC-CANCELADO','AP-APROVADO','DST-DESISTENTE')*/) AS ST_DISC ON SMATRICULA.CODSTATUS = ST_DISC.CODSTATUS 

WHERE  MAT.RA IN( SELECT DISTINCT RA FROM SMATRICPL (NOLOCK)JOIN SSTATUS(NOLOCK) ON SSTATUS.CODSTATUS= SMATRICPL.CODSTATUS WHERE CODTURMA LIKE '%CONDOR%' AND SSTATUS.DESCRICAO LIKE '%MAT%' OR SSTATUS.DESCRICAO LIKE '%TRANC%') 
AND MAT.RA NOT IN (SELECT DISTINCT SBA.RA FROM SHABILITACAOALUNO(NOLOCK) AS SBA  WHERE DTCOLACAOGRAU IS NOT NULL)																						 --AND MAT.RA= '00024557'
AND (MAT.CODTURMA LIKE '%CONDOR%' OR MAT.CODTURMA LIKE '%DISPEN%') 

 ORDER BY ALUNO,RA--,CODPERLET--,DISCIPLINA


 --  SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'STURMADISC'