SELECT A.RA,P.NOME,A.IDPERLET,A.CODCONTRATO,CODBOLSA,DTINICIO,DTFIM,S.CODSERVICO,S.NOME AS SERVICO,A.DESCONTO 
,M.CODTURMA
FROM SBOLSAALUNO AS A
JOIN SCONTRATO AS CONT ON CONT.RA = A.RA AND CONT.CODCONTRATO = A.CODCONTRATO AND CONT.IDPERLET = A.IDPERLET
JOIN SSERVICO AS S ON S.CODSERVICO = A.CODSERVICO AND NOME LIKE 'MENS%'
JOIN SMATRICPL AS M ON M.RA = CONT.RA AND M.IDHABILITACAOFILIAL = CONT.IDHABILITACAOFILIAL AND M.IDPERLET = CONT.IDPERLET
JOIN SALUNO AS AL ON AL.RA = M.RA
JOIN PPESSOA AS P ON P.CODIGO = AL.CODPESSOA

WHERE A.DESCONTO = 100 AND A.IDPERLET = 270 AND CONT.CODFILIAL = 6

ORDER BY NOME