SET DATEFORMAT DMY
set language Português


DECLARE @IDPERLET AS VARCHAR(6), @RA AS VARCHAR(20), @CODPESSOA AS INT

SET @RA = '00026157'--'00025972'--:RA1
SET @CODPESSOA = (SELECT CODIGO FROM PPESSOA  JOIN SALUNO ON SALUNO.CODPESSOA = PPESSOA.CODIGO WHERE SALUNO.RA = @RA)
SET @IDPERLET = (SELECT MAX(SMATRICPL.IDPERLET) 
                   FROM SMATRICPL (NOLOCK) 
                  WHERE RA = @RA)

SELECT PPESSOA.NOME AS NOME_ALUNO,
/*SPLETIVO.CODPERLET + '/' + SMATRICPL.CODTURMA AS ANO_SERIE,*/
       SALUNO.RA AS RA_DO_ALUNO,
       SCURSO.NOME AS NOME_CURSO, 
       SMATRICPL.CODTURMA  AS  ANO_SERIE,        
       CONVERT(VARCHAR,  PPESSOA.DTNASCIMENTO, 103)AS DTNASC_ALUNO,
       PPESSOA.NATURALIDADE AS NATUR_ALUNO,
       PPESSOA.SEXO AS SEXO_ALUNO,
       ISNULL(CASE (PPESSOA.CORRACA) 
			WHEN '0'  THEN 'INDÍGENA'
			WHEN '2'  THEN 'BRANCA'
			WHEN '4'  THEN 'NEGRA'
			WHEN '6'  THEN 'AMARELA'
			WHEN '8'  THEN 'PARDA'
			WHEN '10' THEN 'NÃO DECLARADA' 
       END,'') AS RACA_ALUNO,
	   /*CASE SALUNOCOMPL.RESPGUARDA WHEN '001' THEN 'X' ELSE ' ' END AS GUARDAPAI,
	   CASE SALUNOCOMPL.RESPGUARDA WHEN '002' THEN 'X' ELSE ' ' END AS GUARDAMAE,
	   CASE SALUNOCOMPL.RESPGUARDA WHEN '003' THEN 'X' ELSE ' ' END AS GUARDAAMBOS,
	   CASE SALUNOCOMPL.RESPGUARDA WHEN '004' THEN SALUNOCOMPL.OUTRORESP ELSE '          ' END AS GUARDAOUTROS,      
	   CASE SALUNOCOMPL.DOCRESP WHEN '01' THEN 'X' ELSE ' ' END AS DOCSIM,
	   CASE SALUNOCOMPL.DOCRESP WHEN '02' THEN 'X' ELSE ' ' END AS DOCNAO ,*/
	   isnull(FORMAT(SCONTRATO.DTASSINATURA,'D'), '_____________________________') DATAACEITE
       ,ISNULL((SELECT NACIONALIDADE FROM ZNACIONALIDADE WHERE ZNACIONALIDADE.CODNACIONALIDADE = PPESSOA.NACIONALIDADE),'') AS NACIONALIDADE
	   ,(PCODESTCIVIL.DESCRICAO) AS ESTADOCIVIL
	   ,ISNULL((SELECT DESCRICAO FROM EPROFISS WHERE EPROFISS.CODCLIENTE = PPESSOA.CODPROFISSAO),'Não informada') AS PROFISSAO
	   ,PPESSOA.RUA
	   ,PPESSOA.NUMERO
	   ,PPESSOA.BAIRRO
	   ,PPESSOA.CEP
	   ,PPESSOA.ESTADO
	   ,PPESSOA.CPF
	   ,PPESSOA.CARTIDENTIDADE
	   ,FORMAT(GETDATE(),'D') AS HOJE 

 FROM SCURSO (NOLOCK) 
INNER JOIN SHABILITACAOFILIAL
   ON SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
INNER JOIN SMATRICPL (NOLOCK) 
   ON SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
INNER JOIN SALUNO (NOLOCK) 
   ON SALUNO.RA = SMATRICPL.RA
INNER JOIN PPESSOA (NOLOCK) 
   ON PPESSOA.CODIGO = SALUNO.CODPESSOA
INNER JOIN SPLETIVO (NOLOCK) 
   ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
INNER JOIN SSTATUS (NOLOCK) 
   ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
/*INNER JOIN STURMA
    ON STURMA.CODTURMA = SMATRICPL.CODTURMA*/
   
   LEFT JOIN SALUNOCOMPL
   ON SALUNOCOMPL.RA = SALUNO.RA   
   
   INNER JOIN SCONTRATO ON SCONTRATO.RA = SALUNO.RA
AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
AND SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
AND SCONTRATO.STATUS <> 'S'
AND SCONTRATO.TIPOCONTRATO <> 'A'

   JOIN (SELECT TOP 1 * FROM SPESSOA WHERE CODPESSOAMAE = @CODPESSOA OR CODPESSOAPAI = @CODPESSOA) SP ON (SP.CODPESSOAMAE = PPESSOA.CODIGO OR SP.CODPESSOAPAI = PPESSOA.CODIGO)
   JOIN PCODESTCIVIL ON PCODESTCIVIL.CODCLIENTE = PPESSOA.ESTADOCIVIL

WHERE SALUNO.RA = @RA
AND  SPLETIVO.CODPERLET = '2019'
AND SSTATUS.CODSTATUS IN (1,2)
AND (SCURSO.NOME LIKE '%SCHOOL%')



--SELECT * FROM SPESSOA WHERE CODPESSOAMAE = 92565 --CODIGO = 92565

--SELECT * FROM PPESSOA WHERE CODUSUARIO = '00025972'


--SELECT * FROM PPESSOA WHERE CODIGO = 92564

--SELECT * FROM GLINKSREL WHERE MASTERFIELD LIKE '%ESTADOCIVIL%'


--SELECT* FROM PCODESTCIVIL

--SELECT * FROM SALUNO WHERE CODPESSOA=85129