SELECT DISTINCT *
, CAST(CONT AS NVARCHAR) + 'X '+ 'R$ '+ REPLACE(CAST( (ANUIDADEVL/CONT) AS NVARCHAR) ,'.',',')  AS PARC_ANUIDADE 

,    CASE WHEN CODTURMA LIKE '%EM%' THEN 'ENSINO MÉDIO' 
	 ELSE
	 REPLACE(SUBSTRING(DESC_PLANO,1, ISNULL(CHARINDEX('-',DESC_PLANO),CHARINDEX('/' ,DESC_PLANO)-1)),'-','') 
	 END AS SEGMENTO

,	CASE WHEN CODTURMA LIKE '%EM3%' THEN '3ª SERIE'
	ELSE
	ISNULL(SUBSTRING(DESC_PLANO, ISNULL(CHARINDEX('-' ,DESC_PLANO)+1,CHARINDEX('/' ,DESC_PLANO)+1),  CHARINDEX(',',DESC_PLANO) - CHARINDEX('-',DESC_PLANO)-1),'ERRO')  
	END AS SERIE_ANO

	,'R$ ' + REPLACE(CONVERT(NVARCHAR, ANUIDADEVL),'.',',') AS ANUIDADE

 FROM (
	SELECT 
	MAT.* 
	,PLANPGTO.DESCRICAO AS DESC_PLANO
	,MAX(PARCP.PARCELA) AS CONT
	,CONVERT(SMALLMONEY,SUM(PARCP.VALOR)) AS ANUIDADEVL
	

	FROM MAT (NOLOCK)

	 JOIN SPLANOPGTO (NOLOCK) AS PLANPGTO ON PLANPGTO.CODPLANOPGTO = MAT.CODPLANOPGTO AND PLANPGTO.CODTIPOCURSO = MAT.CODTIPOCURSO
	LEFT JOIN SPARCPLANO (NOLOCK) AS PARCP ON PARCP.IDPERLET = PLANPGTO.IDPERLET AND PARCP.CODPLANOPGTO = PLANPGTO.CODPLANOPGTO AND PARCP.CODSERVICO = MAT.CODSERVICO

	WHERE MAT.RA IN ('00026222','00026223','00026331','00020913','00019774','00004940','00016523','00006768','00003378','00019991','00025395','00025888') AND CODPERLET = '2019' AND MAT.ST_CONTRATO = 'N' AND MAT.TIPOCONTRATO = 'P' AND SERVICO LIKE '%MENSALIDADE%'

	GROUP BY 
 MAT.CODFILIAL,MAT.CODTURMA,MAT.DTMATRICULA,MAT.IDHABILITACAOFILIAL,MAT.IDPERLET,MAT.CODPERLET,MAT.CODTIPOCURSO,MAT.CODTURNO,MAT.TURNO_NOME,MAT.TURNO,MAT.CODCURSO,MAT.CURSO
 ,MAT.RA,MAT.ALUNO,MAT.CODSTATUS,MAT.STATUS,MAT.COD_RESP_FIN,MAT.NOME_RESP_FIN,MAT.COD_RESP_ACA,MAT.NOME_RESP_ACAD,MAT.CNPJ_RES_FIN,MAT.CODCONTRATO,MAT.CODPLANOPGTO,MAT.CODBOLSA
,MAT.BOLSA,MAT.CODSERVICO,MAT.SERVICO,PLANPGTO.DESCRICAO,MAT.CODCCUSTO,MAT.ST_CONTRATO,MAT.DTCANC_CONTRATO,MAT.TIPOCONTRATO,MAT.TIPOPARCELA
)TABA