DECLARE @PARCELAS INT, @CODCONTRATO INT, @RA VARCHAR(10)
SET @CODCONTRATO = 187394 /*:CONTRATO1*/ ; SET @RA ='00016101' /*:RA2*/;
SET @PARCELAS =(SELECT MAX(SPARCPLANO.PARCELA)
				FROM SCONTRATO
				JOIN SPARCPLANO ON SPARCPLANO.CODPLANOPGTO = SCONTRATO.CODPLANOPGTO
				WHERE SCONTRATO.CODCONTRATO = @CODCONTRATO)

SELECT 

CASE WHEN CC.SEMESTRALIDADE IS NULL 
     THEN CAST(REPLACE(DD.SEMESTRALIDADE,',','.') AS NUMERIC(15,2))
     ELSE CAST(REPLACE(CC.SEMESTRALIDADE,',','.' )AS NUMERIC(15,2))
END SEMESTRALIDADE
, CASE WHEN CC.VLPARCELA IS NULL THEN convert(decimal(18,2),CAST(DD.VLPARCELA AS MONEY)) ELSE convert(decimal(18,2),CAST(CC.VLPARCELA AS MONEY)) END VALOR_PARCELA
, @PARCELAS PARCELAS
, CASE WHEN @PARCELAS = '6' THEN CAST( ', o qual poderá ser dividido em até 6 (seis) parcelas consecutivas e mensais' AS VARCHAR(1500)) 
	   WHEN @PARCELAS = '5' THEN CAST( ', o qual poderá ser dividido em até 5 (cinco) parcelas consecutivas e mensais' AS VARCHAR(1500)) 
	   /*WHEN @PARCELAS = '4' THEN CAST( ', o qual poderá ser dividido em até 4 (quatro) parcelas consecutivas e mensais.' AS VARCHAR(1500))*/
END TEXTO

FROM(
SELECT     --   4X80            4 X 10,39
SUM(BB.NUMCREDITOS * SFAIXACRED.VALCRED) SEMESTRALIDADE, SUM((BB.NUMCREDITOS * SFAIXACRED.VALCRED)/@PARCELAS) VLPARCELA
,BB.IDPERLET,BB.CODSTATUS
 FROM (
SELECT SUM(AA.NUMCREDITOSCOB) NUMCREDITOS, AA.IDHABILITACAOFILIAL, AA.IDPERLET,AA.CODSTATUS
FROM (
	SELECT DISTINCT @RA RA,STURMADISC.CODTURMA, STURMADISC.IDTURMADISC,
	SMATRICULA.NUMCREDITOSCOB, SHABILITACAOALUNO.IDHABILITACAOFILIAL, SMATRICULA.IDPERLET,SMATRICULA.CODSTATUS
	FROM SMATRICULA
	JOIN SHABILITACAOALUNO
	  ON SHABILITACAOALUNO.RA = SMATRICULA.RA AND SHABILITACAOALUNO.CODSTATUS IN(40,41,/**ead grad**/176,177,/**ead pos**/196,195) AND SMATRICULA.IDPERLET = 267 ----- ADD
	JOIN SHABILITACAOFILIAL
	  ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
	 AND SHABILITACAOFILIAL.CODFILIAL = 18
	 JOIN SCONTRATO ON (SCONTRATO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL)/*DENNYSON*/
	JOIN SPLETIVO
	  ON SPLETIVO.IDPERLET = SMATRICULA.IDPERLET AND SPLETIVO.IDPERLET = 267
	JOIN STURMADISC
	  ON STURMADISC.CODFILIAL = 18
	 AND STURMADISC.IDPERLET = SMATRICULA.IDPERLET
	 AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC

	JOIN SDISCGRADE
	  ON SDISCGRADE.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	 AND SDISCGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
	 AND SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
	 AND SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
	/*AND SDISCGRADE.CODDISC = STURMADISC.CODDISC*/
	JOIN SMATRICPL ON SMATRICPL.RA = SMATRICULA.RA
	AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
	AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
		/*AND STURMADISC.CODTURMA = SMATRICPL.CODTURMA*/
	JOIN SSTATUS ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS AND SSTATUS.DESCRICAO LIKE '%MAT%'

	WHERE SMATRICULA.RA = @RA
	AND  SCONTRATO.CODCONTRATO = @CODCONTRATO /*DENNYSON*/
	/*AND SHABILITACAOFILIAL.CODCURSO = :CODIGOCURSO1*/
	/*AND STURMADISC.CODTURMA = SMATRICPL.CODTURMA 
	-- Retirado AND STURMADISC.CODTURMA = SMATRICPL.CODTURMA
	por GislaneFerreira em 05/03/19.
	Retornando valor dos contratos em branco. Exemplo: RA 00016101 */
	/* INSERIDO POR HELEN 22/10/18 */
	
	AND SCONTRATO.IDPERLET = 267
	AND (SSTATUS.DESCRICAO LIKE '%MAT%' OR SSTATUS.DESCRICAO LIKE 'PRE%')
	
	
)AA
GROUP BY AA.IDHABILITACAOFILIAL, AA.IDPERLET,AA.CODSTATUS

)BB 

JOIN SFAIXACRED
	  ON SFAIXACRED.IDHABILITACAOFILIAL = BB.IDHABILITACAOFILIAL
	 AND SFAIXACRED.IDPERLET = BB.IDPERLET

	 GROUP BY BB.IDPERLET,BB.CODSTATUS
)CC

LEFT JOIN( SELECT  MAX(SCONTRATO.RA) RA, SUM(SPARCPLANO.VALOR) SEMESTRALIDADE, MAX(SPARCPLANO.VALOR) VLPARCELA
	FROM SCONTRATO
	JOIN SPARCPLANO ON SCONTRATO.CODCONTRATO = @CODCONTRATO AND SPARCPLANO.CODPLANOPGTO = SCONTRATO.CODPLANOPGTO
	WHERE SCONTRATO.CODCONTRATO = @CODCONTRATO
	)DD
ON DD.RA = @RA


 WHERE IDPERLET = 267 AND CODSTATUS IN (40,41)

-- SELECT * FROM SCONTRATO WHERE CODCONTRATO = 187394

--SELECT * FROM SHABILITACAOFILIAL


--SELECT * FROM SMATRICULA WHERE RA='00016101' AND IDPERLET = 267 AND CODSTATUS = 40


--SELECT * FROM STURMADISC WHERE IDTURMADISC =60066  CODTURMA = 'GC5.4AN' --

--SELECT * FROM SPLETIVO WHERE IDPERLET =267 -- 2019/1 FIL 18