--select * from smatricpl WHERE RA='00025972'

--SELECT * FROM SPLETIVO WHERE IDPERLET=265

SET DATEFORMAT DMY

DECLARE @IDPERLET AS VARCHAR(6), @RA AS VARCHAR(20)

SET @RA = '00025972' --:RA1
SET @IDPERLET = (SELECT MAX(SMATRICPL.IDPERLET) 
                   FROM SMATRICPL (NOLOCK) 
                  WHERE RA = @RA)

SELECT PPESSOA.NOME AS NOME_ALUNO, 
       SALUNO.RA AS RA_DO_ALUNO,
       SCURSO.NOME AS NOME_CURSO, 
       CASE WHEN SUBSTRING(SMATRICPL.CODTURMA,1,1) = 'N' THEN SUBSTRING(SMATRICPL.CODTURMA,1,2)+'/EI' 
            WHEN SUBSTRING(SMATRICPL.CODTURMA,1,2) = 'EF' THEN SUBSTRING(SMATRICPL.CODTURMA,3,1)+'/EF'
            WHEN SUBSTRING(SMATRICPL.CODTURMA,1,2) = 'EM' THEN SUBSTRING(SMATRICPL.CODTURMA,3,1)+'/EM'END ANO_SERIE,
       CONVERT(VARCHAR,  PPESSOA.DTNASCIMENTO, 103)AS DTNASC_ALUNO,
       PPESSOA.NATURALIDADE AS NATUR_ALUNO,
       PPESSOA.SEXO AS SEXO_ALUNO,
       CASE (PPESSOA.CORRACA) 
			WHEN '0'  THEN 'INDÍGENA'
			WHEN '2'  THEN 'BRANCA'
			WHEN '4'  THEN 'NEGRA'
			WHEN '6'  THEN 'AMARELA'
			WHEN '8'  THEN 'PARDA'
			WHEN '10' THEN 'NÃO DECLARADA' 
       END AS RACA_ALUNO,
	   (CASE FUNCIONARIO WHEN 0 THEN 'NÃO' WHEN 1 THEN 'SIM'	END) AS FUNCIONARIO,
	   (CASE FUNCIONARIO WHEN 0 THEN CONVERT(SMALLMONEY,205) WHEN 1 THEN CONVERT(SMALLMONEY,185) END) AS MENSALIDADE,			 
       (CASE FUNCIONARIO WHEN 0 THEN CONVERT(SMALLMONEY,205*8) WHEN 1 THEN CONVERT(SMALLMONEY,185*8) END) AS ANUIDADE

 FROM SCURSO (NOLOCK) 
INNER JOIN SHABILITACAOFILIAL
   ON SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
INNER JOIN SMATRICPL (NOLOCK) 
   ON SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
INNER JOIN SALUNO (NOLOCK) 
   ON SALUNO.RA = SMATRICPL.RA
INNER JOIN PPESSOA (NOLOCK) 
   ON PPESSOA.CODIGO = SALUNO.CODPESSOA
INNER JOIN SPLETIVO (NOLOCK) 
   ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
INNER JOIN SSTATUS (NOLOCK) 
   ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
   
WHERE SALUNO.RA = @RA 
AND SPLETIVO.CODPERLET = '2019'
AND SSTATUS.CODSTATUS IN (1,2)
AND SCURSO.NOME LIKE '%SCHOOL%'
/*OR (SCURSO.NOME LIKE 'ENSINO%'
OR SCURSO.NOME LIKE 'CURSO PR%'
   /*OR SCURSO.NOME LIKE 'NIVEL%'
   OR SCURSO.NOME LIKE 'BER%'*/
   OR SCURSO.NOME LIKE 'FOR%')
  */


 -- SELECT FUNCIONARIO,NOME,CODIGO FROM PPESSOA WHERE CODIGO IN (92565,94883)
  

  --SELECT * FROM GCAMPOS WHERE TABELA = 'PPESSOA'