/*DECLARE @DDD AS NVARCHAR(6)
SET @DDD = :RA_ALUNO */

SELECT

CASE WHEN SDISCIPLINA.NOME LIKE '%LÍNGUA PORTUGUESA E LITERATURA%' 
     THEN 'LÍNGUA PORT. E LITERATURA'   
     ELSE SDISCIPLINA.NOME 
END AS NOME_DISCIPLINA,

SDISCGRADE.CH AS HORAS_AULA,

ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 10 
                 THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0' 
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE(
								case when SNOTAETAPA.NOTAFALTA < 10 then
									CAST (0 AS VARCHAR) + ','
									+ CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR)
								else
									CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
									+ CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR)
									end
								)
                      END)
					  
                ELSE NULL 
            END),'-') NOTAS_1,

ISNULL(CASE WHEN (STURMADISC.CODTURMA LIKE 'EM%')
            THEN ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 15 
                                                      THEN SNOTAETAPA.NOTAFALTA 
                                                 END) AS NUMERIC(5))), '-')
            ELSE CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 15
                                               THEN SNOTAETAPA.NOTAFALTA 
                                          END)AS NUMERIC(5)))
       END,'-') FALTAS_1,

ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 15 
				                     THEN SNOTAETAPA.AULASDADAS 
				 					 ELSE NULL 
                                END)AS VARCHAR(5))),'-')  AULAS_DADAS_1,

ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 11 
                 THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0' 
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE(
								case when SNOTAETAPA.NOTAFALTA < 10 then
									CAST (0 AS VARCHAR) + ','
									+ CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR)
								else
									CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
									+ CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR)
									end
								)
                      END)
					  
                ELSE NULL 
            END),'-') NOTAS_2,


ISNULL(CASE WHEN(STURMADISC.CODTURMA LIKE 'EM.%')
            THEN ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 25 
                                                      THEN SNOTAETAPA.NOTAFALTA 
                                                 END) AS NUMERIC(5))), '-')
            ELSE CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 25 
                                               THEN SNOTAETAPA.NOTAFALTA 
                                          END)AS NUMERIC(5)))
        END,'-') FALTAS_2,

ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 25 
                                     THEN SNOTAETAPA.AULASDADAS 
                                     ELSE NULL 
                                END)AS VARCHAR(5))),'-') AULAS_DADAS_2,
           
ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 12
                 THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0' 
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE(
								case when SNOTAETAPA.NOTAFALTA < 10 then
									CAST (0 AS VARCHAR) + ','
									+ CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR)
								else
									CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
									+ CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR)
									end
								)
                      END)
					  
                ELSE NULL 
            END),'-') NOTAS_3,


ISNULL(CASE WHEN (STURMADISC.CODTURMA LIKE 'EM.%')
            THEN ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 35 
                                                      THEN SNOTAETAPA.NOTAFALTA 
                                                 END) AS NUMERIC(5))), '-')
            ELSE CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 35 
                                               THEN SNOTAETAPA.NOTAFALTA 
                                          END)AS NUMERIC(5)))
       END,'-') FALTAS_3,

ISNULL(CONVERT(VARCHAR,CAST(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 35 
                                     THEN SNOTAETAPA.AULASDADAS 
                                     ELSE NULL
                                END)AS VARCHAR(5))),'-') AULAS_DADAS_3,


ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 50
                THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0' 
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE (CAST(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
                                 + CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR))
                      END) 
                ELSE NULL 
            END),'-') MEDIA_ANUAL,

ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 51 
                THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0' 
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE (CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
                                 + CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR))
                       END) 
                ELSE NULL 
            END),'-') RECUP_FINAL,

ISNULL(MAX(CASE WHEN SNOTAETAPA.CODETAPA = 54 
                THEN (CASE WHEN SNOTAETAPA.NOTAFALTA = '100.0000' 
                           THEN '10,0'
                           WHEN SNOTAETAPA.NOTAFALTA = '0.0000' 
                           THEN '0,0' 
                           ELSE (CAST (SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,3) AS VARCHAR) + ','
                                 + CAST(SUBSTRING(SUBSTRING (CAST(SNOTAETAPA.NOTAFALTA AS VARCHAR), -1,4),2,1) AS VARCHAR))
                      END) 
                ELSE NULL 
           END),'-') MEDIA_FINAL,
 SMATRICULA.RA
 --,SDISCGRADE.POSHIST

FROM STURMADISC (NOLOCK)
JOIN SDISCIPLINA (NOLOCK)
  ON SDISCIPLINA.CODCOLIGADA = STURMADISC.CODCOLIGADA
 AND SDISCIPLINA.CODDISC = STURMADISC.CODDISC
JOIN SMATRICULA (NOLOCK)
  ON SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
 AND SMATRICULA.IDPERLET = STURMADISC.IDPERLET
 AND SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC 
JOIN SPLETIVO (NOLOCK)
  ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
 AND SPLETIVO.CODFILIAL = STURMADISC.CODFILIAL
 AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
LEFT JOIN SNOTAETAPA (NOLOCK)
  ON SNOTAETAPA.CODCOLIGADA = SMATRICULA.CODCOLIGADA
 AND SNOTAETAPA.IDTURMADISC = SMATRICULA.IDTURMADISC 
 AND SNOTAETAPA.RA = SMATRICULA.RA
JOIN SSTATUS (NOLOCK)
  ON SSTATUS.CODCOLIGADA = SMATRICULA.CODCOLIGADA
 AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
JOIN SHABILITACAOALUNO (NOLOCK)
  ON SHABILITACAOALUNO.RA = SMATRICULA.RA
 AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
JOIN SHABILITACAOFILIAL (NOLOCK)
  ON SHABILITACAOFILIAL.CODFILIAL = STURMADISC.CODFILIAL
 AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL
JOIN SHABILITACAO (NOLOCK)
  ON SHABILITACAO.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
 AND SHABILITACAO.CODCURSO = SHABILITACAO.CODCURSO
JOIN SDISCGRADE (NOLOCK)
  ON SDISCGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE
 AND SDISCGRADE.CODDISC = STURMADISC.CODDISC
 AND SDISCGRADE.CODCURSO = SHABILITACAO.CODCURSO
 AND SDISCGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
 
WHERE SPLETIVO.CODPERLET = '2019' --:PER_LETIVO
  AND SMATRICULA.RA = '00025626' --'00026377' --:RA_ALUNO
  AND SDISCGRADE.POSHIST < 20
  AND SMATRICULA.CODSTATUS NOT IN (159,23,119,18,212)
 /* AND SDISCIPLINA.NOME NOT LIKE 'FORMAÇÃO HUMANA%'*/
  AND SHABILITACAOFILIAL.CODFILIAL = 21
 
GROUP BY SDISCIPLINA.NOME, SDISCGRADE.POSHIST, SSTATUS.DESCRICAO, SDISCGRADE.CH, SHABILITACAOFILIAL.CODCURSO, SHABILITACAO.CODHABILITACAO, SHABILITACAOFILIAL.CODGRADE, SDISCIPLINA.CODDISC, SMATRICULA.RA,STURMADISC.CODTURMA--,SNOTAETAPA.CODETAPA,SNOTAETAPA.NOTAFALTA
ORDER BY SDISCGRADE.POSHIST