--SELECT * FROM INTEGRACOES_CLIPESCOLA WHERE CODALUNO = '00010221'



	 SELECT  SUM(PF.VALOR) AS VALOR FROM PFFINANC AS PF

	 JOIN ( SELECT CHAPA,MAX(DTPAGTO) DTPGTO,ANOCOMP,MESCOMP FROM PFFINANC WHERE CHAPA = 180117 AND DTPAGTO = (SELECT MAX(DTPAGTO) FROM PFFINANC AS A WHERE A.CHAPA = PFFINANC.CHAPA) GROUP BY CHAPA,ANOCOMP,MESCOMP 
	  
	 )TAB ON TAB.CHAPA = PF.CHAPA AND TAB.ANOCOMP = PF.ANOCOMP AND TAB.MESCOMP = PF.MESCOMP



	  WHERE PF.CHAPA = 180117 AND PF.CODEVENTO IN('0167','0168','0240') AND PF.NROPERIODO = 2
	  


	  --GROUP BY PF.ANOCOMP,PF.MESCOMP,CODEVENTO,PF.VALOR



	  --SELECT * FROM PFFINANC WHERE CHAPA = 180117 AND CODEVENTO IN('0167','0168','0240') AND ANOCOMP = 2020 AND MESCOMP = 3


	SELECT * FROM PPESSOA


	
	
	
