DECLARE @TXT AS VARCHAR(500), @CODPERLET AS VARCHAR(10)

SET @TXT = ''
SET @CODPERLET = ''

DECLARE CURSOR1  CURSOR FOR

	SELECT 
	
	 SP.CODPERLET
  
	 FROM SLOGPLETIVO AS L
	JOIN SSTATUS AS S ON L.CODSTATUS = S.CODSTATUS AND CODTIPOCURSO = 4
	JOIN SPLETIVO AS SP ON SP.IDPERLET = L.IDPERLET


	WHERE RA IN ('00019575','00011137') AND S.DESCRICAO LIKE '%TRANC%'

	ORDER BY CODPERLET

	OPEN CURSOR1

	FETCH NEXT FROM CURSOR1 INTO @CODPERLET

	WHILE @@FETCH_STATUS = 0
	 BEGIN

	 SET @TXT = @TXT + CASE WHEN @CODPERLET IS NULL THEN '' ELSE ', '+ @CODPERLET  END

	FETCH NEXT FROM CURSOR1 INTO @CODPERLET

	END
	

	CLOSE CURSOR1

	DEALLOCATE CURSOR1

	SELECT SUBSTRING(@TXT,2,LEN(@TXT)) AS TRANS