SET LANGUAGE PORTUGUÍS
;WITH

TABA AS (
SELECT DISTINCT
FCFO.NOME NOMECFO,
FCFO.CGCCFO,
FLAN.IDLAN,
FLAN.STATUSLAN,
FLAN.DATABAIXA,
FLAN.DATAVENCIMENTO,
CONVERT(MONEY,FLAN.VALORBAIXADO) VALOR_BAIXADO,
--SPLETIVO.CODPERLET PLETIVO,
PPESSOA.NOME,
CASE PPESSOA.SEXO WHEN 'M' THEN 'matriculado' WHEN 'F' THEN 'matriculada' ELSE 'matriculado(a)' end SEXO


FROM FCFO (NOLOCK)
  JOIN FLAN (NOLOCK) ON FLAN.CODCFO = FCFO.CODCFO
  LEFT JOIN SALUNO (NOLOCK) ON SALUNO.CODCFO = FCFO.CODCFO --'007431'--:RA
INNER JOIN SMATRICPL (NOLOCK) ON SMATRICPL.RA = SALUNO.RA
LEFT JOIN SPLETIVO (NOLOCK) ON SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
INNER JOIN PPESSOA (NOLOCK) ON SALUNO.CODPESSOA = PPESSOA.CODIGO
JOIN SPARCELA ON SPARCELA.RA = SALUNO.RA
JOIN SSERVICO ON SSERVICO.CODSERVICO = SPARCELA.CODSERVICO

WHERE  STATUSLAN IN (1,4) AND /*FORMAT(FLAN.DATABAIXA,'yyyy')*/ SPLETIVO.CODPERLET = '2018' AND SALUNO.RA = '007431'
AND CONVERT(VARCHAR,FLAN.DATABAIXA,103) BETWEEN '01/01/2018' AND '31/12/2018' --:DATA_INICIAL AND :DATA_FINAL
 --(FCFO.CODCFO = 004031 OR FCFO.NOME LIKE '%AMAURI JOS… DA SILVA%')

 ),
  
  TABB AS (
  SELECT FCFO.NOMEFANTASIA, FCFO.CGCCFO, FLAN.IDLAN, FLAN.STATUSLAN, FLAN.DATABAIXA, FLAN.DATAVENCIMENTO, CONVERT(SMALLMONEY,FLAN.VALORBAIXADO) AS VALOR_BAIXADO,
 PPESSOA.NOME
 ,CASE PPESSOA.SEXO WHEN 'M' THEN 'matriculado' WHEN 'F' THEN 'matriculada' ELSE 'matriculado' end SEXO

  FROM FLAN (NOLOCK)
 JOIN FCFO (NOLOCK) ON FLAN.CODCFO = FLAN.CODCFO 
 JOIN FLANCOMPL (NOLOCK) ON FLAN.IDLAN = FLANCOMPL.IDLAN
 LEFT JOIN SALUNO (NOLOCK) ON SALUNO.RA = FLANCOMPL.RA
 LEFT JOIN PPESSOA (NOLOCK) ON SALUNO.CODPESSOA = PPESSOA.CODIGO
  
 WHERE 
 FLAN.CODFILIAL = /*:CODFILIAL_S*/ 6 AND
 FLANCOMPL.RA = '007431' AND
 FORMAT(FLAN.DATABAIXA,'yyyy') LIKE '2018'
 AND STATUSLAN IN (1,4) AND
 FLAN.CODAPLICACAO = 'F' AND
 (FCFO.CODCFO = 004031 OR FCFO.NOME LIKE '%AMAURI JOS… DA SILVA%')
 
 )

  SELECT * FROM TABA 
   UNION ALL
  SELECT * FROM TABB 


/*  -- 
SELECT SUM(TABC.VALOR_BAIXADO) AS VALOR_BX,dbo.fn_numero_por_extenso(SUM(TABC.VALOR_BAIXADO)) AS VALOR_BX_ext,TABC.CGCCFO,'2018'/*:CODPERLET*/ AS PLETIVO,SEXO FROM (
 SELECT * FROM TABA 
 UNION ALL
 SELECT * FROM TABB 
 ) TABC
 GROUP BY CGCCFO,SEXO
 */

--***********************************************************************************************************************************************************************************

--SELECT * FROM FLAN WHERE CODCFO = 004031

--SELECT * FROM SALUNO WHERE CODCFO = 004031

--SELECT * FROM FCFO WHERE CODCFO = 004031

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'FCFO'

--SELECT * FROM FLANCOMPL WHERE IDLAN = 1432165
