BEGIN TRAN
; WITH

  TABA AS
  (
	SELECT DISTINCT M.CODFILIAL
	,M.RA
	,M.CODSTATUS 
	,ST.DESCRICAO AS STATUS
	,M.CODTURMA
	,M.IDHABILITACAOFILIAL
	,M.IDPERLET
	,PL.CODPERLET
	,C.CODCONTRATO
	,PA.IDPARCELA
	,PA.PARCELA
	,R.CODCFO
	,MA.IDTURMADISC
	

	FROM SMATRICPL AS M

	JOIN SPLETIVO AS PL ON PL.IDPERLET = M.IDPERLET
	JOIN SSTATUS AS ST ON ST.CODSTATUS = M.CODSTATUS
	LEFT JOIN SCONTRATO AS C ON C.CODFILIAL = M.CODFILIAL AND C.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL AND C.IDPERLET = M.IDPERLET AND C.RA = M.RA
	LEFT JOIN SMATRICULA AS MA ON MA.RA = M.RA AND MA.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL AND MA.IDPERLET = MA.IDPERLET
	LEFT JOIN SMATRICULACOMPL MC ON MC.IDTURMADISC = MA.IDTURMADISC AND MC.RA = MA.RA
	LEFT JOIN SPARCELA AS PA ON PA.CODCONTRATO = C.CODCONTRATO AND PA.RA = C.RA AND PA.IDPERLET = C.IDPERLET
	LEFT JOIN SRESPONSAVEL AS R ON R.IDPARCELA = PA.IDPARCELA

	WHERE M.CODFILIAL = '5' AND ST.DESCRICAO LIKE 'AGUARDANDO%' AND CODPERLET = '2021'
	)

	--SELECT * FROM TABA

	--****************  EXCLUIR NESSA ORDEM 1 EXECUÇÃO DE CADA VEZ  ****************--

	----  1º
	--DELETE FROM SRESPONSAVEL WHERE SRESPONSAVEL.IDPARCELA IN (SELECT DISTINCT IDPARCELA FROM TABA)

	----  2º
    --DELETE FROM SPARCELA FROM SPARCELA WHERE SPARCELA.IDPARCELA IN (SELECT DISTINCT IDPARCELA FROM TABA)
	
	----  3º
	--DELETE SMATRICPLCOMPL FROM SMATRICPLCOMPL 
	--JOIN TABA ON TABA.IDHABILITACAOFILIAL = SMATRICPLCOMPL.IDHABILITACAOFILIAL AND TABA.RA = SMATRICPLCOMPL.RA
	--WHERE  SMATRICPLCOMPL.IDHABILITACAOFILIAL = TABA.IDHABILITACAOFILIAL AND SMATRICPLCOMPL.RA = TABA.RA AND TABA.IDPERLET = SMATRICPLCOMPL.IDPERLET

	----  4º
	--DELETE SMATRICULACOMPL FROM SMATRICULACOMPL
	--JOIN TABA ON TABA.IDTURMADISC = SMATRICULACOMPL.IDTURMADISC AND TABA.RA = SMATRICULACOMPL.RA

	--  5º
	--DELETE SMATRICULA  FROM SMATRICULA 
	--JOIN TABA ON TABA.IDHABILITACAOFILIAL = SMATRICULA.IDHABILITACAOFILIAL AND SMATRICULA.RA = TABA.RA AND SMATRICULA.IDPERLET = TABA.IDPERLET

	----  6º
	--DELETE SCONTRATO FROM SCONTRATO
	--JOIN TABA ON TABA.CODCONTRATO = SCONTRATO.CODCONTRATO


	   ---- *** EXCLUIR EM MATRICULAS FILTRO STATUS AGUARDANDO SELECIONAR TODOS E EXCLUIR, CÓDGIO ABAIXO DEU ERRO 
	 --DELETE SMATRICPL FROM SMATRICPL
	 --JOIN TABA ON TABA.CODFILIAL = SMATRICPL.CODFILIAL AND TABA.RA = SMATRICPL.RA AND TABA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL AND TABA.CODTURMA = SMATRICPL.CODTURMA
	
	  
	----COMMIT

	----ROLLBACK