SET LANGUAGE PORTUGUÊS

SELECT * FROM (
SELECT A.IDLAN 
,RIGHT(D.CODTURMA,4) TURMA
,D.CODTURMA
,D.RA
,A.HISTORICO
,A.DATACRIACAO
,A.STATUSLAN

 FROM FLAN A
LEFT JOIN SLAN B ON B.IDLAN = A.IDLAN
LEFT JOIN SPARCELA C ON C.IDPARCELA = B.IDPARCELA
LEFT JOIN SMATRICPL D ON D.RA = C.RA AND D.IDPERLET = C.IDPERLET
 
WHERE A.PERLETIVO = 'posstxead'  --AND  STATUSLAN <> 2
)AA

WHERE TURMA <= /*:ANO_ANTERIOR*/'2018' AND DATACRIACAO BETWEEN /*:DTINI*/'01/01/2019' AND '27/02/2019'/*:DTFIM*/
ORDER BY TURMA,RA,IDLAN

--SELECT * FROM SMATRICPL WHERE RA= '00000523' --CODTURMA = 'EDESPS.2019.1'

--SELECT * FROM SPLETIVO WHERE IDPERLET = 277