SELECT * FROM SMATRICPL WHERE IDPERLET = 263 --CODTIPOMAT 23

SELECT * FROM STIPOMATRICULA WHERE CODTIPOMAT = 23 --CODTIPOCURSO = 11

SELECT * FROM SCURSO WHERE CODTIPOCURSO = 11

--SELECT * FROM SPLETIVO WHERE CODPERLET LIKE '%P%' CODPERLET = posstxead


SELECT * FROM SSTATUS WHERE CODTIPOCURSO = 11 --EAD CODSTATUS = 196 PRÉ-MATRICULADO, 195 MATRICULADO

SELECT * FROM SSERVICO WHERE CODTIPOCURSO = 11 -- CODSERVICO = 258


--SELECT * FROM SSERVICO WHERE CODSERVICO IN (1, 100, 101, 102, 103, 104, 158, 163, 264)