SELECT NOME,
'ENDEREÇO: RUA ' +ISNULL(RUA,'')+' Nº'+ ISNULL(NUMERO,'') + ISNULL(CASE WHEN COMPLEMENTO IS NULL THEN '' ELSE 'COMPLEMENTO ' END,0) +ISNULL(COMPLEMENTO,0) +' BAIRRO ' +BAIRRO +' CIDADE ' +CIDADE +' ESTADO ' +ESTADO + ' CEP ' +CEP AS ENDERECO
,'CARTEIRA DE TRABALHO Nº '+CARTEIRATRAB + ' SÉRIE ' + SERIECARTTRAB + ' UF -'+ UFCARTTRAB AS CARTEIRA_TRABALHO
 FROM PPESSOA WHERE CODUSUARIO = '210001' 