/*EQUIVALENTES CONCLUÍDAS - GRADE****************************************************************************************************************************/
--     ESSA


;WITH TAB1 AS
(


SELECT       ROW_NUMBER() OVER(PARTITION BY SEQUIVALENCIADISCGRADE.CODDISC ORDER BY NOTA DESC) AS IND
			,SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			,SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVCONCLUIDAS.RA
			,SHISTDISCEQUIVCONCLUIDAS.PLETIVO
			,SHISTDISCEQUIVCONCLUIDAS.CODDISC AS CODDIS_EQUIVALENTE
			,SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA AS DISC_EQUIVALENTE
			,SEQUIVALENCIADISCGRADE.CODDISC AS CODDISC_GRADE
			,dbo.SDISCIPLINA.NOME AS DISC_GRADE
			,SHISTDISCEQUIVCONCLUIDAS.STATUS
			,SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS
			,SHISTDISCEQUIVCONCLUIDAS.NOTA
			,SHISTDISCEQUIVCONCLUIDAS.CH			
			,SEQUIVALENCIADISCGRADE.CODPERIODO AS CODPERIODO
			,SHISTDISCEQUIVCONCLUIDAS.FALTAS
			,'Equivalentes Concluídas' AS TIPOHISTORICO
			,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
			,AULAS.TOT_AULAS
	FROM 
		SHISTDISCEQUIVCONCLUIDAS (NOLOCK)/*47 Rows*/

		
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.GREQUIV  = SDISCGRUPOEQ.IDGRUPO

	 LEFT JOIN /**/
		dbo.SEQUIVALENCIADISCGRADE (NOLOCK)
			ON 
				
					SDISCGRUPOEQ.CODCOLIGADA= SEQUIVALENCIADISCGRADE.CODCOLIGADA
				AND 
					SDISCGRUPOEQ.IDGRUPO =SEQUIVALENCIADISCGRADE.IDGRUPOEQEQUIV
				AND 
					SHABILITACAOFILIAL.CODGRADE = SEQUIVALENCIADISCGRADE.CODGRADE
				 AND
					dbo.SDISCGRUPOEQ.CODDISC = SHISTDISCEQUIVCONCLUIDAS.CODDISC ----------------------************

				
	LEFT JOIN 
		SDISCIPLINA (NOLOCK)
			ON 
				dbo.SDISCIPLINA.CODDISC     = dbo.SEQUIVALENCIADISCGRADE.CODDISC 
			AND 
				dbo.SDISCIPLINA.CODCOLIGADA = dbo.SEQUIVALENCIADISCGRADE.CODCOLIGADA
				
	LEFT JOIN 
		STURMADISC  (NOLOCK)
			ON 
				STURMADISC.CODCOLIGADA = SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			AND 
				STURMADISC.IDTURMADISC = SHISTDISCEQUIVCONCLUIDAS.IDTURMADISC
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
					

			WHERE 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = 1 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.RA LIKE '00024091' --@RA
			

)


SELECT  DISTINCT
    
		     CODCOLIGADA
			,IDHABILITACAOFILIAL
			,RA
			,PLETIVO
			,CODDIS_EQUIVALENTE
			,DISC_EQUIVALENTE
			, CODDISC_GRADE
			,DISC_GRADE
			,STATUS
			,NUMCREDITOS
			,MAX(NOTA) AS NOTA1
			,CH			
			,CODPERIODO
			,FALTAS
			,TIPOHISTORICO
			,ProfTit
			,TOT_AULAS 

   FROM TAB1 
   
  --WHERE CODDISC_GRADE = 'GRA.080.0267' --'GRA.080.0235'

			GROUP BY CODCOLIGADA
			,IDHABILITACAOFILIAL
			,RA
			,PLETIVO
			,CODDIS_EQUIVALENTE
			,DISC_EQUIVALENTE
			, CODDISC_GRADE
			,DISC_GRADE
			,STATUS
			,NUMCREDITOS
			,CH			
			,CODPERIODO
			,FALTAS
			,TIPOHISTORICO
			,ProfTit
			,TOT_AULAS
			,IND
			,NOTA

			

			HAVING IND = 1

			ORDER BY CODDISC_GRADE

			---------------------------------------------------------------------------------------------

			--SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA= '00024091' AND GREQUIV = 1001 --AND CODDISC= 'GRA.080.0267'
			--ORDER BY DISCIPLINA