SET LANGUAGE BRAZILIAN

SELECT 
   P.CODPERLET
  ,SC.CODCURSO
  ,SC.NOME AS CURSO
  ,TUR.NOME AS TURNO
  ,M.CODTURMA
  ,S.DESCRICAO AS SITUACAO_MAT
  ,SANT.DESCRICAO SITUACAO_ANTERIOR
  ,M.RA
  ,PES.NOME AS ALUNO
  ,MOTALT.DESCRICAO AS MOTIVO_ALT
  ,CONVERT(VARCHAR,SLP.DTALTERACAO,103) AS DTALTERACAO
  ,PES.EMAIL
  ,SHBFIL.CODGRADE
  ,CASE  SHBFIL.CODTIPOCURSO WHEN 4 THEN 'GRADUAÇÃO' WHEN 6 THEN 'PÓS-GRADUAÇÃO' END AS TIPOCURSO
  ,STM.DESCRICAO AS TIPOMAT
  ,MES_ANO = RIGHT(CONVERT(VARCHAR,SLP.DTALTERACAO,103),7)

FROM SMATRICPL AS M

JOIN SPLETIVO P ON P.IDPERLET = M.IDPERLET
JOIN SLOGPLETIVO SLP ON  SLP.RA = M.RA AND SLP.CODTURMA = M.CODTURMA AND SLP.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL
JOIN SSTATUS S ON S.CODSTATUS=SLP.CODSTATUS AND (S.DESCRICAO LIKE '%TRANC%' OR S.DESCRICAO LIKE '%CANC%' OR S.DESCRICAO LIKE '%DESIS%' OR S.DESCRICAO LIKE '%TRANS%')
JOIN SSTATUS SANT ON SANT.CODSTATUS = SLP.CODSTATUSANT
JOIN SALUNO AL ON AL.RA = M.RA
JOIN PPESSOA PES ON PES.CODIGO = AL.CODPESSOA
JOIN SMOTIVOALTMAT MOTALT ON MOTALT.CODMOTIVO = SLP.CODMOTIVO
JOIN SHABILITACAOFILIAL SHBFIL ON SHBFIL.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL
JOIN SCURSO SC ON SC.CODCURSO = SHBFIL.CODCURSO
JOIN STURNO TUR ON TUR.CODTURNO = SHBFIL.CODTURNO
JOIN STIPOMATRICULA STM ON  STM.CODTIPOMAT = M.CODTIPOMAT

WHERE M.CODFILIAL = 18 AND P.CODTIPOCURSO IN (4,6) AND DTALTERACAO BETWEEN '01/01/2020' AND '15/05/2020'  AND P.CODPERLET LIKE '2020/1' --AND M.RA= '00024695' --M.RA='00027385'

ORDER BY CODPERLET,CURSO,ALUNO,DTALTERACAO