--BEGIN TRAN

--DELETE FROM SBOLSAALUNO WHERE EXISTS(

SELECT * FROM SBOLSAALUNO AS SBA

JOIN SPLETIVO AS PL ON PL.IDPERLET = SBA.IDPERLET

WHERE PL.CODPERLET = '2021/1' AND PL.CODTIPOCURSO = 4 AND CODBOLSA = 100 --AND SBA.IDBOLSAALUNO = SBOLSAALUNO.IDBOLSAALUNO

--)

--COMMIT