DECLARE @VAR AS VARCHAR

SET @VAR='T'
SET LANGUAGE PORTUGUêS

; WITH TABA  AS
(
SELECT * ,(SELECT COUNT(DISTINCT IDACORDO) FROM FACORDOREL WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL WHERE IDLAN = AA.IDLAN)) AS CONTA
,(CONVERT(MONEY,(VALORORIGINAL+ACRÉSCIMOS+PGTO_MAIOR+JUROSBX+MULTABX+HJUROSACORDO-DESC_ACORDO-DESC_PONTUALIDADE-DIMINUI_LIQ-PGTO_MENOR-BOLSA_INCOND-VALORDESCONTO))) AS VALOR_LIQUIDO
,(CONVERT(MONEY,(DESC_ACORDO+DESC_PONTUALIDADE+DIMINUI_LIQ+PGTO_MENOR+BOLSA_INCOND+VALORDESCONTO+BOLSA_CONDI))) AS DESC_GERAL
,CASE WHEN NSTATUSLAN NOT IN (0,4) THEN (CONVERT(MONEY,(ACRÉSCIMOS+PGTO_MAIOR+HJUROSACORDO+AUMENTA_LIQUI))) ELSE (CONVERT(MONEY,(ACRÉSCIMOS+PGTO_MAIOR+AUMENTA_LIQUI))) END AS ACRE_GERAL
,ISNULL(CONVERT(MONEY,(VALORORIGINAL-(CASE WHEN STATUSLAN='ABERTO' THEN (VALORORIGINALBX+DESC_ACORDO+HACRESCIMOACORDO) ELSE VALORORIGINALBX END))),0) AS VLR_ABERTO
,CASE WHEN TIPOPARCELA = 'P' THEN 'OK' WHEN CLASSIFICACAO = 2 AND TIPOPARCELA='A' THEN 'OK' ELSE 'NAO' END AS TWO
 FROM 

(
SELECT 
 CASE WHEN F.NOME='LIVROS DIDÁTICOS INTEGRADOS - MAT DID' THEN 'MATERIAL DIDÁTICO' 
	  WHEN A.CLASSIFICACAO = 15  THEN 'ACORDO Nº '+CONVERT(VARCHAR,B.IDACORDO)
     
 ELSE F.NOME END AS SERVICO
,B.CLASSIFICACAO
,E.PARCELA
,CONVERT(VARCHAR(10),A.DATAVENCIMENTO,103) VENCIMENTO
,ISNULL(CAST(A.VALORORIGINAL AS MONEY),0) VALORORIGINAL
,ISNULL(CAST(A.VALORDESCONTO AS MONEY),0) VALORDESCONTO
,ISNULL(CAST(A.VALORACRESCIMOACORDO AS MONEY),0) ACRÉSCIMOS 
,ISNULL(CAST(A.VALORBAIXADO AS MONEY),0) VALORBAIXADO
,ISNULL(CONVERT(VARCHAR(10),H.DATABAIXA,103),'') AS DATABAIXA
,CASE  WHEN B.CLASSIFICACAO = 2 AND STATUSLAN = 3 THEN 'ACORDO-'+CONVERT(VARCHAR,(SELECT FACORDOREL.IDACORDO FROM FACORDOREL WHERE A.IDLAN = FACORDOREL.IDLAN AND FACORDOREL.IDACORDO > B.IDACORDO)) 
      ELSE 
      CASE A.STATUSLAN WHEN 0 THEN 'ABERTO'
                       WHEN 1 THEN 'PAGO'
				       WHEN 2 THEN 'CANCELADO'
				       WHEN 3 THEN 'ACORDO - '+CONVERT(VARCHAR,B.IDACORDO)  
				       WHEN 4 THEN 'BX_PARCIAL' 
		  
				       /*ELSE CONVERT(VARCHAR,ISNULL(A.STATUSLAN,STATUSLAN))*/END  END AS STATUSLAN
 	,A.CODCOLIGADA
	,A.CODFILIAL
	,A.IDLAN
	,A.CLASSIFICACAO CLASFLAN
	,E.IDPARCELA
	,E.TIPOPARCELA
	,CASE WHEN A.STATUSLAN=0 OR A.STATUSLAN=4 THEN 0 ELSE ISNULL(CAST(A.VALORJUROSBX AS MONEY),0) END JUROSBX
	,ISNULL(CAST(H.VALORJUROSACORDO AS MONEY),0) HJUROSACORDO
	,CASE WHEN A.STATUSLAN=0 THEN /*':FORM (0106)'*/0 ELSE ISNULL(CAST(A.VALORMULTABX AS MONEY),0) END MULTABX
	,ISNULL(CAST(A.VALORDESCONTOACORDO AS MONEY),0) DESC_ACORDO
	,ISNULL(CAST(A.VALOROP3BX AS MONEY),0) DESC_PONTUALIDADE
	,ISNULL(CAST(A.VALOROP2BX AS MONEY),0) AS BOLSA_CONDI
	,ISNULL(CAST(H.VALORACRESCIMOACORDO AS MONEY),0) HACRESCIMOACORDO
	,E.RA
	,A.CODCFO
	,A.DATAEMISSAO
	,I.NOME NOME_ALUNO
	,ISNULL(CASE WHEN STATUSLAN IN (1,4) THEN CONVERT(MONEY,A.VALORBAIXADO) ELSE 0 END,0) VALORORIGINALBX
	,ISNULL(CONVERT(MONEY,A.VALORORIGINALBX),0) AS VVVV
	,ISNULL(CONVERT(MONEY,A.VALOROP8),0) BOLSA_INCOND
	,ISNULL(CONVERT(MONEY,A.VALOROP4),0) DIMINUI_LIQ
	,ISNULL(CONVERT(MONEY,A.VALOROP5),0) AUMENTA_LIQUI
	,ISNULL(CONVERT(MONEY,A.VALOROP7),0) PGTO_MENOR
	,ISNULL(CONVERT(MONEY,A.VALOROP6BX),0) PGTO_MAIOR
    ,STATUSLAN NSTATUSLAN

FROM FLAN A (NOLOCK)
LEFT JOIN FACORDOREL B (NOLOCK) ON A.IDLAN = B.IDLAN
JOIN SLAN D (NOLOCK) ON A.IDLAN = D.IDLAN
JOIN SPARCELA E (NOLOCK) ON E.IDPARCELA = D.IDPARCELA
JOIN SSERVICO F (NOLOCK) ON F.CODSERVICO = E.CODSERVICO
LEFT JOIN FACORDO C (NOLOCK) ON C.IDACORDO = B.IDACORDO
JOIN FCFO G (NOLOCK) ON A.CODCFO = G.CODCFO
LEFT JOIN FLANBAIXA H (NOLOCK) ON  H.IDLAN = A.IDLAN AND H.STATUS <> 1 
JOIN SCONTRATO K (NOLOCK) ON K.IDPERLET = E.IDPERLET AND K.RA=E.RA AND K.CODCONTRATO = E.CODCONTRATO
JOIN SALUNO J (NOLOCK) ON J.RA = K.RA
JOIN PPESSOA I (NOLOCK) ON I.CODIGO = J.CODPESSOA

WHERE A.CODFILIAL = 6 AND /* A.CODCFO='027882' AND*/ E.RA = /*'008954'*/'008975' /*'00019845'*/  AND STATUSLAN <> 2 

)AA
  WHERE AA.DATABAIXA = (SELECT ISNULL(DATABAIXA,'') FROM FLAN WHERE IDLAN=AA.IDLAN)

  GROUP BY SERVICO,	CLASSIFICACAO,	PARCELA,	VENCIMENTO,	VALORORIGINAL,	VALORDESCONTO,	ACRÉSCIMOS,	VALORBAIXADO,	DATABAIXA,	STATUSLAN,	CODCOLIGADA,	CODFILIAL,	IDLAN,	CLASFLAN,	IDPARCELA,	TIPOPARCELA,	JUROSBX,	HJUROSACORDO,	MULTABX,	DESC_ACORDO,	DESC_PONTUALIDADE,	BOLSA_CONDI,	HACRESCIMOACORDO,	RA,	CODCFO,	DATAEMISSAO,	NOME_ALUNO,	VALORORIGINALBX,	VVVV,	BOLSA_INCOND,	DIMINUI_LIQ,	AUMENTA_LIQUI,	PGTO_MENOR,	PGTO_MAIOR,	NSTATUSLAN


  ) /* FIM WITH  */

   SELECT *
   , ISNULL(CONVERT(SMALLMONEY,(SELECT SUM(TABA.VLR_ABERTO) FROM TABA WHERE NSTATUSLAN = (CASE @VAR  
								   WHEN 'A' THEN (SELECT NSTATUSLAN  WHERE NSTATUSLAN IN (4,0))							   
								   WHEN 'T' THEN NSTATUSLAN END))),0) AS TOTALGERAL 

   , ISNULL(CONVERT(SMALLMONEY,(SELECT SUM(TABA.VALORBAIXADO) FROM TABA WHERE NSTATUSLAN IN (4,1) 
      AND NSTATUSLAN = (CASE @VAR  WHEN 'A' THEN (SELECT NSTATUSLAN  WHERE NSTATUSLAN IN (4,0))							   
								   WHEN 'T' THEN NSTATUSLAN END))),0) AS BAIXADO_TOTAL  

   FROM TABA

   WHERE NSTATUSLAN IN (CASE @VAR  WHEN 'A' THEN (SELECT NSTATUSLAN  WHERE NSTATUSLAN IN (4,0))							   
								   WHEN 'T' THEN NSTATUSLAN END)

								   AND TWO = 'OK'
 

   ORDER BY RA,CONVERT(DATE,VENCIMENTO), PARCELA