SELECT ROW_NUMBER() OVER(ORDER BY C.NOME) AS N
,A.CODCOLIGADA,A.CODFILIAL,A.CODSTATUS,A.CODTURMA,A.IDHABILITACAOFILIAL,A.IDPERLET,A.NUMALUNO,A.RA
,B.CODPESSOA
,(C.NOME +'  '+A.RA)  AS NOME_ALUNO
,D.CODPERLET
,E.DESCRICAO STATUS_DESC
,CASE WHEN F.CODTURMAPROX IS NOT NULL THEN LEFT(F.NOMERED,2) ELSE F.NOMERED END AS INI
,CASE WHEN F.CODTURMAPROX IS NOT NULL THEN RIGHT(F.NOMERED,1) ELSE '' END AS FIM

FROM SMATRICPL (NOLOCK) A
 JOIN SALUNO B (NOLOCK) ON B.RA=A.RA
 JOIN PPESSOA C (NOLOCK) ON C.CODIGO = B.CODPESSOA
 JOIN SPLETIVO D (NOLOCK) ON D.IDPERLET = A.IDPERLET
 JOIN SSTATUS E (NOLOCK) ON E.CODSTATUS = A.CODSTATUS AND E.DESCRICAO LIKE '%MAT%'
 JOIN STURMA F (NOLOCK) ON F.CODTURMA = A.CODTURMA AND F.IDPERLET = A.IDPERLET

WHERE A.CODTURMA = 'EF.7A.M' AND D.CODPERLET = '2019'

ORDER BY C.NOME


--SELECT * FROM STURMA WHERE IDPERLET=270 CODTURMA = 'EF.7A.M'     BADMINTON VESP   SUB 17 MASC H   EM.1B.M