SELECT G.NOMEFANTASIA
,G.CGC
,UPPER(G.RUA ) AS RUA
,UPPER(G.NUMERO) AS NUMERO
,UPPER(G.BAIRRO) AS BAIRRO
,G.CEP
,UPPER(G.CIDADE) AS CIDADE
,UPPER(G.ESTADO) AS ESTADO
,PF.NOME AS NOME_FUNC
,PF.CHAPA
,PF.NROFICHAREG AS NRO_FICHA_REG
,PES.CARTEIRATRAB
,PES.TITULOELEITOR
,PES.CPF
,PES.CARTMOTORISTA
,PES.CARTIDENTIDADE AS IDENTIDADE
,PES.ORGEMISSORIDENT
,PES.UFCARTIDENT
,PES.SERIECARTTRAB
,PES.UFCARTTRAB
,CONVERT(VARCHAR,PES.DTCARTTRAB,103) AS DTCARTTRAB
,PES.CERTIFRESERV
,PES.CATEGMILITAR
,PES.REGPROFISSIONAL
,PES.ZONATITELEITOR
,PES.SECAOTITELEITOR
,PF.PISPASEP
,CONVERT(VARCHAR,PF.DTCADASTROPIS,103) AS DTCADASTROPIS
,PES.TIPOCARTHABILIT
,CONVERT(VARCHAR,PES.DTEMISSAOIDENT,103) AS DTEMISSAOIDENT
,CONVERT(VARCHAR,PF.DATAADMISSAO,103) AS DATAADMISSAO
,FUNC.NOME AS CARGO
,CONVERT(VARCHAR,PF.DTOPCAOFGTS,103) AS DTOPCAOFGTS
,SEC.DESCRICAO AS SECAO
,FORMAT(PF.SALARIO,'C','PT-BR') AS SALARIO
--,PF.CODRECEBIMENTO
,REC.DESCRICAO AS RECEBIMENTORE
,PF.JORNADAMENSAL
,CONVERT(DECIMAL(4,2),(PF.SALARIO/PF.JORNADAMENSAL)*60) AS SAL_HR
,PES.DTNASCIMENTO
,PES.NACIONALIDADE
,PES.NATURALIDADE
,PES.ESTADOCIVIL
,PES.ESTADONATAL
,PES.SEXO
,PES.GRAUINSTRUCAO
,PES.DATACHEGADA
,PES.TIPOVISTO
,PES.NATURALIZADO
,PES.NROFILHOSBRASIL
,PES.NROREGGERAL
,PES.CONJUGEBRASIL
,PES.NRODECRETO
,PES.DTVENCIDENT
,PES.DTVENCCARTTRAB
,IMG.IMAGEM
,MOTIVODEMISSAO
,PES.RUA
,PES.NUMERO
,PES.BAIRRO
,PES.CIDADE
 
FROM PFUNC PF

JOIN GFILIAL G ON G.CODFILIAL = PF.CODFILIAL
JOIN PPESSOA PES ON PF.CODPESSOA = PES.CODIGO 
JOIN PFUNCAO FUNC ON FUNC.CODIGO = PF.CODFUNCAO
JOIN PSECAO SEC ON SEC.CODIGO = PF.CODSECAO
JOIN PCODRECEB REC ON REC.CODCLIENTE = PF.CODRECEBIMENTO
JOIN GIMAGEM IMG ON IMG.ID = PES.IDIMAGEM
 
WHERE PF.CHAPA = 060189  AND PF.CODFILIAL = 6

--       SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'GIMAGEM'