/*
BOLSA 490 - AUX. ESTAGIARIO

GRATIFIC, INSS/ISS/IR
*/

DECLARE @ANOCOMP INT, @MESCOMP INT, @NROPERIODO INT, @CODFILIAL  INT  
SET @ANOCOMP = '2019'--:ANO_N; 
SET @MESCOMP = '1'--:MES_N; 
SET @NROPERIODO = 2;
SET @CODFILIAL = 5

SELECT 'DOCENTES' TIPOFUNC, PFUNC.CODFILIAL, PSECAO.DESCRICAO SECAOFUNCIONARIO, PFUNC.CHAPA, PFUNC.NOME, PPESSOA.CPF,
ISNULL(CONVERT(VARCHAR, PFUNC.DATAADMISSAO,103),'') DATAADMISSAO, PFUNC.CODSITUACAO,
PFUNCAO.NOME FUNCAO, ISNULL(PCODINSTRUCAO.DESCRICAO,'') GRAUINSTRUCAO,
PPESSOA.SEXO, CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS DTNASCIMENTO,PEVENTO.CODIGO AS CODEVENTO,
PEVENTO.DESCRICAO EVENTO, PFFINANC.ANOCOMP,PFFINANC.MESCOMP, PFSALCMP.VALOR,
CONVERT(DECIMAL(18,2),PFSALCMP.JORNADA / 60.0) JORNADAMENSAL,
CONVERT(DECIMAL(18,2),PFSALCMP.VALOR / (PFSALCMP.JORNADA / 60.0)) VALORHORA,
CONVERT(DECIMAL(18,2),
ISNULL((SELECT SUM((PFSALCMP.JORNADA / 60.0) / 4.5) 
	FROM PFSALCMP 
	WHERE  PFSALCMP.CHAPA = PFUNC.CHAPA
	AND PFFINANC.CODEVENTO = PFSALCMP.CODEVENTO), '0')) JORNADASEMANAL,
	
	
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO IN('0020','0041','0037','0040','0045','0055','0056','0059','0076','0079',
'0080','0081','0086','0087','0092','0112','0119','0125','0146','0166','0176','0183','0187',
'0203','0213','0265','0274','0275','0287','0298','0299','0308','0309','0311','0313','0316','0322',
'0325','0424','0507','0508','0509','0510','0511','0512','0513','0514','0515','0516','0517','0518',
'0519','0520','0521','0522','0523','0524','0525','0526','0527','0528','0529','0530','0531','0600','0210','0540')), 0) EVENTOSESPORADICOS,	
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP 
AND PF.MESCOMP =PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'DSR%'),0) DSR,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'HORA ATIVIDADE%'),0) HORAATIVIDADE,

ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'QUINQUENIO%'),0) QUINQUENIO,
ISNULL((SELECT SUM(PF.REF) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'QUINQUENIO%'),0) REFQUINQUENIO,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0003'),0) INSS,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0004'),0) IR,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0490'),0) AS AUX_ESTAGIARIO

FROM PFUNC WITH (NOLOCK)
INNER JOIN PFFINANC ON PFFINANC.CHAPA = PFUNC.CHAPA
INNER JOIN PEVENTO ON PEVENTO.CODIGO = PFFINANC.CODEVENTO      
INNER JOIN PSECAO ON PSECAO.CODIGO = PFUNC.CODSECAO
INNER JOIN PFUNCAO ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
INNER JOIN PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN PCODINSTRUCAO ON PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODCLIENTE
/*INNER*/left JOIN PFSALCMP ON PFUNC.CHAPA = PFSALCMP.CHAPA /*Alterado para LEFT JOIN para geração de relatórios anteriores a 2017 - Augusto Ambrozio - 08/12/2017*/
AND PEVENTO.CODIGO = PFSALCMP.CODEVENTO
WHERE PFFINANC.ANOCOMP IN ('2019','2020')-- PFFINANC.MESCOMP
AND PFFINANC.MESCOMP BETWEEN 1 AND 12 --PFFINANC.ANOCOMP
AND PFFINANC.NROPERIODO = @NROPERIODO
/*AND PFUNC.CODSITUACAO <> 'D'*/ /*Removido em 07/12/2017 por Augusto Ambrozio para relação de docentes de 2016*/
and PFUNC.CODFILIAL in (@CODFILIAL)

UNION ALL

SELECT 'ADM' TIPOFUNC, PFUNC.CODFILIAL, PSECAO.DESCRICAO SECAOFUNCIONARIO, PFUNC.CHAPA, PFUNC.NOME, PPESSOA.CPF,
ISNULL(CONVERT(VARCHAR, PFUNC.DATAADMISSAO,103),'') DATAADMISSAO, PFUNC.CODSITUACAO,
PFUNCAO.NOME FUNCAO, ISNULL(PCODINSTRUCAO.DESCRICAO,'') GRAUINSTRUCAO,
PPESSOA.SEXO, CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS DTNASCIMENTO,PEVENTO.CODIGO AS CODEVENTO,
PEVENTO.DESCRICAO EVENTO,PFFINANC.ANOCOMP,PFFINANC.MESCOMP, PFUNC.SALARIO,
CONVERT(DECIMAL(18,2),PFUNC.JORNADAMENSAL / 60.0) JORNADAMENSAL,
CONVERT(DECIMAL(18,2),PFUNC.SALARIO / (PFUNC.JORNADAMENSAL / 60.0)) VALORHORA,
CONVERT(DECIMAL(18,2),ISNULL((PFUNC.JORNADAMENSAL / 60.0 / 5.0), '0')) JORNADASEMANAL,	
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO IN('0020','0041','0037','0040','0045','0055','0056','0059','0076','0079',
'0080','0081','0086','0087','0092','0112','0119','0125','0146','0166','0176','0183','0187',
'0203','0213','0265','0274','0275','0287','0298','0299','0308','0309','0311','0313','0316','0322',
'0325','0424','0507','0508','0509','0510','0511','0512','0513','0514','0515','0516','0517','0518',
'0519','0520','0521','0522','0523','0524','0525','0526','0527','0528','0529','0530','0531','0600','0210','0540')), 0) EVENTOSESPORADICOS,	
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP >= PFFINANC.MESCOMP     --*********************
AND PF.MESCOMP BETWEEN 1 AND 12 --PFFINANC.ANOCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'DSR%'),0) DSR,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'HORA ATIVIDADE%'),0) HORAATIVIDADE,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'QUINQUENIO%'),0) QUINQUENIO,
ISNULL((SELECT SUM(PF.REF) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.DESCRICAO LIKE 'QUINQUENIO%'),0) REFQUINQUENIO,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0003'),0) INSS,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0004'),0) IR,
ISNULL((SELECT SUM(PF.VALOR) FROM PFFINANC PF
INNER JOIN PEVENTO PE ON PF.CODEVENTO = PE.CODIGO
WHERE PF.CHAPA = PFUNC.CHAPA
AND PF.ANOCOMP = PFFINANC.ANOCOMP
AND PF.MESCOMP = PFFINANC.MESCOMP
AND PF.NROPERIODO = @NROPERIODO
AND PE.CODIGO = '0490'),0) AS AUX_ESTAGIARIO

FROM PFUNC WITH (NOLOCK)
INNER JOIN PFFINANC ON PFFINANC.CHAPA = PFUNC.CHAPA
INNER JOIN PEVENTO ON PEVENTO.CODIGO = PFFINANC.CODEVENTO      
INNER JOIN PSECAO ON PSECAO.CODIGO = PFUNC.CODSECAO
INNER JOIN PFUNCAO ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
INNER JOIN PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO
LEFT JOIN PCODINSTRUCAO ON PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODCLIENTE
WHERE PFFINANC.ANOCOMP IN ('2019','2020')--@ANOCOMP
AND PFFINANC.MESCOMP BETWEEN 1 AND 12 --@MESCOMP
AND PEVENTO.CODIGO in ('0002','0017')
AND PFUNC.USASALCOMPOSTO = 0
AND PFFINANC.NROPERIODO = @NROPERIODO
AND PFUNC.CODSITUACAO <> 'D'
and PFUNC.CODFILIAL in (@CODFILIAL)

/*
AND PF.ANOCOMP >= @ANOCOMP     --*********************
AND PF.MESCOMP BETWEEN 1 AND 12 --@MESCOMP
*/