--SELECT * FROM MAT WHERE CODFILIAL = 6 AND STATUS LIKE 'MAT%' AND CODPERLET = '2019'

SELECT ROW_NUMBER()OVER(ORDER BY TAB1.NOME,TAB1.RA) AS ID,DTNASCIMENTO  FROM
(
	SELECT DISTINCT 

	SMATRICPL.RA,PPESSOA.NOME,CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS DTNASCIMENTO--,SPLETIVO.CODPERLET

	 FROM SMATRICPL(NOLOCK) 
		  JOIN SALUNO(NOLOCK) ON SALUNO.RA = SMATRICPL.RA 
		  JOIN PPESSOA(NOLOCK) ON PPESSOA.CODIGO = SALUNO.CODPESSOA 
		  JOIN SPLETIVO(NOLOCK) ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET

		 -- WHERE NOME LIKE 'LEONARDO%'
) AS TAB1

	  ORDER BY ID 



	--  SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SALUNO'

--SELECT COUNT( RA) AS CONT, RA,CODTURMA FROM MAT

-- WHERE CODFILIAL = 5 AND CODPERLET = '2019'  

-- GROUP BY RA,CODTURMA