ALTER FUNCTION HIST_OURINHOS (@RA AS VARCHAR(12))

RETURNS  TABLE 

AS

RETURN 

(

SELECT DISTINCT
  HDC.CODCURSOHIST
, HDC.RA
, HDC.ANO
, HDC.CODDISCHIST
, D.NOME AS DISCIPLINA
, HDC.CODSERIEHIST
, CASE HDC.CODPARTEHIST WHEN 1 THEN 'COMUM' WHEN 2 THEN 'DIVERSIFICADA' END AS BASE_NACIONAL
, HDC.POSICAO
, HDC.NOTA
, HDC.FALTAS
, HDC.CODSTATUS
, HAC.CARGAHORARIA
, HAC.DIASLETIVOS
, HAC.DIRETOR
, I.NOME AS INSTITUICAO
, HAC.CODSERIEHIST AS SERIE
, HAB.CODSERIEHIST AS HABCODSERIE

 FROM SHISTDISCCOL AS HDC

LEFT JOIN SDISCIPLINA AS D ON D.CODDISCHIST = HDC.CODDISCHIST AND CODTIPOCURSO = 12
LEFT JOIN SHISTALUNOCOL AS HAC ON HAC.RA = HDC.RA AND HAC.ANO = HDC.ANO AND HAC.CODCURSOHIST = HDC.CODCURSOHIST AND HAC.CODSERIEHIST = HDC.CODSERIEHIST
LEFT JOIN SINSTITUICAO AS I ON I.CODINST = HAC.CODINST
JOIN SHABILITACAO AS HAB ON HAB.CODCURSOHIST = HDC.CODCURSOHIST

WHERE HDC.RA= '00025908' -- @RA 
)  
   

   -- CHAMAR DESSA FORMA
   SELECT * FROM HIST_OURINHOS('00025908')



   SELECT * FROM SHABILITACAO WHERE CODHABILITACAO = 'EM-0013' --SMATRICPL WHERE RA= '00025908'