CREATE FUNCTION D_DT_EXTENSO (@DT AS DATE)

RETURNS VARCHAR(1000)

BEGIN
DECLARE @X AS VARCHAR(1000)

 SET @X =  REPLACE(CONVERT(VARCHAR,DBO.INITCAP(FORMAT(@DT, 'D'))),'De','de')

 RETURN @X
END