SET LANGUAGE PORTUGUÍS
SET DATEFORMAT DMY

--DECLARE @VAR1 AS VARCHAR(10), @VAR2 AS VARCHAR(10)

--SET @VAR1 = '25.000000' --SUBSTRING('25.000000',1,CHARINDEX('0','25.000000',CHARINDEX('.','25.000000')))

--SET @VAR2 = '27.500000' --SUBSTRING('27.500000',1,CHARINDEX('0','27.500000',CHARINDEX('.','27.500000')))

SELECT  DISTINCT
 CHAPA
,NOME
,DTVENCFERIAS
,CONVERT(VARCHAR,DTINIPERAQUIS,103) AS DTINIPERAQUIS
,CONVERT(VARCHAR,DTFIMPERAQUIS,103) AS DTFIMPERAQUIS
,MAX(TABA.INICIOFERIAS) AS INICIOFERIAS
,MAX(TABA.FIMFERIAS) AS FIMFERIAS
,CODFILIAL

   ,SALDO
   --,DIF_HOJE
   --,SOMA_DIA_FERIAS
   ,DINI
   ,DFIM
   ,DATEDIFF(M,DINI,DFIM) AS DIFERENCA

   --,ISNULL(CASE WHEN DTVENCFERIAS <= GETDATE() THEN CONVERT(DECIMAL(18,0),CASE WHEN SALDO = 0 THEN SOMA_DIA_FERIAS ELSE SALDO END) ELSE 0 END,0) AS DIAS_HAVER --SALDO$
  -- ,PERIODOABERTO
   --,SOMA_DIA_FERIAS
   , NRODIASFERIAS 
   , DT_DIF_PER_ARQUI
   , DT_DIF_HOJE
   , SALDO_PER = CASE WHEN (dbo.D_NUM_DEC_INT((CONVERT(DECIMAL(4,1),30*DT_DIF_HOJE)) / CONVERT(DECIMAL(4,1),DT_DIF_PER_ARQUI))) > '30' THEN '30' 
      ELSE dbo.D_NUM_DEC_INT((CONVERT(DECIMAL(4,1),30*DT_DIF_HOJE)) / CONVERT(DECIMAL(4,1),DT_DIF_PER_ARQUI)) END

   , FERIAS_A_MARCAR = dbo.D_NUM_DEC_INT((CONVERT(DECIMAL(4,1),30*DT_DIF_HOJE)) / CONVERT(DECIMAL(4,1),DT_DIF_PER_ARQUI)) - NRODIASFERIAS
 
 FROM	

(
	SELECT  PFUNC.CHAPA , PFUNC.NOME
	,CONVERT(VARCHAR,PFUNC.DTVENCFERIAS,103) AS DTVENCFERIAS
	, MAX(PFHSTFER.DTINIPERAQUIS) AS DTINIPERAQUIS
	, MAX(PFHSTFER.DTFIMPERAQUIS) AS DTFIMPERAQUIS
	,CONVERT(VARCHAR,MAX(PFUFERIASPER.DATAINICIO),103) AS INICIOFERIAS
	,CONVERT(VARCHAR,MAX(PFUFERIASPER.DATAFIM),103) AS  FIMFERIAS
	,PFUNC.CODFILIAL
	,MAX(CONVERT(VARCHAR,PFUFERIASPER.DATAINICIO,103)) AS DTINI
	,MAX(CONVERT(VARCHAR,PFUFERIASPER.FIMPERAQUIS,103)) AS DTFIM
	,DATEDIFF(MONTH,MAX(PFUFERIAS.INICIOPERAQUIS)-1,MAX(PFUFERIAS.FIMPERAQUIS)) as DIF_PER_AQUI
	--  ,DATEDIFF(MONTH,MAX(PFUFERIAS.FIMPERAQUIS),GETDATE()) AS DIF_HOJE 
	  ,PFUFERIAS.SALDO
      ,CONVERT(VARCHAR,'01'+FORMAT(MAX(PFUFERIAS.INICIOPERAQUIS)-1,'/MM/yyyy'),103) AS DINI 
      ,CONVERT(VARCHAR,'01'+FORMAT(MAX(PFUFERIAS.FIMPERAQUIS),'/MM/yyyy'),103) AS DFIM 
	   
	--,ISNULL((SELECT SUM(NRODIASFERIAS) FROM PFUFERIASPER A WHERE A.FIMPERAQUIS = ( SELECT MAX(PF.FIMPERAQUIS) FROM PFUFERIAS PF WHERE PFUNC.CHAPA = PF.CHAPA)),0) AS SOMA_DIA_FERIAS
	,PFUFERIAS.PERIODOABERTO
	,PFUNC.NRODIASFERIAS
	,DATEDIFF(DAY,DTINIPERAQUIS,DTFIMPERAQUIS) /30 AS DT_DIF_PER_ARQUI
    ,CAST(ROUND(CONVERT(DECIMAL(5,2),DATEDIFF(DAY,DTINIPERAQUIS,GETDATE())/30)+1,0) AS INT) AS DT_DIF_HOJE

	FROM PFUNC
	LEFT JOIN PFHSTFER
	  ON PFHSTFER.CHAPA = PFUNC.CHAPA
	 AND PFHSTFER.CODCOLIGADA = PFUNC.CODCOLIGADA
	 AND PFHSTFER.DTINIPERAQUIS = (SELECT MAX(PFHSTFER.DTINIPERAQUIS) FROM PFHSTFER WHERE PFHSTFER.CHAPA = PFUNC.CHAPA)
	LEFT JOIN PFUFERIASPER ON PFUNC.CHAPA = PFUFERIASPER.CHAPA AND PFUFERIASPER.DATAINICIO = (SELECT MAX(DATAINICIO)AS DTINIPF FROM PFUFERIASPER PF WHERE PF.CHAPA = PFUNC.CHAPA)
	LEFT JOIN PFUFERIAS ON PFUFERIAS.CHAPA = PFUNC.CHAPA AND PFUFERIAS.FIMPERAQUIS = (SELECT MAX(PF.FIMPERAQUIS) FROM PFUFERIAS PF WHERE PF.CHAPA = PFUNC.CHAPA)

	WHERE PFUNC.CODFILIAL IN (21,1) --:P_CODFILIAL
	 AND PFUNC.CODSITUACAO NOT IN ('P','I','D')
	 AND PFUNC.CODTIPO IN ('N','Z')
	AND PFUNC.CHAPA IN ('210021','010066' ,'010069','010063','010070', '010048', '010004','010065')
	--AND ISNULL(PFUFERIAS.PERIODOABERTO,1) = 1

	GROUP BY PFUNC.CHAPA,PFUNC.DTVENCFERIAS, PFHSTFER.DTINIPERAQUIS, PFHSTFER.DTFIMPERAQUIS, pfunc.codfilial,PFUFERIAS.INICIOPERAQUIS,PFUFERIAS.FIMPERAQUIS,SALDO,PFUNC.NOME,PFUFERIASPER.DATAINICIO,PFUFERIASPER.FIMPERAQUIS,PERIODOABERTO,PFUNC.NRODIASFERIAS

	) TABA

	GROUP BY CHAPA,NOME,DTVENCFERIAS,DTINIPERAQUIS,DTFIMPERAQUIS,INICIOFERIAS,FIMFERIAS,CODFILIAL,DTFIM,SALDO,PERIODOABERTO,DFIM,DINI,NRODIASFERIAS , DT_DIF_PER_ARQUI
   , DT_DIF_HOJE

	ORDER BY NOME