/* ARRUMAR PROBLEMA DE CHAVE DUPLICADAS MESMO SEM BOLSAS, PROBLEMA OCORREU QUANDO O OSVALDO PEDIU PARA IMPORTAR AS BOLSAS POR SQL E O AUTOINC (IDBOLSAALUNO) FICOU DIFERENTE DA TABELA GAUTOINC
   O MAX(IDBOLSAALUNO) DEVE SER O MEMSO NÚMERO OU 1 MAIOR QUE O VALAUTOINC DA TABELA GAUTOINC 
*/

--SELECT MAX(IDBOLSAALUNO) FROM SBOLSAALUNO

--BEGIN TRAN
--UPDATE GAUTOINC SET VALAUTOINC = 119270 WHERE CODAUTOINC = 'IDBOLSAALUNO'

--COMMIT

SELECT * FROM GAUTOINC WHERE CODAUTOINC = 'IDBOLSAALUNO'