SET LANGUAGE PORTUGUÍS

 SELECT 
 PFHSTSEC.CHAPA
,PFUNC.NOME
,PFHSTSEC.MOTIVO AS CODMOTIVO
,PMOTMUDSECAO.DESCRICAO AS MOTIVO 
,PFHSTSEC.CODSECAO
,PSECAO.DESCRICAO AS SECAO
,PSECAO.CODFILIAL AS FIL_SECAO
,PFUNC.CODSITUACAO
,PFUNC.CODFUNCAO
,PFUNCAO.NOME AS FUNCAO
,CONVERT(VARCHAR(12),PFHSTSEC.DTMUDANCA,103) AS DTMUDANCA 
,ISNULL(X.CODFILIAL,PSECAO.CODFILIAL) AS FIL_ANTERIOR


 FROM PFHSTSEC  

 JOIN PFUNC ON PFUNC.CHAPA = PFHSTSEC.CHAPA
 LEFT JOIN PMOTMUDSECAO ON PMOTMUDSECAO.CODCLIENTE = PFHSTSEC.MOTIVO
 JOIN PSECAO ON PSECAO.CODIGO = PFHSTSEC.CODSECAO
 JOIN PFUNCAO ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO
 LEFT JOIN (SELECT TOP 100 PERCENT S.CHAPA,P.CODFILIAL,P.CODIGO,S.DTMUDANCA
			FROM PFHSTSEC AS S
			
			LEFT JOIN PSECAO AS P ON P.CODIGO = S.CODSECAO
			
			ORDER BY DTMUDANCA DESC
			) AS X ON X.CHAPA = PFUNC.CHAPA  AND  X.DTMUDANCA < PFHSTSEC.DTMUDANCA 

WHERE 

 PFHSTSEC.DTMUDANCA BETWEEN '01/06/2019' AND '30/07/2019' --AND PFUNC.CHAPA = '070066'

 ORDER BY NOME




--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'PSECAO'


