
DECLARE @RA AS VARCHAR (100) , @PROF AS VARCHAR(500)

SET @RA = '00016659'--:RA1
			
SELECT
	 DISTINCT  CASE WHEN COUNT(DISCAPROVADAS.ProfTit)>1 THEN ( SELECT DISCAPROVADAS.ProfTit FROM DISCAPROVADAS) ELSE DISCAPROVADAS.ProfTit END AS AA ,SDISCGRADE.CODDISC 
	 /*
	 SHABILITACAOFILIAL.CODCOLIGADA 
	,SDISCGRADE.CODGRADE
	,SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	,SDISCGRADE.CODPERIODO
	
	/**/
		,/*CASE
		WHEN
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NOT NULL THEN ZEQUIVHISTORICO.CODDIS_EQUIVALENTE
		WHEN
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NULL THEN SDISCIPLINA.CODDISC
		WHEN 
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NOT NULL THEN SDISCGRADE.CODDISC -- DISCAPROVADAS.CODDISC
				END*/ SDISCGRADE.CODDISC AS CODDISC
				
				/*****************************/
	,/*CASE
		WHEN
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NOT NULL THEN ZEQUIVHISTORICO.DISC_EQUIVALENTE
		WHEN
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NULL THEN SDISCIPLINA.NOME
		WHEN 
			ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NOT NULL THEN DISCAPROVADAS.DISCIPLINA
				END*/ SDISCIPLINA.NOME AS DISCIPLINAS
				/*****************************/
				
	,ZEQUIVHISTORICO.DISC_EQUIVALENTE,DISCAPROVADAS.DISCIPLINA, SDISCIPLINA.NOME
	
	
	,ISNULL(ISNULL(DISCAPROVADAS.PLETIVO, ZEQUIVHISTORICO.PLETIVO), ZAPROVEITA.CODPERLET) AS PLETIVO
		
	,/*ISNULL(ISNULL(ISNULL(DISCAPROVADAS.CH, ZEQUIVHISTORICO.CH),ZAPROVEITA.CARGAHORARIA),0)*/ SDISCIPLINA.CH AS CH
	,ISNULL(ISNULL(ISNULL(DISCAPROVADAS.FALTAS , ZEQUIVHISTORICO.FALTAS),ZAPROVEITA.FALTAS),0) AS FALTAS
	,CAST ( (100 - ((ISNULL(ISNULL(ISNULL(DISCAPROVADAS.FALTAS , ZEQUIVHISTORICO.FALTAS),ZAPROVEITA.FALTAS),0)
		* 100) 
			/ CASE 
		WHEN ISNULL (ISNULL (DISCAPROVADAS.TOT_AULAS, ZEQUIVHISTORICO.TOT_AULAS),0.00001) = 0 
			THEN 0.00001 
				ELSE  ISNULL (ISNULL (DISCAPROVADAS.TOT_AULAS, ZEQUIVHISTORICO.TOT_AULAS),0.00001) 
					END)) AS NUMERIC (10,2))AS  PCENTPRESENCA
	
	,ISNULL(ISNULL(ISNULL(DISCAPROVADAS.NOTA, ZEQUIVHISTORICO.NOTA),ZAPROVEITA.NOTA),0) AS NOTA 
	,ISNULL(DISCAPROVADAS.STATUS, ZAPROVEITA.STATUS) AS STATUS
	,ISNULL(DISCAPROVADAS.CODEXTERNO, ISNULL(ZAPROVEITA.CODEXTERNO, (SELECT TOP 1 CODEXTERNO FROM SSTATUS WHERE SSTATUS.DESCRICAO = ZEQUIVHISTORICO.STATUS) )) AS CODEXTERNO
	, ISNULL(CASE WHEN ISNULL(DISCAPROVADAS.CODEXTERNO, ZAPROVEITA.CODEXTERNO) IN ('DPE','APE') THEN '******' ELSE
	   CASE
			WHEN
				ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NOT NULL THEN ZEQUIVHISTORICO.ProfTit
			WHEN
				ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NULL THEN ZEQUIVHISTORICO.ProfTit
			WHEN 
				ZEQUIVHISTORICO.DISC_EQUIVALENTE IS NULL AND DISCAPROVADAS.DISCIPLINA IS NOT NULL THEN DISCAPROVADAS.ProfTit
					END 
					    END,'******')AS ProfTit
	
	  --, @PROF = 'AAAAAAAAA'--ISNULL(ZEQUIVHISTORICO.ProfTit,'')-- + CHAR(13)+CHAR(10)
	  
	    --,DISCAPROVADAS.ProfTit
		*/
	
		FROM
		SHABILITACAOALUNO(NOLOCK)
	JOIN 
		SHABILITACAOFILIAL HABMATRICULA(NOLOCK)
			ON 
				SHABILITACAOALUNO.CODCOLIGADA = HABMATRICULA.CODCOLIGADA
			AND 
				SHABILITACAOALUNO.IDHABILITACAOFILIAL  = HABMATRICULA.IDHABILITACAOFILIAL
	JOIN 
		/*DISCIPLINAS DA GRADE E DA MATRICULA*/	
		SDISCGRADE
			ON 
				SDISCGRADE.CODCOLIGADA = HABMATRICULA.CODCOLIGADA
			AND 
				SDISCGRADE.CODCURSO=HABMATRICULA.CODCURSO
			AND 
				SDISCGRADE.CODGRADE=HABMATRICULA.CODGRADE
			AND 
				SDISCGRADE.CODHABILITACAO=HABMATRICULA.CODHABILITACAO
			
	JOIN 
		SDISCIPLINA	
			ON 
				SDISCIPLINA.CODCOLIGADA = SDISCGRADE.CODCOLIGADA
			AND 
				SDISCIPLINA.CODDISC   = SDISCGRADE.CODDISC
	JOIN 
		SGRADE (NOLOCK)
			ON 
				SGRADE.CODCOLIGADA  = SDISCGRADE.CODCOLIGADA
			AND 
				SGRADE.CODCURSO = SDISCGRADE.CODCURSO
			AND 
				SGRADE.CODHABILITACAO = SDISCGRADE.CODHABILITACAO
			AND 
				SGRADE.CODGRADE = SDISCGRADE.CODGRADE				
	JOIN 
		SHABILITACAOFILIAL (NOLOCK)
			ON 
				SGRADE.CODCOLIGADA  = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO
			AND 
				SGRADE.CODHABILITACAO = SHABILITACAOFILIAL.CODHABILITACAO
			AND 
				SGRADE.CODGRADE = SHABILITACAOFILIAL.CODGRADE	
			AND 
				HABMATRICULA.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
				
				
	/*DISCIPLINAS CURSADAS*/
	LEFT  JOIN 
	(
	SELECT	
		DISTINCT 
	 SHABILITACAOFILIAL.CODCOLIGADA
	,SHABILITACAOFILIAL.CODCURSO
	/*,SHABILITACAOFILIAL.IDHABILITACAOFILIAL*/
	,SHABILITACAOFILIAL.CODHABILITACAO
	,SHABILITACAOFILIAL.CODTURNO
	/*,SHABILITACAOFILIAL.CODGRADE*/
	,SHISTDISCCONCLUIDAS.RA
	
	,SHISTDISCCONCLUIDAS.CODPERIODO
	      ,SHISTDISCCONCLUIDAS.CODDISC
	,SHISTDISCCONCLUIDAS.DISCIPLINA
	,SHISTDISCCONCLUIDAS.PLETIVO
	,CAST (SHISTDISCCONCLUIDAS.CH AS NUMERIC(10,2)) AS CH
	,CAST (SHISTDISCCONCLUIDAS.FALTAS AS NUMERIC(10,2)) AS FALTAS
	,CAST (SHISTDISCCONCLUIDAS.NOTA AS NUMERIC(10,2)) AS NOTA
	,SHISTDISCCONCLUIDAS.STATUS
	,SSTATUS.CODEXTERNO
	,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
	,AULAS.TOT_AULAS
	
	FROM 
		SHISTDISCCONCLUIDAS (NOLOCK)
	JOIN 
		SHABILITACAOFILIAL (NOLOCK)
			ON 
				SHISTDISCCONCLUIDAS.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL  
	JOIN 
		SSTATUS (NOLOCK)
			ON 
				SSTATUS.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
			AND 
				SSTATUS.CODSTATUS = SHISTDISCCONCLUIDAS.CODSTATUS
				
	JOIN 
		STURMADISC  (NOLOCK)
			ON 
				STURMADISC.CODCOLIGADA = SHISTDISCCONCLUIDAS.CODCOLIGADA
			AND 
				STURMADISC.IDTURMADISC = SHISTDISCCONCLUIDAS.IDTURMADISC
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
		
			WHERE
				SHISTDISCCONCLUIDAS.CODCOLIGADA = 1/*CODCOLIGADA1*/
			and 				 
				SHISTDISCCONCLUIDAS.RA = @RA
			AND 
				SHISTDISCCONCLUIDAS.IDHABILITACAOFILIAL = 1089
			/*AND 
				SHISTDISCCONCLUIDAS.CODPERIODO =2--:CODPERIODO1*/
				
	)DISCAPROVADAS
		ON 
			DISCAPROVADAS.CODCOLIGADA = SDISCGRADE.CODCOLIGADA
		AND 
			DISCAPROVADAS.CODPERIODO = SDISCGRADE.CODPERIODO
		AND 
			DISCAPROVADAS.DISCIPLINA = SDISCIPLINA.NOME
		AND 
			DISCAPROVADAS.RA = SHABILITACAOALUNO.RA
		
			
/*****************************************************************************************************************/			
	LEFT JOIN	
(	
SELECT 
*
FROM

(
/*EQUIVALENTES CONCLUÍDAS - GRADE***********************************************************************************/
SELECT 
			 ROW_NUMBER() OVER(PARTITION BY SEQUIVALENCIADISCGRADE.CODDISC ORDER BY NOTA DESC) AS IND
			,SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			,SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVCONCLUIDAS.RA
			,SHISTDISCEQUIVCONCLUIDAS.PLETIVO
			,SHISTDISCEQUIVCONCLUIDAS.CODDISC AS CODDIS_EQUIVALENTE
			,SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA AS DISC_EQUIVALENTE
			,SEQUIVALENCIADISCGRADE.CODDISC AS CODDISC_GRADE
			,dbo.SDISCIPLINA.NOME AS DISC_GRADE
			,SHISTDISCEQUIVCONCLUIDAS.STATUS
			,SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS
			,SHISTDISCEQUIVCONCLUIDAS.NOTA
			,SHISTDISCEQUIVCONCLUIDAS.CH			
			,SEQUIVALENCIADISCGRADE.CODPERIODO AS CODPERIODO
			,SHISTDISCEQUIVCONCLUIDAS.FALTAS
			,'Equivalentes Concluídas' AS TIPOHISTORICO
			,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
			,AULAS.TOT_AULAS
	FROM 
		SHISTDISCEQUIVCONCLUIDAS (NOLOCK)/*47 Rows*/

		
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.GREQUIV  = SDISCGRUPOEQ.IDGRUPO

	 LEFT JOIN /**/
		dbo.SEQUIVALENCIADISCGRADE (NOLOCK)
			ON 
				
					SDISCGRUPOEQ.CODCOLIGADA= SEQUIVALENCIADISCGRADE.CODCOLIGADA
				AND 
					SDISCGRUPOEQ.IDGRUPO =SEQUIVALENCIADISCGRADE.IDGRUPOEQEQUIV
				AND 
					SHABILITACAOFILIAL.CODGRADE = SEQUIVALENCIADISCGRADE.CODGRADE
				 AND
					dbo.SDISCGRUPOEQ.CODDISC = SHISTDISCEQUIVCONCLUIDAS.CODDISC
	LEFT JOIN 
		SDISCIPLINA (NOLOCK)
			ON 
				dbo.SDISCIPLINA.CODDISC     = dbo.SEQUIVALENCIADISCGRADE.CODDISC 
			AND 
				dbo.SDISCIPLINA.CODCOLIGADA = dbo.SEQUIVALENCIADISCGRADE.CODCOLIGADA
				
	LEFT JOIN 
		STURMADISC  (NOLOCK)
			ON 
				STURMADISC.CODCOLIGADA = SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			AND 
				STURMADISC.IDTURMADISC = SHISTDISCEQUIVCONCLUIDAS.IDTURMADISC
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
					

			WHERE 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = 1 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.RA LIKE @RA	
					
	UNION 
	
/*EQUIVALENTES CONCLUÍDAS - GERAL***********************************************************************************/
		
		SELECT
			 ROW_NUMBER() OVER(PARTITION BY SDISCGRUPO_EQUIVALENTE.CODDISC ORDER BY NOTA DESC) AS IND
			,SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			,SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVCONCLUIDAS.RA
			,SHISTDISCEQUIVCONCLUIDAS.PLETIVO
			,SHISTDISCEQUIVCONCLUIDAS.CODDISC AS CODDISC_EQUIVALENTE
			,SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA AS DISC_EQUIVALENTE
			,SDISCGRUPO_EQUIVALENTE.CODDISC AS CODDISC_GRADE
			,SDISCIPLINA_EQUIVALENTE.NOME AS DISC_GRADE			
			,SHISTDISCEQUIVCONCLUIDAS.STATUS
			,SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS
			,SHISTDISCEQUIVCONCLUIDAS.NOTA
			,SHISTDISCEQUIVCONCLUIDAS.CH			
		    ,0 AS CODPERIODO
		    ,SHISTDISCEQUIVCONCLUIDAS.FALTAS
		    ,'Equivalentes Concluídas' AS TIPOHISTORICO
		    ,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
		    ,AULAS.TOT_AULAS
		    
		
			FROM 
		SHISTDISCEQUIVCONCLUIDAS (NOLOCK)/*47 Rows*/
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
			AND 
				SHABILITACAOFILIAL.ATIVO = 'S'
	/*LEFT*/ JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.GREQUIV  = SDISCGRUPOEQ.IDGRUPO 
	LEFT JOIN 
		dbo.SEQUIVALENCIA (NOLOCK)
			ON 
				SEQUIVALENCIA.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA
			AND 
				(
					SEQUIVALENCIA.IDGRUPOEQ= SDISCGRUPOEQ.IDGRUPO
				  OR 
					SEQUIVALENCIA.IDGRUPOEQEQUIV = SDISCGRUPOEQ.IDGRUPO
				)
					

	LEFT  JOIN   
			SDISCGRUPOEQ AS SDISCGRUPO_EQUIVALENTE (NOLOCK)
				ON 
					SDISCGRUPO_EQUIVALENTE.CODCOLIGADA=SEQUIVALENCIA.CODCOLIGADA
				AND 
					(
						SDISCGRUPO_EQUIVALENTE.IDGRUPO=SEQUIVALENCIA.IDGRUPOEQEQUIV
					OR 
						SDISCGRUPO_EQUIVALENTE.IDGRUPO = SEQUIVALENCIA.IDGRUPOEQ
					
					)

		LEFT  JOIN 
			SDISCIPLINA AS SDISCIPLINA_EQUIVALENTE (NOLOCK)
				ON 					 
					SDISCIPLINA_EQUIVALENTE.CODCOLIGADA = SDISCGRUPO_EQUIVALENTE.CODCOLIGADA
				AND 
					(
						SDISCIPLINA_EQUIVALENTE.CODDISC = SDISCGRUPO_EQUIVALENTE.CODDISC
					
					)
		LEFT JOIN 
		STURMADISC  (NOLOCK)
			ON 
				STURMADISC.CODCOLIGADA = SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			AND 
				STURMADISC.IDTURMADISC = SHISTDISCEQUIVCONCLUIDAS.IDTURMADISC
				
		LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA

				WHERE
						SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = 1
					AND 
						SHISTDISCEQUIVCONCLUIDAS.RA LIKE @RA
	UNION 
/*EQUIVALENTES CONCLUIDAS - HABILITACAOALUNO*************************************************************************/

		SELECT 
			 ROW_NUMBER() OVER(PARTITION BY SDISCGRUPO_EQUIVALENTE.CODDISC ORDER BY NOTA DESC) AS IND
			,SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			,SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVCONCLUIDAS.RA
			,SHISTDISCEQUIVCONCLUIDAS.PLETIVO
			,SHISTDISCEQUIVCONCLUIDAS.CODDISC AS CODDISC_EQUIVALENTE
			,SHISTDISCEQUIVCONCLUIDAS.DISCIPLINA AS DISC_EQUIVALENTE			
			,SDISCGRUPO_EQUIVALENTE.CODDISC AS CODDISC_GRADE
			,SDISCIPLINA_EQUIVALENTE.NOME AS DISC_GRADE
			,SHISTDISCEQUIVCONCLUIDAS.STATUS
			,SHISTDISCEQUIVCONCLUIDAS.NUMCREDITOS
			,SHISTDISCEQUIVCONCLUIDAS.NOTA
			,SHISTDISCEQUIVCONCLUIDAS.CH			
		    ,0 AS CODPERIODO
		    ,SHISTDISCEQUIVCONCLUIDAS.FALTAS
		    ,'Equivalentes Concluídas' AS TIPOHISTORICO
		    ,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
		    ,aulas.TOT_AULAS
		   

			FROM 
		SHISTDISCEQUIVCONCLUIDAS (NOLOCK)/*47 Rows*/
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	JOIN	
		SEQUIVALENCIAHABILITACAOALUNO (NOLOCK)
			ON 
				SEQUIVALENCIAHABILITACAOALUNO.CODCOLIGADA = SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.RA = SHISTDISCEQUIVCONCLUIDAS.RA
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.IDHABILITACAOFILIAL =  SHISTDISCEQUIVCONCLUIDAS.IDHABILITACAOFILIAL
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.IDGRUPOEQEQUIV = SHISTDISCEQUIVCONCLUIDAS.GREQUIV
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVCONCLUIDAS.GREQUIV  = SDISCGRUPOEQ.IDGRUPO
	 JOIN   
			SDISCGRUPOEQ AS SDISCGRUPO_EQUIVALENTE (NOLOCK)
				ON 
					SDISCGRUPO_EQUIVALENTE.CODCOLIGADA=dbo.SEQUIVALENCIAHABILITACAOALUNO.CODCOLIGADA
				AND 
					SDISCGRUPO_EQUIVALENTE.IDGRUPO=SEQUIVALENCIAHABILITACAOALUNO.IDGRUPOEQ

		 JOIN 
			SDISCIPLINA AS SDISCIPLINA_EQUIVALENTE (NOLOCK)
				ON 					 
					SDISCIPLINA_EQUIVALENTE.CODCOLIGADA = SDISCGRUPO_EQUIVALENTE.CODCOLIGADA
				AND 
					SDISCIPLINA_EQUIVALENTE.CODDISC = SDISCGRUPO_EQUIVALENTE.CODDISC
		
		JOIN 
		STURMADISC  (NOLOCK)
			ON 
				STURMADISC.CODCOLIGADA = SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA
			AND 
				STURMADISC.IDTURMADISC = SHISTDISCEQUIVCONCLUIDAS.IDTURMADISC
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA

					WHERE 						
						SHISTDISCEQUIVCONCLUIDAS.CODCOLIGADA = 1
					AND 
						SHISTDISCEQUIVCONCLUIDAS.RA LIKE @RA
UNION 
/*EQUIVALENTES EM CURSO - GRADE*************************************************************************/
SELECT 
			 ROW_NUMBER() OVER(PARTITION BY SEQUIVALENCIADISCGRADE.CODDISC ORDER BY NOTA) AS IND
			,SHISTDISCEQUIVEMCURSO.CODCOLIGADA
			,SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVEMCURSO.RA
			,SHISTDISCEQUIVEMCURSO.PLETIVO
			,SHISTDISCEQUIVEMCURSO.CODDISC AS CODDIS_EQUIVALENTE
			,SHISTDISCEQUIVEMCURSO.DISCIPLINA AS DISC_EQUIVALENTE
			,SEQUIVALENCIADISCGRADE.CODDISC AS CODDISC_GRADE
			,dbo.SDISCIPLINA.NOME AS DISC_GRADE
			,SHISTDISCEQUIVEMCURSO.STATUS
			,SHISTDISCEQUIVEMCURSO.NUMCREDITOS
			,SHISTDISCEQUIVEMCURSO.NOTA
			,SHISTDISCEQUIVEMCURSO.CH			
			,SEQUIVALENCIADISCGRADE.CODPERIODO AS CODPERIODO
			,SHISTDISCEQUIVEMCURSO.FALTAS
			,'Equivalentes em Curso' AS TIPOHISTORICO
			,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
			,aulas.TOT_AULAS
			
			
	FROM 
		SHISTDISCEQUIVEMCURSO (NOLOCK)/*47 Rows*/
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVEMCURSO.GREQUIV  = SDISCGRUPOEQ.IDGRUPO

	 JOIN 
		dbo.SEQUIVALENCIADISCGRADE (NOLOCK)
			ON 
				
					SDISCGRUPOEQ.CODCOLIGADA= SEQUIVALENCIADISCGRADE.CODCOLIGADA
				AND 
					SDISCGRUPOEQ.IDGRUPO =SEQUIVALENCIADISCGRADE.IDGRUPOEQEQUIV
				AND 
					SHABILITACAOFILIAL.CODGRADE = SEQUIVALENCIADISCGRADE.CODGRADE
				 AND
					dbo.SDISCGRUPOEQ.CODDISC = SHISTDISCEQUIVEMCURSO.CODDISC
	JOIN 
		SDISCIPLINA (NOLOCK)
			ON 
				dbo.SDISCIPLINA.CODDISC     = dbo.SEQUIVALENCIADISCGRADE.CODDISC 
			AND 
				dbo.SDISCIPLINA.CODCOLIGADA = dbo.SEQUIVALENCIADISCGRADE.CODCOLIGADA
				
	JOIN 
		SPLETIVO (NOLOCK)
			ON 
				SPLETIVO.CODCOLIGADA = SHISTDISCEQUIVEMCURSO.CODCOLIGADA
			AND 
				SPLETIVO.CODPERLET = SHISTDISCEQUIVEMCURSO.PLETIVO
			AND 
				SPLETIVO.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				SPLETIVO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
	
	JOIN 
		STURMADISC (NOLOCK)
			ON 
				SHISTDISCEQUIVEMCURSO.CODDISC = STURMADISC.CODDISC
			AND 
				SPLETIVO.IDPERLET = STURMADISC.IDPERLET	
			AND 
				STURMADISC.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				STURMADISC.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
			
	JOIN 
		SMATRICULA (NOLOCK)
			ON 
				SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC
			AND 
				SMATRICULA.IDPERLET = SPLETIVO.IDPERLET
			AND 
				SMATRICULA.RA = SHISTDISCEQUIVEMCURSO.RA
			
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA					

			WHERE 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = 1
			AND 
				SHISTDISCEQUIVEMCURSO.RA LIKE @RA	
					
	UNION 
/*EQUIVALENTES EM CURSO - GERAL*************************************************************************/

		
		SELECT
			 ROW_NUMBER() OVER( PARTITION BY SDISCGRUPO_EQUIVALENTE.CODDISC ORDER BY NOTA) AS IND
			,SHISTDISCEQUIVEMCURSO.CODCOLIGADA
			,SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVEMCURSO.RA
			,SHISTDISCEQUIVEMCURSO.PLETIVO
			,SHISTDISCEQUIVEMCURSO.CODDISC AS CODDISC_EQUIVALENTE
			,SHISTDISCEQUIVEMCURSO.DISCIPLINA AS DISC_EQUIVALENTE
			,SDISCGRUPO_EQUIVALENTE.CODDISC AS CODDISC_GRADE
			,SDISCIPLINA_EQUIVALENTE.NOME AS DISC_GRADE			
			,SHISTDISCEQUIVEMCURSO.STATUS
			,SHISTDISCEQUIVEMCURSO.NUMCREDITOS
			,SHISTDISCEQUIVEMCURSO.NOTA
			,SHISTDISCEQUIVEMCURSO.CH			
		   ,0 AS CODPERIODO
		   ,SHISTDISCEQUIVEMCURSO.FALTAS
		   ,'Equivalentes em Curso' AS TIPOHISTORICO
		   ,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
		   ,aulas.TOT_AULAS
		   
		   
		
			FROM 
		SHISTDISCEQUIVEMCURSO (NOLOCK)/*47 Rows*/
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
			AND 
				SHABILITACAOFILIAL.ATIVO = 'S'
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVEMCURSO.GREQUIV  = SDISCGRUPOEQ.IDGRUPO 
	JOIN 
		dbo.SEQUIVALENCIA (NOLOCK)
			ON 
				SEQUIVALENCIA.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA
			AND 
				SEQUIVALENCIA.IDGRUPOEQ= SDISCGRUPOEQ.IDGRUPO

	 JOIN   
			SDISCGRUPOEQ AS SDISCGRUPO_EQUIVALENTE (NOLOCK)
				ON 
					SDISCGRUPO_EQUIVALENTE.CODCOLIGADA=dbo.SEQUIVALENCIA.CODCOLIGADA
				AND 
					SDISCGRUPO_EQUIVALENTE.IDGRUPO=SEQUIVALENCIA.IDGRUPOEQEQUIV

		 JOIN 
			SDISCIPLINA AS SDISCIPLINA_EQUIVALENTE (NOLOCK)
				ON 					 
					SDISCIPLINA_EQUIVALENTE.CODCOLIGADA = SDISCGRUPO_EQUIVALENTE.CODCOLIGADA
				AND 
					SDISCIPLINA_EQUIVALENTE.CODDISC = SDISCGRUPO_EQUIVALENTE.CODDISC
					
	JOIN 
		SPLETIVO (NOLOCK)
			ON 
				SPLETIVO.CODCOLIGADA  = SDISCIPLINA_EQUIVALENTE.CODCOLIGADA
			AND 
				SPLETIVO.CODPERLET    = SHISTDISCEQUIVEMCURSO.PLETIVO
			AND 
				SPLETIVO.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				SPLETIVO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
	
	  JOIN 
		STURMADISC (NOLOCK)
			ON 
				SHISTDISCEQUIVEMCURSO.CODDISC = STURMADISC.CODDISC
			AND 
				SPLETIVO.IDPERLET = STURMADISC.IDPERLET	
			AND 
				STURMADISC.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				STURMADISC.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO	
				
	LEFT JOIN			
	(
	SELECT 
		COUNT (*)TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	)AULAS
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
			
	 JOIN 
		SMATRICULA (NOLOCK)
			ON 
				SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC
			AND 
				SMATRICULA.IDPERLET = SPLETIVO.IDPERLET
			AND 
				SMATRICULA.RA = SHISTDISCEQUIVEMCURSO.RA
			
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA
					
		WHERE
						SHISTDISCEQUIVEMCURSO.CODCOLIGADA = 1
					AND 
						SHISTDISCEQUIVEMCURSO.RA LIKE @RA
						
/*EQUIVALENTES EM CURSO - HABILITACAOALUNO*************************************************************************/

	UNION 
		SELECT 
			 ROW_NUMBER() OVER (PARTITION BY SDISCGRUPO_EQUIVALENTE.CODDISC ORDER BY NOTA) AS IND
			,SHISTDISCEQUIVEMCURSO.CODCOLIGADA
			,SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL
			,SHISTDISCEQUIVEMCURSO.RA
			,SHISTDISCEQUIVEMCURSO.PLETIVO
			,SHISTDISCEQUIVEMCURSO.CODDISC AS CODDISC_EQUIVALENTE
			,SHISTDISCEQUIVEMCURSO.DISCIPLINA AS DISC_EQUIVALENTE			
			,SDISCGRUPO_EQUIVALENTE.CODDISC AS CODDISC_GRADE
			,SDISCIPLINA_EQUIVALENTE.NOME AS DISC_GRADE
			,SHISTDISCEQUIVEMCURSO.STATUS
			,SHISTDISCEQUIVEMCURSO.NUMCREDITOS
			,SHISTDISCEQUIVEMCURSO.NOTA
			,SHISTDISCEQUIVEMCURSO.CH			
		    ,0 AS CODPERIODO
		    ,SHISTDISCEQUIVEMCURSO.FALTAS
		    ,'Equivalentes em Curso' AS TIPOHISTORICO
		    ,dbo.InitCap (PPESSOA.NOME) + ' - ' + dbo.InitCap (stitulacao.nome) as ProfTit
		    ,AULAS.TOT_AULAS
		   

			FROM 
		SHISTDISCEQUIVEMCURSO (NOLOCK)/*47 Rows*/
	JOIN 
		SHABILITACAOFILIAL (NOLOCK) 
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
	JOIN	
		SEQUIVALENCIAHABILITACAOALUNO (NOLOCK)
			ON 
				SEQUIVALENCIAHABILITACAOALUNO.CODCOLIGADA = SHISTDISCEQUIVEMCURSO.CODCOLIGADA
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.RA = SHISTDISCEQUIVEMCURSO.RA
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.IDHABILITACAOFILIAL =  SHISTDISCEQUIVEMCURSO.IDHABILITACAOFILIAL
			AND 
				SEQUIVALENCIAHABILITACAOALUNO.IDGRUPOEQEQUIV = SHISTDISCEQUIVEMCURSO.GREQUIV
	JOIN 
		SDISCGRUPOEQ (NOLOCK) /*49 Rows*/
			ON 
				SHISTDISCEQUIVEMCURSO.CODCOLIGADA = SDISCGRUPOEQ.CODCOLIGADA 
			AND 
				SHISTDISCEQUIVEMCURSO.GREQUIV  = SDISCGRUPOEQ.IDGRUPO
	 LEFT JOIN   
			SDISCGRUPOEQ AS SDISCGRUPO_EQUIVALENTE (NOLOCK)
				ON 
					SDISCGRUPO_EQUIVALENTE.CODCOLIGADA=dbo.SEQUIVALENCIAHABILITACAOALUNO.CODCOLIGADA
				AND 
					SDISCGRUPO_EQUIVALENTE.IDGRUPO=SEQUIVALENCIAHABILITACAOALUNO.IDGRUPOEQ

	LEFT	 JOIN 
			SDISCIPLINA AS SDISCIPLINA_EQUIVALENTE (NOLOCK)
				ON 					 
					SDISCIPLINA_EQUIVALENTE.CODCOLIGADA = SDISCGRUPO_EQUIVALENTE.CODCOLIGADA
				AND 
					SDISCIPLINA_EQUIVALENTE.CODDISC = SDISCGRUPO_EQUIVALENTE.CODDISC
					
	JOIN 
		SPLETIVO (NOLOCK)
			ON 
				SPLETIVO.CODCOLIGADA  = SDISCIPLINA_EQUIVALENTE.CODCOLIGADA
			AND 
				SPLETIVO.CODPERLET    = SHISTDISCEQUIVEMCURSO.PLETIVO
			AND 
				SPLETIVO.CODFILIAL    = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				SPLETIVO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
	
	LEFT   JOIN 
		STURMADISC (NOLOCK)
			ON 
				SHISTDISCEQUIVEMCURSO.CODDISC = STURMADISC.CODDISC
			AND 
				SPLETIVO.IDPERLET = STURMADISC.IDPERLET	
			AND 
				STURMADISC.CODFILIAL = SHABILITACAOFILIAL.CODFILIAL 
			AND 
				STURMADISC.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO	
	LEFT JOIN			
	(
	SELECT 
		COUNT (*) TOT_AULAS, IDTURMADISC, CODCOLIGADA  
			FROM SPLANOAULA 
				GROUP BY IDTURMADISC, CODCOLIGADA
	) AULAS 
		ON 
			AULAS.CODCOLIGADA = STURMADISC.CODCOLIGADA
		AND 
			AULAS.IDTURMADISC = STURMADISC.IDTURMADISC
			
	  JOIN 
		SMATRICULA (NOLOCK)
			ON 
				SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC
			AND 
				SMATRICULA.IDPERLET = SPLETIVO.IDPERLET
			AND 
				SMATRICULA.RA = SHISTDISCEQUIVEMCURSO.RA
				
	LEFT JOIN 
		SPROFESSORTURMA (NOLOCK)
			ON 
				SPROFESSORTURMA.CODCOLIGADA = STURMADISC.CODCOLIGADA
			AND 
				SPROFESSORTURMA.IDTURMADISC = STURMADISC.IDTURMADISC
				
	LEFT JOIN 
		SPROFESSOR (NOLOCK) 
			ON
				SPROFESSOR.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA
			AND 
				SPROFESSOR.CODPROF = SPROFESSORTURMA.CODPROF
	LEFT JOIN 
		STITULACAO (NOLOCK)
			ON 
				STITULACAO.CODTITULACAO = SPROFESSOR.CODTITULACAO
	LEFT JOIN 
		PPESSOA (NOLOCK)
			ON 
				PPESSOA.CODIGO = SPROFESSOR.CODPESSOA

					WHERE 						
						SHISTDISCEQUIVEMCURSO.CODCOLIGADA = 1
					AND 
						SHISTDISCEQUIVEMCURSO.RA LIKE @RA
				

)ZEQUIVHISTORICO
)ZEQUIVHISTORICO
	ON 
		ZEQUIVHISTORICO.CODCOLIGADA = SDISCIPLINA.CODCOLIGADA
	AND 
		ZEQUIVHISTORICO.CODDISC_GRADE = SDISCGRADE.CODDISC	
	AND 
		ZEQUIVHISTORICO.RA = 	SHABILITACAOALUNO.RA
		
	AND ZEQUIVHISTORICO.IND = 1		
		
		
		
/**********************************APROVAITAMENTO DE ESTUDOS***************************************/

LEFT JOIN 
(

SELECT 
	SHISTDISCFAC.CODCOLIGADA
	,SHISTDISCFAC.RA
	,'' AS CODGRADE
	,SHISTDISCFAC.IDHABILITACAOFILIAL
	,SDISCGRADE.CODPERIODO
	,SDISCIPLINA.NOME AS DISCIPLINAS
	,'' AS DISCEQQUIV
	,'' AS DISCIPLINA
	,'' AS NOMEEQUIVALENTE
	,SPLETIVO.CODPERLET
	,SHISTDISCFAC.CARGAHORARIA
	,SHISTDISCFAC.FALTAS	
	,100 PERCPRESENCA
	,0.001 MYASS
	,CAST (SHISTDISCFAC.NOTA AS NUMERIC (10,2)) AS NOTA
	,SSTATUS.DESCRICAO AS STATUS
	,SSTATUS.CODEXTERNO
	,'' AS PROFTIT
	
	
	FROM 
		SHISTDISCFAC (NOLOCK)
	 JOIN 
		SSTATUS (NOLOCK)
			ON
				SHISTDISCFAC.CODCOLIGADA = SSTATUS.CODCOLIGADA
			AND 
				SHISTDISCFAC.CODSTATUS = SSTATUS.CODSTATUS
	JOIN 
		SHABILITACAOFILIAL (NOLOCK)
			ON 
				SHABILITACAOFILIAL.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND 
				SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SHISTDISCFAC.IDHABILITACAOFILIAL
				
	JOIN 
		SDISCGRADE (NOLOCK)
			ON 
				SDISCGRADE.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA
			AND 
				SDISCGRADE.CODCURSO=SHABILITACAOFILIAL.CODCURSO
			AND
				SDISCGRADE.CODGRADE=SHABILITACAOFILIAL.CODGRADE
			AND 
				SDISCGRADE.CODHABILITACAO=SHABILITACAOFILIAL.CODHABILITACAO
			AND 
				SDISCGRADE.CODDISC = SHISTDISCFAC.CODDISC
	JOIN 
		SDISCIPLINA (NOLOCK)
			ON 
				SDISCIPLINA.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND	
				SDISCIPLINA.CODDISC = SHISTDISCFAC.CODDISC
				
	JOIN 
		SPLETIVO (NOLOCK)
			ON 
				SPLETIVO.CODCOLIGADA = SHISTDISCFAC.CODCOLIGADA
			AND 
				SPLETIVO.IDPERLET = SHISTDISCFAC.IDPERLET 
				
				
			WHERE 
				SHISTDISCFAC.CODCOLIGADA = 1
			AND 
				SHISTDISCFAC.RA = @RA


)ZAPROVEITA
			
				ON 					
					ZAPROVEITA.CODCOLIGADA = SDISCGRADE.CODCOLIGADA
				AND 
					ZAPROVEITA.CODPERIODO = SDISCGRADE.CODPERIODO
				AND 
					ZAPROVEITA.DISCIPLINAS = SDISCIPLINA.NOME
				AND 
					ZAPROVEITA.RA = SHABILITACAOALUNO.RA
			

		
					
				
			WHERE 
				SHABILITACAOFILIAL.CODCOLIGADA = 1
			AND 
				SHABILITACAOALUNO.RA = @RA
			AND 
				HABMATRICULA.IDHABILITACAOFILIAL =   1089    
			and 
				SDISCGRADE.CODPERIODO= 3
			
					
					--ORDER BY 
					--	SDISCGRADE.CODPERIODO, SDISCIPLINA.NOME



					GROUP BY SDISCGRADE.CODDISC, DISCAPROVADAS.ProfTit		