SELECT  DISTINCT
       C.CODCURSO
      ,C.NOME AS CURSO
	  ,HAB.IDHABILITACAOFILIAL
	  ,HAB.RA
	  ,DG.CODGRADE
	  ,D.CODDISC
	  ,D.NOME AS DISCIPLINA
	  ,D.CH
	  ,D.NUMCREDITOS
	  ,DG.TIPODISC AS DGTIPOD
	  ,MA.CODSTATUSRES
	  ,ST.CODSTATUS
	  ,ST.DESCRICAO AS STATUS

 FROM SHABILITACAOALUNO AS HAB
 JOIN SHABILITACAOFILIAL AS SHF ON SHF.IDHABILITACAOFILIAL = HAB.IDHABILITACAOFILIAL
 JOIN SDISCGRADE AS DG ON DG.CODGRADE = SHF.CODGRADE
 JOIN SDISCIPLINA AS D ON D.CODDISC = DG.CODDISC
 JOIN SCURSO AS C ON C.CODCURSO = SHF.CODCURSO
 JOIN SMATRICULA AS MA ON MA.RA = HAB.RA AND MA.IDTURMADISC = SHF.ID --AND MA.
 LEFT JOIN SSTATUS AS ST ON ST.CODSTATUS = MA.CODSTATUSRES

WHERE  DG.TIPODISC IN ('E','O') AND HAB.RA = '00001554' --AND D.CODDISC = 'EDUCHISTBRASIL'




--SELECT * FROM SMATRICULA WHERE RA = '00001554'

--  SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'STURMADISC' 

--SELECT * FROM SHABILITACAOALUNO WHERE RA='00001554'




--SELECT * FROM SHABILITACAOFILIAL