
--BEGIN TRAN  --***** NÃO UTILIZAR O INSERT, POIS BLOQUEIA POR SER UMA TABELA PROTEGIDA  G

--INSERT INTO GUSRPERFIL (CODCOLIGADA,CODUSUARIO,CODSISTEMA,CODPERFIL,INDICE) --CODCOLIGADA,CODUSUARIO,CODSISTEMA,CODPERFIL,INDICE,CONTROLE


SELECT CODCOLIGADA,CODUSUARIO,'S','05_ALUNO',0 FROM

(

	SELECT DISTINCT
	 M.CODCOLIGADA
	,M.CODTURMA
	,M.RA
	,SP.CODPERLET
	,P.CODUSUARIO
	,GP.CODSISTEMA
	,GP.CODPERFIL
	,GP.INDICE
	,GP.CONTROLE

	 FROM SMATRICPL AS M

	JOIN SPLETIVO AS SP ON SP.IDPERLET = M.IDPERLET
	--LEFT JOIN SCONTRATO AS C ON C.IDHABILITACAOFILIAL = M.IDHABILITACAOFILIAL AND C.RA = M.RA AND C.IDPERLET = M.IDPERLET
	JOIN SALUNO AL ON AL.RA = M.RA
	JOIN PPESSOA AS P ON P.CODIGO = AL.CODPESSOA
	LEFT JOIN GUSRPERFIL AS GP ON GP.CODUSUARIO = P.CODUSUARIO AND CODPERFIL = '05_ALUNO' AND CODSISTEMA = 'S'

	WHERE M.CODTURMA LIKE 'EF1%' AND SP.CODPERLET = '2021' AND M.CODFILIAL = 5 AND GP.CONTROLE IS NULL

	) TAB


	--COMMIT