
--BEGIN TRAN

--INSERT INTO STIPOATENDIMENTO (CODCOLIGADA,CODTIPOATENDIMENTO,VERIFICAINADIMPLENCIA,CODSERVICO,APLICACAO,CODFORMULA,AGENDALANCAMENTO,CODTIPOCURSO,ACAOTEMPLATE)

SELECT AT.CODCOLIGADA,AT.CODTIPOATENDIMENTO,AT.VERIFICAINADIMPLENCIA,S2.CODSERVICO,APLICACAO,CODFORMULA,AGENDALANCAMENTO,11 AS CODTIPOCURSO,ACAOTEMPLATE


 FROM STIPOATENDIMENTO AS AT

LEFT JOIN SSERVICO AS S1 ON S1.CODSERVICO = AT.CODSERVICO
LEFT JOIN SSERVICO AS S2 ON S2.NOME = S1.NOME AND S2.CODTIPOCURSO = 11

WHERE AT.CODTIPOCURSO = 4 


--COMMIT
--ROLLBACK