/* ALUNOS NOVOS DO CONTEXTO 10 SEM ACESSO AO PORTAL, INSERTIR USUÁRIO*/

/*BEGIN TRAN  -- FILIAL 10

INSERT INTO SUSUARIOFILIAL (CODCOLIGADA,CODTIPOCURSO,CODFILIAL,CODUSUARIO,ACESSO)

SELECT DISTINCT 1,10,18,PPESSOA.CODUSUARIO,1 FROM SCONTRATO 
JOIN SPLETIVO ON SPLETIVO.IDPERLET = SCONTRATO.IDPERLET
JOIN SALUNO ON SALUNO.RA = SCONTRATO.RA
JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA

WHERE SCONTRATO.CODTIPOCURSO = 10 AND CODPERLET = '2020/2' AND  NOT EXISTS (SELECT CODUSUARIO FROM SUSUARIOFILIAL WHERE CODTIPOCURSO=10 AND CODUSUARIO = PPESSOA.CODUSUARIO) AND SCONTRATO.STATUS = 'N'

COMMIT
*/

--  FILIAL 5 ALUNOS NOVOS VINDOS DA FILIAL 19


	--BEGIN TRAN

	--INSERT INTO SUSUARIOFILIAL (CODCOLIGADA,CODTIPOCURSO,CODFILIAL,CODUSUARIO,ACESSO)

	SELECT DISTINCT SC.CODCOLIGADA,SC.CODTIPOCURSO,SC.CODFILIAL,PPESSOA.CODUSUARIO,U.ACESSO

	FROM SCONTRATO SC
	JOIN SPLETIVO ON SPLETIVO.IDPERLET = SC.IDPERLET
	JOIN SALUNO ON SALUNO.RA = SC.RA
	JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA
	JOIN SUSUARIOFILIAL AS U ON U.CODUSUARIO = PPESSOA.CODUSUARIO

	WHERE SC.CODFILIAL = 5 AND SC.CODTIPOCURSO = 1 AND CODPERLET = '2021' 
	AND  PPESSOA.CODUSUARIO NOT IN (SELECT CODUSUARIO FROM SUSUARIOFILIAL WHERE CODFILIAL = 5 AND CODUSUARIO =  PPESSOA.CODUSUARIO) 
	AND SC.STATUS = 'N'

	--COMMIT
