SET LANGUAGE BRAZILIAN


SELECT CAST(SUM(VALORBAIXADO) AS NUMERIC(15,2)) AS SOMA_VALOR,
dbo.fn_numero_por_extenso(SUM(FLAN.VALORBAIXADO)) AS VALOR_EXTENSO


FROM FLAN (NOLOCK)
LEFT JOIN SLAN (NOLOCK)
ON SLAN.IDLAN = FLAN.IDLAN
LEFT JOIN SPARCELA (NOLOCK)
ON SLAN.IDPARCELA = SPARCELA.IDPARCELA
LEFT JOIN SSERVICO (NOLOCK)
ON SPARCELA.CODSERVICO = SSERVICO.CODSERVICO
LEFT JOIN SALUNO (NOLOCK)
ON SALUNO.RA = SPARCELA.RA
/*AND SALUNO.CODCFO = FLAN.CODCFO*/
WHERE SPARCELA.RA = '00000837' --:RA_ALUNO
AND FLAN.DATABAIXA >=  '01/01/2019'  /*'01/01/2018'	:DATA_INICIAL */
AND FLAN.DATABAIXA <=  '31/12/2019' /*'31/12/2018'  :DATA_FINAL*/
--AND VALORBAIXADO > '0'
--AND FLAN.STATUSLAN NOT IN (3,5)
--AND FLAN.CODTDO = '1.01.1'
AND SSERVICO.NOME LIKE 'MENS%'
AND FLAN.CODFILIAL = 5
AND FLAN.CODCFO = '000982' --:CLIENTE

--ORDER BY DATAVENCIMENTO


--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPARCELA' AND CHILDTABLE = 'SLAN'


--SELECT * FROM SPARCELA WHERE RA='00000611' AND DTCOMPETENCIA LIKE '%2019%'


--SELECT * FROM SLAN WHERE IDPARCELA= 1766128


--SELECT * FROM FLAN WHERE IDLAN= 1534308


--SELECT * FROM SSERVICO WHERE CODSERVICO = 1