-- PROJETO JOB ALTERAR DATA 
-- 1-MUDAR APENAS PRIMEIRA PARCELA
-- 2-FUNCIONAR ATÉ DIA 20/12/2019  

SET LANGUAGE BRAZILIAN

--SELECT * FROM SPLANOPGTO WHERE CODPLANOPGTO = 'F20/1C_06'
DECLARE @DIA AS DATETIME

SET @DIA = (GETDATE() + 3) ;
  BEGIN TRAN

  UPDATE SPARCPLANO SET DTVENCIMENTO = (CASE  DATEPART(DW,@DIA) WHEN 1 THEN DATEADD(DD,1,@DIA)
									   WHEN 7 THEN DATEADD(DD,2,@DIA)
									   ELSE @DIA END)

									   FROM SPARCPLANO AS A

									   WHERE CODPLANOPGTO = 'F20/1C_06' AND PARCELA = 1 AND EXISTS(

		SELECT 

		 PGO.CODPLANOPGTO
		,PACP.CODSERVICO
		,PACP.PARCELA
		,PACP.DTVENCIMENTO

		FROM SPLANOPGTO (NOLOCK) AS PGO

		JOIN SPARCPLANO (NOLOCK) AS PACP ON PACP.CODPLANOPGTO = PGO.CODPLANOPGTO AND PACP.IDPERLET = PGO.IDPERLET AND PACP.PARCELA = 1

WHERE PGO.CODPLANOPGTO = 'F20/1C_06' AND A.CODPLANOPGTO = PGO.CODPLANOPGTO AND A.IDPERLET = PGO.IDPERLET

) 
--COMMIT
--ROLLBACK