SET LANGUAGE PORTUGUÍS

SELECT FLANBAIXA.IDLAN,
FLANBAIXA.CODFILIAL,
CONVERT(VARCHAR(10),FLANBAIXA.DATABAIXA,103) AS DATABAIXA,
CONVERT(VARCHAR(10),FLANBAIXA.DATAVENCIMENTOLANCAMENTO,103) AS DATAVENCIMENTOLANCAMENTO,
CONVERT(MONEY,FLANBAIXA.VALORBAIXA) AS VALORBAIXA,
CONVERT(MONEY,FLANBAIXA.VALORORIGINAL) AS VALORORIGINAL,
CONVERT(MONEY,FLANBAIXA.VALOROP3) AS DESC_PONT,
CONVERT(MONEY,FLANBAIXA.VALOROP6) AS APURA_MAIOR,
SPARCELA.PARCELA,
FLAN.STATUSLAN,
FLAN.HISTORICO


FROM FLANBAIXA 


 LEFT JOIN FLAN ON FLAN.IDLAN = FLANBAIXA.IDLAN
 LEFT JOIN SLAN ON SLAN.IDLAN = FLANBAIXA.IDLAN
 LEFT JOIN SPARCELA ON SPARCELA.IDPARCELA = SLAN.IDPARCELA
 LEFT JOIN SPLETIVO ON SPLETIVO.IDPERLET = SPARCELA.IDPERLET


WHERE FLANBAIXA.CODFILIAL = 5 AND FLAN.STATUSLAN =1  AND FLANBAIXA.DATABAIXA < = FLANBAIXA.DATAVENCIMENTOLANCAMENTO 
AND CODPERLET = '2019' AND SPARCELA.PARCELA = 2 AND FLANBAIXA.VALOROP6 > 0
