SELECT * FROM FLAN WHERE IDLAN = 545328


SELECT * FROM SBOLSAALUNO WHERE RA='801806'


SELECT * FROM SPARCELA WHERE CODCONTRATO=54550

SELECT * FROM SBOLSALAN WHERE IDLAN=545328

SELECT * FROM GCONSSQL WHERE CODSENTENCA='STATUSLAN'

SELECT flan.codfilial, STATUSLAN FROM FLAN WHERE IDLAN = :FRM_0019