SET DATEFORMAT DMY

SELECT 
LANACORDO.CODCOLIGADA, 
LANACORDO.IDLAN,
SERVICOACORDO.NOME, 
SPARCELAACORDO.PARCELA, 
LANACORDO.VALORORIGINAL VALORORIGINAL, 
CONVERT(VARCHAR(10),LANACORDO.DATAVENCIMENTO,103) VENCIMENTO,
LANACORDO.CODFILIAL

FROM FACORDOREL


LEFT JOIN FLAN LANACORDO ON LANACORDO.IDLAN = FACORDOREL.IDLAN
LEFT JOIN SLAN SLANACORDO ON LANACORDO.IDLAN = SLANACORDO.IDLAN
LEFT JOIN SPARCELA SPARCELAACORDO ON SPARCELAACORDO.IDPARCELA = SLANACORDO.IDPARCELA
LEFT JOIN SSERVICO SERVICOACORDO ON SERVICOACORDO.CODSERVICO = SPARCELAACORDO.CODSERVICO
LEFT JOIN FACORDO ON FACORDOREL.IDACORDO = FACORDO.IDACORDO
LEFT JOIN FCFO ON FACORDO.CODCFO = FCFO.CODCFO

WHERE
FACORDO.IDACORDO = :IDACORDO
AND SPARCELAACORDO.RA = :RA


ORDER BY SERVICOACORDO.NOME, SPARCELAACORDO.PARCELA