--SELECT * FROM FCFO WHERE CGCCFO = '53.416.921/0021-40'
--SELECT IDNAT, * FROM TMOV WHERE LEN(IDNAT)>=6


--SELECT * FROM GFILIAL 



SELECT IDNAT,* FROM TMOV WHERE NUMEROMOV = '00208863' --IDNAT IS NOT NULL AND LEN(IDNAT)>=6


SELECT * FROM GCAMPOS WHERE COLUNA LIKE 'CODIGOSERVICO'

SELECT * FROM DITEM WHERE CODIGOSERVICO IS NOT NULL


SELECT * FROM GCAMPOS WHERE TABELA = 'TMOV'

SELECT * FROM TMOVFISCAL

SELECT * FROM FTDO

/*
DITEM
DITEMHISTORICO
DLAF
DLAFHISTORICO
DTRBMUNICIPIOPRD
TITMCNT
TITMCNTMEDICAO
TITMMOV
TMOV
TNFE
*/