SET LANGUAGE PORTUGUÍS
SET DATEFORMAT DMY

SELECT A.CODFILIAL,A.RA, A.CODTURMA, A.IDHABILITACAOFILIAL ,C.DESCRICAO STATUS, FORMAT(DTMATRICULA,'dd/MM/yyyy hh:mm:ss') DTMATRICULA,B.CODPERLET FROM SMATRICPL (NOLOCK) A
LEFT JOIN SPLETIVO (NOLOCK) B ON A.IDPERLET = B.IDPERLET
LEFT JOIN SSTATUS (NOLOCK) C ON C.CODSTATUS = A.CODSTATUS
WHERE B.CODPERLET = '2018'

ORDER BY CODFILIAL,CODTURMA,C.DESCRICAO