/*
As notas das provas ficaram no turma de origem e na turma destino ficara apenas as notas das etapas que informar. 

O processo somente se aplica quando tentam realizar a transferência de turma e algum valor de nota limite no destino e maior que na origem.
*/

--SELECT * FROM STURMADISC WHERE IDTURMADISC = 62822
/*
SELECT CODTURMA
,*
FROM
SMATRICPL
WHERE CODCOLIGADA= 1 AND RA = '00014303' AND IDPERLET = 265 AND CODTURMA LIKE 'E%'
*/
/*
SELECT
*
 FROM
SMATRICULA
WHERE CODCOLIGADA= 1 AND RA = '00014303' AND IDPERLET = 265 AND IDHABILITACAOFILIAL = 1471
*/

--SELECT * FROM STURMADISC WHERE CODTURMA = 'EF6VC' AND IDPERLET = 265
--SELECT * FROM STURMADISC WHERE CODTURMA = 'EF6MC' AND IDPERLET = 265

--SELECT * FROM SETAPAS WHERE IDTURMADISC = 55825
--SELECT * FROM SETAPAS(NOLOCK) WHERE IDTURMADISC = 55569 AND CODETAPA IN (19,29)

--SELECT * FROM SPROVAS WHERE IDTURMADISC = 55569
--SELECT * FROM SPROVAS WHERE IDTURMADISC = 55825

--SELECT * FROM SFREQUENCIA(NOLOCK) WHERE RA = '00014303' AND DATA>='2019-04-01'


INSERT
INTO
SNOTAETAPA (CODCOLIGADA, CODETAPA,TIPOETAPA,  IDTURMADISC, NOTAFALTA, RA, RECMODIFIEDBY, RECMODIFIEDON)



SELECT
 SNOTAETAPA.CODCOLIGADA
, SNOTAETAPA.CODETAPA
, SNOTAETAPA.TIPOETAPA
, Z.IDTURMADISC
--, SNOTAETAPA.IDTURMADISC
, SNOTAETAPA.NOTAFALTA
, SNOTAETAPA.RA
, 'dennyson.silva' as criador
, GETDATE() as criatura
from
SNOTAETAPA (NOLOCK)
JOIN
STURMADISC (NOLOCK)
ON
SNOTAETAPA.CODCOLIGADA = STURMADISC.CODCOLIGADA
AND
SNOTAETAPA.IDTURMADISC = STURMADISC.IDTURMADISC

LEFT JOIN
(
SELECT
SMATRICULA.CODCOLIGADA, SMATRICULA.RA, SMATRICULA.IDHABILITACAOFILIAL, SMATRICULA.IDTURMADISC,
SMATRICULA.IDPERLET , STURMADISC.CODDISC
FROM
SMATRICULA(NOLOCK)
JOIN
STURMADISC (NOLOCK)
ON
SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
AND
SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC

)Z
ON
Z.CODCOLIGADA = SNOTAETAPA.CODCOLIGADA
AND
Z.RA = SNOTAETAPA.RA
AND
Z.IDPERLET = STURMADISC.IDPERLET

AND
Z.CODDISC = STURMADISC.CODDISC
AND
Z.IDTURMADISC <>SNOTAETAPA.IDTURMADISC



WHERE SNOTAETAPA.IDTURMADISC IN (

55407





 )
AND
SNOTAETAPA.RA = '00011867'
AND
SNOTAETAPA.CODETAPA IN (10,12,19)
AND
SNOTAETAPA.TIPOETAPA = 'N'


--SELECT
-- *
-- --INTO YSNOTAS
-- from
-- SNOTAETAPA
-- WHERE IDTURMADISC = 55825

---- where IDTURMADISC in (
---- 55569
---- ,55570
---- ,55571
---- ,55572
---- ,55573
---- ,55574
---- ,55575
---- ,55576
---- ,55577
---- ,55578
---- ,55579
----  )
-- and
-- RA = '00014303'



ORDER BY SNOTAETAPA.CODETAPA, SNOTAETAPA.IDTURMADISC

--SELECT * FROM SETAPAS WHERE IDTURMADISC =
--62326