SELECT * FROM PPESSOA WHERE NACIONALIDADE = 36--CODUSUARIO = '009438'

--RA-009438
--ATO OFICIAL DO CURSO	ATO_CURSO	Resolução nº 6420/14 - DOE de 17/12/2014
--ATO OFICIAL DO ESTABELECIMENTO	ATO_ESTAB	Resolução nº 1079/14 - DOE de 28/03/2014
--SÍNTESE DO SISTEMA DE AVALIAÇÃO	SINT	Para aprovação exige-se média igual ou superior a 6,0 (seis vírgula zero) e frequência mínima igual ou superior a 75%.
--DATA	DATA	07/12/2018
------------------------------------------------------------------------------	
	SELECT
SALUNO.RA,
ALUNO$.NOME,
CASE WHEN ALUNO$.SEXO = 'F' THEN 'FEMININO' ELSE 'MASCULINO' END AS SEXO, 
CONVERT(VARCHAR, ALUNO$.DTNASCIMENTO, 103) as DTNASC, 
UPPER (ALUNO$.NATURALIDADE)+'/'+ALUNO$.ESTADONATAL AS CIDADE_NATAL, 
ALUNO$.CARTIDENTIDADE+'/'+ALUNO$.UFCARTIDENT AS RG,	
PCODNACAO.DESCRICAO, 
CASE WHEN PAI$.NOME IS NULL
	 THEN MAE$.NOME
	 ELSE PAI$.NOME+' e '+MAE$.NOME 
END AS 'FILIACAO',
 CASE ALUNO$.NACIONALIDADE WHEN 10 THEN 'BRASIL'
			WHEN	21	THEN	'ARGENTINA'
			WHEN	22	THEN	'BOLÍVIA'
			WHEN	23	THEN	'CHILE'
			WHEN	24	THEN	'PARAGUAI'
			WHEN	25	THEN	'URUGUAI'
			WHEN	30	THEN	'ALEMANHA'
			WHEN	31	THEN	'BÉLGICA'
			WHEN	32	THEN	'GRÃ-BRETANHA'
			WHEN	34	THEN	'CANADÁ'
			WHEN	35	THEN	'ESPANHA'
			WHEN	14	THEN	'ESTADOS UNIDOS'
			WHEN	37	THEN	'FRANÇA'
			WHEN	38	THEN	'SUIÇA'
			WHEN	39	THEN	'ITÁLIA'
			WHEN	41	THEN	'JAPÃO'
			WHEN	42	THEN	'CHINA'
			WHEN	43	THEN	'COREA DO SUL'
			WHEN	45	THEN	'PORTUGAL'
	   END AS PAÍS

FROM SALUNO (NOLOCK)
INNER JOIN SPESSOA (NOLOCK) ON SPESSOA.CODIGO = SALUNO.CODPESSOA
INNER JOIN PPESSOA ALUNO$ ON ALUNO$.CODIGO = SALUNO.CODPESSOA
LEFT JOIN PPESSOA MAE$ (NOLOCK) ON mae$.CODIGO = SPESSOA.CODPESSOAMAE
LEFT JOIN PPESSOA PAI$ (NOLOCK) ON PAI$.CODIGO = SPESSOA.CODPESSOAPAI
LEFT JOIN PCODNACAO ON PCODNACAO.CODINTERNO = ALUNO$.NACIONALIDADE
WHERE SALUNO.RA = :RA_S