BEGIN TRAN

UPDATE SMATRICPL SET CODTURMA = 'NATAÇÃO2020'
FROM SMATRICPL AS A
  WHERE 
   EXISTS(
	SELECT 
	  MAT.CODFILIAL
	 ,MAT.RA
	 ,MAT.IDHABILITACAOFILIAL
	 ,MAT.IDPERLET
	 ,LET.CODPERLET
	 ,MAT.CODTURMA
	 ,C.CODCURSO
	 ,C.NOME AS CURSO
 
	 FROM SMATRICPL AS MAT

	JOIN SPLETIVO AS LET ON LET.IDPERLET = MAT.IDPERLET AND LET.CODPERLET='2020' 
	JOIN SHABILITACAOFILIAL AS HABF ON HABF.IDHABILITACAOFILIAL = MAT.IDHABILITACAOFILIAL
	JOIN SCURSO AS C ON C.CODCURSO = HABF.CODCURSO AND C.NOME = 'NATAÇÃO'

	WHERE  A.RA = MAT.RA  AND A.IDHABILITACAOFILIAL = MAT.IDHABILITACAOFILIAL AND A.IDPERLET = MAT.IDPERLET AND MAT.CODTURMA IS  NULL
	)

--	ROLLBACK
COMMIT