--TITMMOV.CODTBORCAMENTO
SELECT DISTINCT TITMMOV.CODTBORCAMENTO,TMOV.CODFILIAL, TMOV.CODTMV, TMOV.IDMOV/*,TMOV.CODTMV,TTBORCAMENTO.DESCRICAO,**/ FROM TTBORCAMENTO

 JOIN TITMMOV ON TITMMOV.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO
 JOIN TMOV ON TMOV.IDMOV = TITMMOV.IDMOV

WHERE /*TMOV.IDMOV = 423676 --AND*/ TMOV.CODFILIAL IN (5) --AND  TTBORCAMENTO.DESCRICAO LIKE '%Informatica e Manut. de Software%' AND
 AND TITMMOV.CODTBORCAMENTO LIKE 
     (CASE WHEN TMOV.CODFILIAL IN (5, 6, 7, 15, 16, 18, 19, 21) AND TMOV.CODTMV IN ('1.2.03','1.2.04') THEN  '5%'
           WHEN TMOV.CODFILIAL IN (1, 3, 4, 8, 9, 11, 14, 17) AND TMOV.CODTMV IN ('1.2.03','1.2.04') THEN '4%' 
		   WHEN TMOV.CODTMV IN ('1.2.02') THEN '1%'
		   ELSE TITMMOV.CODTBORCAMENTO END
)
--AND TITMOV.IDMOV = :FRM_IDMOV

--ORDER BY TMOV.CODFILIAL,TITMMOV.CODTBORCAMENTO



--SELECT * FROM TITMMOV

--SELECT * FROM TTBORCAMENTO WHERE TTBORCAMENTO.DESCRICAO LIKE '%Informatica e Manut. de Software%'

--SELECT * FROM GLINKSREL WHERE MASTERTABLE LIKE 'TITMMOV' AND CHILDTABLE = 'TMOV'

------------------------------------------------------------------------------------------------------------
/*Naturezas do grupo: 1.2.3.1 - Imobilizado e 5 - Custos (Filiais: 5, 6, 7, 15, 16, 18, 19, 21)

Naturezas do grupo: 1.2.3.1 - Imobilizado e 4 - Despesas ( Filiais: 1, 3, 4, 8, 9, 11, 14, 17)*/
------------------------------------------------------------------------------------------------------------

--CODCOLIGADA, CODTBORCAMENTO

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'TMOV' AND CHILDTABLE = 'TITMMOV'