SELECT *,AA.DIAS_LETIVOS_1+AA.DIAS_LETIVOS_2+AA.DIAS_LETIVOS_3+AA.DIAS_LETIVOS_4 AS TOTAL_DIAS_LET,
FALTAS_1+FALTAS_2+FALTAS_3+FALTAS_4 AS FALTAS_TOTAL,
ISNULL(CAST((CASE WHEN (AA.CODTURMA LIKE 'EF.1%' 
    		   OR AA.CODTURMA LIKE 'EF.2%' 
			   OR AA.CODTURMA LIKE 'EF.3%' 
			   OR AA.CODTURMA LIKE 'EF.4%' 
			   OR AA.CODTURMA LIKE 'EF.5%') THEN NULL ELSE
			   AA.AULAS_DADAS_1+AA.AULAS_DADAS_2+AA.AULAS_DADAS_3+AA.AULAS_DADAS_4 END) AS VARCHAR(5)),'-')  AS TOTAL_AULAS_DADAS

FROM
(
SELECT 

ISNULL(CAST(SUM(CASE WHEN SNOTAETAPA.CODETAPA = 19 THEN SNOTAETAPA.NOTAFALTA ELSE NULL END)AS NUMERIC(5)),'0') AS FALTAS_1,
SUM(CASE WHEN SNOTAETAPA.CODETAPA = 19 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) AS AULAS_DADAS_1,
CASE WHEN SPLETIVO.CODPERLET = '2016' 
          AND (STURMADISC.CODTURMA LIKE 'EF.1%' 
    		   OR STURMADISC.CODTURMA LIKE 'EF.2%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.3%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.4%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.5%')
		  AND SUM(CASE WHEN SNOTAETAPA.CODETAPA = 19 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) <> 0
     THEN 54
     ELSE MAX(CASE WHEN SMODETAPAPLETIVO.CODETAPA = 19 THEN SMODETAPAPLETIVO.AULASPREVISTAS ELSE NULL END)
END AS DIAS_LETIVOS_1,

ISNULL(CAST(SUM(CASE WHEN SNOTAETAPA.CODETAPA = 29 THEN SNOTAETAPA.NOTAFALTA ELSE NULL END)AS NUMERIC(5)),'0') AS FALTAS_2,
SUM(CASE WHEN SNOTAETAPA.CODETAPA = 29 THEN SNOTAETAPA.AULASDADAS ELSE NULL END)AS AULAS_DADAS_2,
CASE WHEN SPLETIVO.CODPERLET = '2016' 
          AND (STURMADISC.CODTURMA LIKE 'EF.1%' 
    		   OR STURMADISC.CODTURMA LIKE 'EF.2%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.3%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.4%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.5%') 
		  AND SUM(CASE WHEN SNOTAETAPA.CODETAPA = 29 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) <> 0	   
     THEN 50
     ELSE MAX(CASE WHEN SMODETAPAPLETIVO.CODETAPA = 29 THEN SMODETAPAPLETIVO.AULASPREVISTAS ELSE NULL END) 
END AS DIAS_LETIVOS_2,

ISNULL(CAST(SUM(CASE WHEN SNOTAETAPA.CODETAPA = 39 THEN SNOTAETAPA.NOTAFALTA ELSE NULL END)AS NUMERIC(5)),'0') AS FALTAS_3,
CASE WHEN SPLETIVO.CODPERLET >= '2016' 
          AND (STURMADISC.CODTURMA LIKE 'EF.1%' 
    		   OR STURMADISC.CODTURMA LIKE 'EF.2%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.3%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.4%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.5%') THEN 50 ELSE SUM(CASE WHEN SNOTAETAPA.CODETAPA = 39 THEN SNOTAETAPA.AULASDADAS ELSE NULL END)END AS AULAS_DADAS_3, /*ADD DENNYSON 09/01/2019*/
			   
CASE WHEN SPLETIVO.CODPERLET >= '2016' 
          AND (STURMADISC.CODTURMA LIKE 'EF.1%' 
    		   OR STURMADISC.CODTURMA LIKE 'EF.2%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.3%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.4%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.5%') 
		  AND SUM(CASE WHEN SNOTAETAPA.CODETAPA = 39 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) <> 0	
     THEN 50
     ELSE MAX(CASE WHEN SMODETAPAPLETIVO.CODETAPA = 39 THEN SMODETAPAPLETIVO.AULASPREVISTAS ELSE NULL END)
END AS DIAS_LETIVOS_3,

ISNULL(CAST(SUM(CASE WHEN SNOTAETAPA.CODETAPA = 49 THEN SNOTAETAPA.NOTAFALTA ELSE NULL END)AS NUMERIC(5)),'0') AS FALTAS_4,
SUM(CASE WHEN SNOTAETAPA.CODETAPA = 49 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) AS AULAS_DADAS_4,
CASE WHEN SPLETIVO.CODPERLET >= '2016' 
          AND (STURMADISC.CODTURMA LIKE 'EF.1%' 
    		   OR STURMADISC.CODTURMA LIKE 'EF.2%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.3%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.4%' 
			   OR STURMADISC.CODTURMA LIKE 'EF.5%') 
		  AND SUM(CASE WHEN SNOTAETAPA.CODETAPA = 49 THEN SNOTAETAPA.AULASDADAS ELSE NULL END) <> 0	
     THEN 48
     ELSE MAX(CASE WHEN SMODETAPAPLETIVO.CODETAPA = 49 THEN SMODETAPAPLETIVO.AULASPREVISTAS ELSE NULL END) 
END AS DIAS_LETIVOS_4,

STURMADISC.CODTURMA

FROM STURMADISC (NOLOCK)
JOIN SMATRICULA (NOLOCK)
  ON SMATRICULA.CODCOLIGADA = STURMADISC.CODCOLIGADA
 AND SMATRICULA.IDPERLET = STURMADISC.IDPERLET
 AND SMATRICULA.IDTURMADISC = STURMADISC.IDTURMADISC 
JOIN SPLETIVO (NOLOCK)
  ON SPLETIVO.CODCOLIGADA = STURMADISC.CODCOLIGADA
 AND SPLETIVO.CODFILIAL = STURMADISC.CODFILIAL
 AND SPLETIVO.IDPERLET = STURMADISC.IDPERLET
INNER JOIN SNOTAETAPA (NOLOCK)
  ON SNOTAETAPA.CODCOLIGADA = SMATRICULA.CODCOLIGADA
 AND SNOTAETAPA.IDTURMADISC = SMATRICULA.IDTURMADISC 
 AND SNOTAETAPA.RA = SMATRICULA.RA
JOIN SMODETAPAPLETIVO (NOLOCK)
  ON SMODETAPAPLETIVO.IDPERLET = STURMADISC.IDPERLET
  AND SNOTAETAPA.CODETAPA = SMODETAPAPLETIVO.CODETAPA
WHERE SPLETIVO.CODPERLET = '2018'--:PER_LETIVO
  AND SMATRICULA.RA = '009082'--:RAALUNO1
  AND STURMADISC.CODTURMA = 'EF.1A.V'--:COD_TURMA
  AND SNOTAETAPA.CODETAPA IN(19,29,39,49)


GROUP BY SPLETIVO.CODPERLET, STURMADISC.CODTURMA
)AA


--SELECT * FROM SMODETAPAPLETIVO WHERE SMODETAPAPLETIVO.CODETAPA = 49 AND IDPERLET=235

--SELECT * FROM SPLETIVO WHERE CODPERLET='2018' AND CODFILIAL=6

SELECT * FROM SMATRICULA WHERE RA IN(010053,
009847,
009923,
009838,
010046) AND IDPERLET =235