USE CORPORERM	

BEGIN TRAN


UPDATE SNOTAETAPA SET NOTAFALTA = TAB.NOTAFALTA FROM 

 SNOTAETAPA AS N

 JOIN
(
SELECT DISTINCT
SP.CODFILIAL,
SP.CODTIPOCURSO,
SP.CODPERLET,
NT.CODETAPA,
NT.IDTURMADISC,
NT.TIPOETAPA,
NT.NOTAFALTA,
NT.RA,
STD.CODTURMA,
STD.CODDISC,
STD.IDHABILITACAOFILIAL

FROM SNOTAETAPA AS NT

JOIN STURMADISC AS STD ON STD.IDTURMADISC = NT.IDTURMADISC
JOIN SPLETIVO AS SP ON SP.IDPERLET = STD.IDPERLET

WHERE SP.CODFILIAL = 6 AND CODPERLET = '2020' AND CODETAPA = 10 AND NT.NOTAFALTA IS NOT NULL AND STD.CODTURMA BETWEEN 'EF.6A.M' AND 'EM4' --'EF.9D.M' --AND NT.RA= '010480'



) AS TAB ON N.IDTURMADISC = TAB.IDTURMADISC AND N.RA = TAB.RA


WHERE N.CODETAPA = 16

 -- RA= '009791'

 /* ETAPA 10 - PROVA TRIMESTRAL --- ETAPA 16 - 1° TRIMESTRE */
--
-- ROLLBACK

--COMMIT