SELECT AA.IDBOLETO FROM 
 (
 SELECT A.IDLAN,A.NUMERODOCUMENTO,A.STATUSLAN,A.HISTORICO,

 FORMAT( A.MESDECOMPETENCIA,'MM/yyyy')  AS MES_COMPETENCIA,
 A.DATACRIACAO,A.DATABAIXA,C.IDBOLETO,D.IDMOV,E.NUMEROMOV,E.CODTMV,F.NUMERONFSE NFE, F.STATUS STATUS_NFE, A.CODFILIAL,G.IDPARCELA,H.RA,
 H.CODCONTRATO,H.CODSERVICO/*,I.NOME SERVICO*/,A.CODTB1FLX
 
 FROM FLAN  A (NOLOCK) 

 JOIN FLANBOLETO C (NOLOCK)  ON C.IDLAN=A.IDLAN AND A.CODFILIAL=5 AND A.PERLETIVO = CONVERT(VARCHAR,DATEPART(YEAR,A.MESDECOMPETENCIA)) AND CODTB1FLX NOT IN ('1.1.1.14','1.1.1.23')
 LEFT JOIN FBOLETO B (NOLOCK)  ON B.IDBOLETO=C.IDBOLETO
 LEFT JOIN SLANMOV D (NOLOCK)  ON D.IDLAN = A.IDLAN
 LEFT JOIN TMOV E (NOLOCK)  ON E.IDMOV = D.IDMOV
 LEFT JOIN TNFEMUNICIPAL F (NOLOCK)  ON F.IDMOV = D.IDMOV
 LEFT JOIN SLAN G (NOLOCK)  ON G.IDLAN=A.IDLAN
  JOIN SPARCELA H (NOLOCK)  ON H.IDPARCELA = G.IDPARCELA AND H.CODSERVICO IN (1 ,127 ,15 ,154 ,163 ,22 ,226 ,258 ,259 ,264 ,31 ,56 ,57 ,59 ,61 ,62 ,8 ,101 ,163 ,275)
 --JOIN SSERVICO I (NOLOCK)  ON I.CODSERVICO = H.CODSERVICO
 WHERE A.PAGREC=1 AND A.STATUSLAN NOT IN (2,3)
 )AA

 WHERE NFE IS NULL  AND AA.MES_COMPETENCIA LIKE '12/2018' OR AA.MES_COMPETENCIA IS NULL

 ORDER BY IDLAN