SET LANGUAGE BRAZILIAN

SELECT DISTINCT SMATRICPL.IDHABILITACAOFILIAL QUEBRA,
       SMATRICPL.CODTURMA TURMA,
       SALUNO.RA, 
       PPESSOA.NOME, 
       SPARCELA.PARCELA, 
       FLAN.DATAVENCIMENTO, 
       FLAN.VALORORIGINAL, 
       ISNULL(CONVERT(DECIMAL(8,2),(SUM(SBOLSAALUNO.DESCONTO))),0) AS PER_DESC,
       SUM(SBOLSALAN.VALOR) DESCONTO,
       VLR_LIQ = (CASE WHEN SUM(SBOLSALAN.VALOR) IS NOT NULL THEN FLAN.VALORORIGINAL - SUM(SBOLSALAN.VALOR) ELSE FLAN.VALORORIGINAL END) ,
       VLJURO = (CASE WHEN FLAN.VALORJUROS = 0 AND FLAN.DATAVENCIMENTO < GETDATE() AND FLAN.STATUSLAN = 0 THEN ((FLAN.VALORORIGINAL * (0.03333 * DATEDIFF(DAY,FLAN.DATAVENCIMENTO,GETDATE())))/100) ELSE FLAN.VALORJUROS END),
       VLMULTA = (CASE WHEN FLAN.VALORMULTA = 0 AND FLAN.DATAVENCIMENTO < GETDATE() AND FLAN.STATUSLAN = 0 THEN (FLAN.VALORORIGINAL * 0.02) ELSE FLAN.VALORMULTA END),
       VLBAIXA = (CASE WHEN FLAN.VALORBAIXADO = 0 THEN (((CASE WHEN SUM(SBOLSALAN.VALOR) IS NOT NULL THEN FLAN.VALORORIGINAL - SUM(SBOLSALAN.VALOR) ELSE FLAN.VALORORIGINAL END) + ((FLAN.VALORORIGINAL * (0.03333 * DATEDIFF(DAY,FLAN.DATAVENCIMENTO,GETDATE())))/100) + (FLAN.VALORORIGINAL * 0.02))) ELSE FLAN.VALORBAIXADO END),
       FLAN.IDLAN,
       VLR_PG = CASE WHEN FLAN.STATUSLAN='1' THEN CAST(FLAN.VALORBAIXADO AS CHAR) ELSE '0' END,
       VLR_APG = (CASE WHEN FLAN.STATUSLAN = 0 THEN (((CASE WHEN SUM(SBOLSALAN.VALOR) IS NOT NULL THEN FLAN.VALORORIGINAL - SUM(SBOLSALAN.VALOR) ELSE FLAN.VALORORIGINAL END) + ((FLAN.VALORORIGINAL * (0.03333 * DATEDIFF(DAY,FLAN.DATAVENCIMENTO,GETDATE())))/100) + (FLAN.VALORORIGINAL * 0.02))) ELSE 0 END),
       SSERVICO.NOME,
       FLAN.DATABAIXA,
       SOMA_DIF = (FLAN.VALOROP5 + FLAN.VALOROP6),
       SUB_DIF = (FLAN.VALOROP4 + FLAN.VALOROP7)
FROM FLAN 
  INNER JOIN SLAN               ON FLAN.IDLAN = SLAN.IDLAN 
                                AND FLAN.CODFILIAL = 6 -- :COD_FILIAL_S
  INNER JOIN SPARCELA           ON SLAN.IDPARCELA = SPARCELA.IDPARCELA
  inner join scontrato			on scontrato.codcontrato = sparcela.codcontrato AND SCONTRATO.USARSOLICITACAO = 'S' /*Inserido em 27 de junho de 2018*/
  INNER JOIN SSERVICO           ON SSERVICO.CODSERVICO = SPARCELA.CODSERVICO --AND SSERVICO.NOME like '%' AND SSERVICO.CODSERVICO NOT IN (68,69)
  INNER JOIN SALUNO             ON SPARCELA.RA = SALUNO.RA
  INNER JOIN PPESSOA            ON SALUNO.CODPESSOA = PPESSOA.CODIGO
  INNER JOIN SMATRICPL          ON SALUNO.RA = SMATRICPL.RA 
                                AND SMATRICPL.CODFILIAL = 6 --:COD_FILIAL_S
                                AND SPARCELA.IDPERLET = SMATRICPL.IDPERLET
  INNER JOIN SPLETIVO           ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
                                AND SPLETIVO.CODPERLET = '2019' -- :PERIODO
  INNER JOIN SHABILITACAOFILIAL ON SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL 
                                AND SHABILITACAOFILIAL.CODFILIAL = 6 --:COD_FILIAL_S
                                AND SCONTRATO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL /*Inserido em 27 de junho de 2018*/
  INNER JOIN SSTATUS            ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
  LEFT JOIN SBOLSALAN           ON SBOLSALAN.IDLAN=FLAN.IDLAN AND SBOLSALAN.IDPARCELA=SPARCELA.IDPARCELA
  LEFT JOIN SBOLSAALUNO         ON SBOLSAALUNO.RA = SCONTRATO.RA AND SBOLSAALUNO.CODCONTRATO = SCONTRATO.CODCONTRATO AND SBOLSAALUNO.IDPERLET = SCONTRATO.IDPERLET AND SBOLSAALUNO.CODBOLSA = SBOLSALAN.CODBOLSA

WHERE 
 SSERVICO.NOME LIKE '%' AND
 SSTATUS.DESCRICAO = 'MATRICULADO' AND
 FLAN.DATAVENCIMENTO >= '01/11/2019' AND
 FLAN.DATAVENCIMENTO <= '30/11/2019' AND
 ((FLAN.DATABAIXA >= '01/01/2019' AND FLAN.DATABAIXA <= '17/12/2019') OR 
 FLAN.DATABAIXA IS NULL) AND
 FLAN.STATUSLAN<>'2' AND
 SMATRICPL.CODTURMA>='A' AND
 SMATRICPL.CODTURMA<='Z'
-- SPARCELA.RA= '007162'

GROUP BY SMATRICPL.IDHABILITACAOFILIAL, SMATRICPL.CODTURMA, SALUNO.RA, PPESSOA.NOME, SPARCELA.PARCELA, FLAN.DATAVENCIMENTO, FLAN.VALORORIGINAL
, FLAN.VALORJUROS, FLAN.STATUSLAN, FLAN.VALORMULTA, FLAN.VALORBAIXADO, FLAN.IDLAN, SSERVICO.NOME, FLAN.DATABAIXA, FLAN.VALOROP5, FLAN.VALOROP6, FLAN.VALOROP4, FLAN.VALOROP7
, SBOLSAALUNO.DESCONTO

HAVING ISNULL(CONVERT(DECIMAL(8,2),((SBOLSAALUNO.DESCONTO))),0) >= REPLACE('100',',','.') AND ISNULL(CONVERT(DECIMAL(8,2),((SBOLSAALUNO.DESCONTO))),0) <= REPLACE('100',',','.')

ORDER BY PPESSOA.NOME, SPARCELA.PARCELA