--  PARCELAS PLANO REL CONTRATO PG 7 FIL 5 ORIGINAL
SELECT DISTINCT
 SCONTRATO.CODCONTRATO
,SCONTRATO.RA
,SCONTRATO.CODPLANOPGTO
,SCONTRATO.CODFILIAL
,MAX(SPARCPLANO.PARCELA) AS

,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EFI_INI),0),'C','pt-br') AS EFI_INI1
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EF_FIM),0),'C','pt-br') AS EF_FIM1
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EM12),0),'C','pt-br') AS EM121
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EM3),0),'C','pt-br') AS EM31
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:PREVEST),0),'C','pt-br') AS PREVEST1


,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EFI_INI)/MAX(SPARCPLANO.PARCELA),0),'C','pt-br') AS P_EFI_INI
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EF_FIM)/MAX(SPARCPLANO.PARCELA),0),'C','pt-br') AS P_EF_FIM
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EM12)/MAX(SPARCPLANO.PARCELA),0),'C','pt-br') AS P_EM12
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:EM3)/MAX(SPARCPLANO.PARCELA),0),'C','pt-br') AS P_EM3
,FORMAT(ISNULL(CONVERT(DECIMAL(12,4),:PREVEST)/MAX(SPARCPLANO.PARCELA),0),'C','pt-br') AS P_PREVEST

 FROM SCONTRATO 
JOIN SPLANOPGTO ON SPLANOPGTO.CODPLANOPGTO = SCONTRATO.CODPLANOPGTO AND SPLANOPGTO.IDPERLET = SCONTRATO.IDPERLET
JOIN SPLETIVO ON SPLETIVO.IDPERLET = SCONTRATO.IDPERLET
JOIN SPARCPLANO ON SPARCPLANO.CODPLANOPGTO = SCONTRATO.CODPLANOPGTO AND SPARCPLANO.IDPERLET = SCONTRATO.IDPERLET

WHERE CODCONTRATO = 193671 AND SPLETIVO.IDPERLET = 292--:IDPERLET

GROUP BY CODCONTRATO,RA,SCONTRATO.CODPLANOPGTO,SCONTRATO.CODFILIAL