		/*
PARÂMETROS	
Filial	5
Período Letivo	%
Nível de Ensino	1
Serviço	%
Data de Corte	30/12/2018
Data Inicial	01/01/2015
Data Final	30/12/2018    RA  = 00018603   LAN 1489927   ----------   RA BOLSA INDCONDICIONAL 00015160
		*/

DECLARE @DATA_CORTE AS DATE , @DATA_INICIAL AS DATE , @DATA_FINAL AS DATE
DECLARE @CODPERLET AS VARCHAR(10), @CODFILIAL AS VARCHAR(2),  @NOME_SERVICO AS VARCHAR(20), @COD_TIPO_CURSO AS VARCHAR(2)

SET LANGUAGE PORTUGUêS
SET DATEFORMAT DMY

SET @DATA_CORTE = '30/12/2018'  --'2019-12-30' -- '2018-12-30' --'2019-12-30'
SET @DATA_FINAL =  '30/12/2018'  --'2018-12-30'  --
SET @DATA_INICIAL = '01/01/2015'
SET @CODFILIAL = 5 --18
SET @NOME_SERVICO = '%'
SET @COD_TIPO_CURSO = 1 --4
SET @CODPERLET = '%'


SELECT *
,CONVERT(MONEY,(TAB.VALORORIGINAL-ISNULL(TAB.VALORORIGINAL_BX,0)-ISNULL(TAB.BOLSASINCONDICIONAIS,0))) AS VALOR_LIQUIDO --******* ALTERADO OK
 FROM (
SELECT  

       -- FLANBAIXA.IDBAIXA, --******* ALTERADO
		SPLETIVO.CODPERLET,
		FLAN.IDLAN,
		FLAN.MESDECOMPETENCIA,
		FLAN.DATAVENCIMENTO,
		CASE WHEN FLAN.STATUSLAN <> 1 THEN (DATEDIFF ( day , CONVERT(VARCHAR(11),FLAN.DATAVENCIMENTO,103) , CONVERT(VARCHAR(11),GETDATE(),103))) ELSE 0 END DIASVENCIDOS,
		SALUNO.RA,
		PPESSOA.NOME NOMEALUNO,
		FTB1.CODTB1FLX,
		FTB1.DESCRICAO DESC_CODTB
		,CONVERT(MONEY,FLAN.VALORORIGINAL) VALORORIGINAL --******* ALTERADO ok
		,ISNULL((CONVERT(DECIMAL(18,2),(SELECT SUM(VALORORIGINAL) AS VALORORIGINAL FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = FLAN.IDLAN AND (FLANBAIXA.DATABAIXA <= @DATA_CORTE) AND FLANBAIXA.DATACANCELBAIXA IS NULL))),0) AS VALORORIGINAL_BX, --******* ALTERADO ok
		--ISNULL(CONVERT(DECIMAL(18,2),AA.VALORBAIXA),'0') AS VALORORIGINAL_BX , --**ALTERADO OK
		CASE (CASE WHEN AA.STATUS1 IS NOT NULL THEN AA.STATUS1 ELSE FLAN.STATUSLAN END) WHEN 0 THEN 'Em Aberto'
							WHEN 4 THEN 'Baixado Parcialmente'
							WHEN 3 THEN CASE WHEN FLAN.DATABAIXA > ''--@DATA_CORTE
									 		 THEN 'Baixado p/ Acordo Após Dt. Corte'  END
							WHEN 1 THEN 
							CASE 
							(SELECT TOP 1
												FLANBAIXA.CODCXA 
												FROM FLANBAIXA 
												INNER JOIN 
												FCXA ON FCXA.CODCXA = FLANBAIXA.CODCXA
												WHERE IDLAN = FLAN.IDLAN
												AND FCXA.DESCRICAO LIKE '%PERDA%'
												AND FLANBAIXA.STATUS <> 1
												) WHEN '885' THEN 'Baixado como Perda'
							ELSE
							CASE
							WHEN FLAN.DATABAIXA > @DATA_CORTE 
											 THEN 'Baixado Após Dt. Corte' END END
					 
		END STATUSLAN,
		ISNULL(CONVERT(VARCHAR(10),ISNULL(AA.DATABAIXA1, FLAN.DATABAIXA),103),'') AS DATABAIXA, --******* ALTERADO OK
		FLAN.CODFILIAL,
		--FLANBAIXA.
		ISNULL(CONVERT(SMALLMONEY,AA.VALORBAIXA),CASE  (SELECT TOP 1
				FLANBAIXA.CODCXA 
				FROM FLANBAIXA 
				INNER JOIN 
				FCXA ON FCXA.CODCXA = FLANBAIXA.CODCXA
				WHERE IDLAN = FLAN.IDLAN
				AND FCXA.DESCRICAO LIKE '%PERDA%'
				AND FLANBAIXA.STATUS <> 1) WHEN '885' THEN NULL ELSE convert(decimal(18,2),FLAN.VALORBAIXADO)END)  VALORBAIXADO, --*****ALTERADO INTEIRO OK

		CASE (SELECT TOP 1
				FLANBAIXA.CODCXA 
				FROM FLANBAIXA 
				INNER JOIN 
				FCXA ON FCXA.CODCXA = FLANBAIXA.CODCXA
				WHERE IDLAN = FLAN.IDLAN
				AND FCXA.DESCRICAO LIKE '%PERDA%'
				AND FLANBAIXA.STATUS <> 1) WHEN '885' THEN convert(decimal(18,2),FLAN.VALORBAIXADO) ELSE NULL END VALORPERDA,
		STIPOCURSO.NOME TIPOCURSO,
		SSERVICO.NOME SERVIÇO,
		CASE SCONTRATO.TIPOCONTRATO WHEN 'A' THEN 'Acordo' WHEN 'P' THEN 'Parcela' ELSE SCONTRATO.TIPOCONTRATO END TIPOPARCELA,
		SPARCELA.PARCELA,
		SCURSO.NOME,
		FCFO.CODCFO AS 'CODIGO CLI/FOR',
		FCFO.NOMEFANTASIA AS 'NOME CLI/FOR',
		SBOLSA.VALOR VALOR_BOLSA -- ALTERADO
		/*FLAN.VALOROP8 BOLSASINCONDICIONAIS*/
		,
		case when (SBOLSA.NOME LIKE 'BOLSA%' OR SBOLSA.NOME LIKE '%FIES%')  then CONVERT(smallmoney,SBOLSALAN.VALOR) else 0 end BOLSASINCONDICIONAIS --******* ALTERADO OK
		--,CONVERT(SMALLMONEY,FLANBAIXA.VALORBAIXA) VALORBAIXA1 
		--,FLANBAIXA.*
		

		FROM FLAN WITH (NOLOCK)
		INNER JOIN FTB1 WITH (NOLOCK) ON FTB1.CODTB1FLX = FLAN.CODTB1FLX
		INNER JOIN SLAN WITH (NOLOCK) ON SLAN.IDLAN = FLAN.IDLAN
		INNER JOIN SPARCELA WITH (NOLOCK) ON SLAN.IDPARCELA = SPARCELA.IDPARCELA
		INNER JOIN SALUNO WITH (NOLOCK) ON SALUNO.RA = SPARCELA.RA
		INNER JOIN PPESSOA WITH (NOLOCK) ON SALUNO.CODPESSOA = PPESSOA.CODIGO
		INNER JOIN FCFO ON FCFO.CODCFO = FLAN.CODCFO
		--AND FCFO.NOME NOT LIKE '%CAIX%ECON%' --******************** ALTERADO OK
		INNER JOIN SPLETIVO ON SPARCELA.IDPERLET = SPLETIVO.IDPERLET	
		INNER JOIN SSERVICO WITH (NOLOCK) ON SPARCELA.CODSERVICO = SSERVICO.CODSERVICO
				INNER JOIN STIPOCURSO WITH (NOLOCK) ON SSERVICO.CODTIPOCURSO = STIPOCURSO.CODTIPOCURSO
		INNER JOIN SCONTRATO WITH (NOLOCK) ON SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
		INNER JOIN SHABILITACAOFILIAL WITH (NOLOCK) ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
		INNER JOIN SCURSO WITH (NOLOCK) ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

		------  valororiginal , valororiginalbx , valorbx, valorperda, valorliquido
		/*
		LEFT JOIN (SELECT F.IDLAN,CONVERT(MONEY,SUM(F.VALORORIGINAL)) VALORORIGINAL1, CONVERT(MONEY,SUM(F.VALORORIGINALBX)) AS VALORORIGINALBX1, CONVERT(MONEY,SUM(F.VALORBAIXADO)) AS VALORBAIXADO, CONVERT(MONEY,SUM(F.VALORORIGINAL-F.VALORBAIXADO)) AS VRLIQUIDO FROM SBOLSALAN 
				LEFT JOIN FLAN F ON F.IDLAN = SBOLSALAN.IDLAN
				LEFT JOIN FLANBAIXA ON FLANBAIXA.IDLAN = SBOLSALAN.IDLAN GROUP BY F.IDLAN
		
		)AA ON AA.IDLAN = FLAN.IDLAN  */

		LEFT JOIN SBOLSALAN ON SBOLSALAN.IDLAN = FLAN.IDLAN AND SBOLSALAN.CODBOLSA IN (SELECT CODBOLSA FROM SBOLSA WHERE (SBOLSA.NOME LIKE 'BOLSA%' OR SBOLSA.NOME LIKE '%FIES%')) --******************** ALTERADO OK
		LEFT JOIN SBOLSA ON SBOLSA.CODBOLSA = SBOLSALAN.CODBOLSA
		AND (SBOLSA.NOME LIKE 'BOLSA%' OR SBOLSA.NOME LIKE '%FIES%') --******************** ALTERADO OK
		

----------------------------------------------------TESTS--------------------------------------------------
		LEFT JOIN (SELECT  IDLAN, DATACANCELBAIXA
, (SELECT MAX(DATABAIXA) FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = BB.IDLAN AND CONVERT(VARCHAR(10),FLANBAIXA.DATABAIXA,103) < = @DATA_CORTE AND DATACANCELBAIXA IS NULL ) AS DATABAIXA1
, (SELECT MAX(STATUS) FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = BB.IDLAN AND CONVERT(VARCHAR(10),FLANBAIXA.DATABAIXA,103) < = @DATA_CORTE AND DATACANCELBAIXA IS NULL ) AS STATUS1
,CONVERT(MONEY,SUM(VALORORIGINAL)) AS VALORORIGINAL
,CONVERT(MONEY,SUM(VALORBAIXA)) AS VALORBAIXA

 FROM FLANBAIXA BB WHERE BB.DATACANCELBAIXA IS NULL AND BB.DATABAIXA < = @DATA_CORTE  --WHERE BB.IDLAN = IDLAN

 GROUP BY IDLAN,DATACANCELBAIXA,DATABAIXA) AA
 
  ON  AA.IDLAN = FLAN.IDLAN AND AA.DATACANCELBAIXA IS NULL AND AA.DATABAIXA1 < =  @DATA_CORTE --******************** ALTERADO OK

-----------------------------------------------------TESTS FIM--------------------------------------------------


		--FLANBAIXA ou FLOGVALORES
		WHERE 
		
		FLAN.MESDECOMPETENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL
		AND (FLAN.DATABAIXA IS NULL OR FLAN.DATABAIXA > @DATA_CORTE 
		)
		AND 
		SPLETIVO.CODPERLET LIKE @CODPERLET
		AND 
		FLAN.CODFILIAL =  @CODFILIAL
		AND SSERVICO.NOME LIKE  @NOME_SERVICO
		AND SSERVICO.CODTIPOCURSO =  @COD_TIPO_CURSO
		/*AND FCFO.NOME NOT LIKE '%CAIXA%ECON%FEDERAL%'*/  --*********ALTERADO OK
		AND FLAN.STATUSLAN NOT IN (2)
		--AND SPARCELA.RA=  '00018603'  
		--AND SALUNO.RA = '00015160'
		      AND FLAN.IDLAN = 1435510
--1518738 --932503

		-- FLANBAIXA.IDBAIXA, FLANBAIXA.DATACANCELBAIXA IS NULL , FLANBAIXA.DATABAIXA < =  DATACORTE, FLANBAIXA.VALORBAIXA = 490,50
		AND FLAN.CODTB1FLX NOT IN ('1.1.1.02') --******ALTERADO OK

		

		)TAB
		ORDER BY idlan, NOME,MESDECOMPETENCIA 

		/*
					   WHEN 0 THEN 'ABERTO'
                       WHEN 1 THEN 'PAGO'
				       WHEN 2 THEN 'CANCELADO'
				       WHEN 3 THEN 'ACORDO - '+CONVERT(VARCHAR,B.IDACORDO)  
				       WHEN 4 THEN 'BX_PARCIAL' 
       */


	 --  SELECT * FROM SMATRICPL WHERE RA= '00015160'

	 -- SELECT * FROM FLANBAIXA WHERE IDLAN = '1518738'

	 