SELECT 
A.CODFILIAL
,D.NOME ALUNO
,CONVERT(VARCHAR(10),D.DTNASCIMENTO,103) DT_NASCIMENTO
,A.RA
,A.DTMATRICULA
,A.CODTURMA
,C.DESCRICAO STATUS
,E.NOME RESPONSAVEL
,ISNULL(E.CPF,'') CPF_RESP
,E.EMAIL EMAIL_RESP
,E.TELEFONE1 TEL_RESP1
,E.TELEFONE2 TEL_RESP2
,E.TELEFONE3 TEL_RESP3
,I.CODCONTRATO
,J.NOME SERVICO

 FROM SMATRICPL A

 JOIN SALUNO B ON A.RA = B.RA
 JOIN SSTATUS C ON A.CODSTATUS = C.CODSTATUS
 JOIN PPESSOA D ON B.CODPESSOA = D.CODIGO
 JOIN PPESSOA E ON E.CODIGO = B.CODPESSOARACA
 JOIN SPLETIVO F ON F.IDPERLET = A.IDPERLET
 JOIN SHABILITACAOFILIAL G ON G.IDHABILITACAOFILIAL = A.IDHABILITACAOFILIAL
 JOIN SCURSO H ON H.CODCURSO = G.CODCURSO 
 JOIN SCONTRATO I ON I.RA = A.RA AND I.IDPERLET = A.IDPERLET AND I.IDHABILITACAOFILIAL = A.IDHABILITACAOFILIAL
 JOIN SPLANOPGTO K ON K.CODPLANOPGTO = I.CODPLANOPGTO AND K.IDPERLET = I.IDPERLET
 JOIN SPARCPLANO L ON L.CODPLANOPGTO = K.CODPLANOPGTO AND L.PARCELA = 1
 JOIN SSERVICO J ON J.CODSERVICO = L.CODSERVICO

WHERE C.DESCRICAO LIKE 'MAT%' AND F.CODPERLET = '2019' AND  A.CODFILIAL IN (5,19) AND J.NOME LIKE '%MENS%' --AND A.RA= '00007298'


ORDER BY A.CODFILIAL,A.CODTURMA,D.NOME


--SELECT * FROM SPARCPLANO
--SELECT * FROM STIPOCURSO
--SELECT * FROM SBOLSAALUNO
--SELECT* FROM SCURSO
--SELECT * FROM SMODALIDADECURSO

--SELECT * FROM SHABILITACAOFILIAL
--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SPLANOPGTO'  IN ('SCONTRATO' ,'SSERVICO')

--SELECT * FROM PPESSOA WHERE CODIGO = 36778

/*
- Filial 5 e 19;
- Todos os Alunos;
- Status Matriculado;

- Colunas 
Nome completo do aluno
data de nascimento
RA
Turma do aluno
Status ( ativo)
Nome completo do responsável Acadêmico 
CPF Responsável Acadêmico
e-mail Responsável Acadêmico
celular Responsável Acadêmico
*/

