SET LANGUAGE PORTUGUêS
SET DATEFORMAT DMY

;WITH TABA AS(

SELECT DISTINCT J.NOME CURSO
,A.CODTURMA
,A.RA
,C.DESCRICAO AS SITUACAO
,CASE  (CASE  WHEN D.DTCANCELAMENTO IS NOT NULL THEN (CASE WHEN CONVERT(DATE,E.DTVENCIMENTO) < CONVERT(DATE,D.DTCANCELAMENTO) THEN 'ATIVO' ELSE D.STATUS END) ELSE D.STATUS END) WHEN  'N' THEN 'ATIVO' WHEN 'S' THEN 'CANCELADO' END AS STATUS_CONTRATO
,CONVERT(VARCHAR,E.DTVENCIMENTO,103) AS VENCIMENTO_PARCELA
,ISNULL(CASE K.VALIDADELIMITADA WHEN 0 THEN 'BOLSA COMERCIAL' ELSE K.NOME END ,' MENSALIDADE') NOME_BOLSA
 
 -- ,CASE WHEN A.RA IN (SELECT RA FROM SBOLSAALUNO WHERE SBOLSAALUNO.RA = A.RA) THEN 'TEST MENSAL' ELSE NULL END AS TESTMENSL

,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE G.DESCONTO END),'') DESC_BOLSA
,CONVERT(SMALLMONEY,N.VALOROP2) VALORBOLSA
,CONVERT(SMALLMONEY,/*L.VALOROP3BX*/N.VALOROP3) DESC_PONTUALIDADE_BX
,(SELECT DESCRICAO FROM STIPOMATRICULA WHERE CODTIPOMAT =  A.CODTIPOMAT) AS TIPOMATRICULA
,ISNULL(CONVERT(SMALLMONEY,(N.VALORDESCONTO+N.VALORDESCONTOACORDO+N.VALOROP3+N.VALOROP7+N.VALOROP2+N.VALOROP4+N.VALOROP8)),0) AS DESCONTO_TOTAL
--flb.valordesconto + valordescontoacordo + valorop3 + valorop7 + valorop2 + valorop4 + valorop8
,D.TIPOCONTRATO
,F.NOME AS SERVICO
,L.CODCXA AS CONTA_CX
,CASE STATUSLAN 
WHEN 0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
WHEN 3 THEN 'ACORDO'
WHEN 4 THEN 'BX_PARCIAL' END AS STATUSLAN
,CONVERT(VARCHAR,N.DATABAIXA,103) AS DATABAIXA
,CONVERT(MONEY,L.VALORORIGINAL) AS VALORORIGINAL
,CONVERT(MONEY, N.VALORBAIXA) AS VALORBAIXADO
,K.VALIDADELIMITADA 
  ,E.PARCELA
  ,H.IDLAN
  --,L.STATUSLAN AS STSLAN
  ,A.IDPERLET
  ,E.VALOR
  ,K.CODBOLSA
  ,K.NOME NOME_BOLSA1
  ,E.IDPARCELA
  ,A.CODFILIAL
  ,CONVERT(SMALLMONEY,N.VALOROP8) AS BOLSAS_INCONDICIONAIS
  ,CONVERT(VARCHAR,E.DTVENCIMENTO,103) AS MESDECOMPETENCIA
  ,ISNULL(CONVERT(SMALLMONEY,M.VALORBAIXA),0) AS VALORBX_SBLAN 
  ,ISNULL(CONVERT(SMALLMONEY,M.VALOR),0) AS VLR_SBLAN
  ,CONVERT(SMALLMONEY,E.VALOR) AS VAL_PARCELA
  ,CONVERT(SMALLMONEY,L.VALOROP2) AS VALOROP2
  ,CONVERT(VARCHAR,D.DTCANCELAMENTO,103) AS CANCELAMENTO_CONTRATO

FROM SMATRICPL A (NOLOCK)

 JOIN SPLETIVO B (NOLOCK) ON B.IDPERLET = A.IDPERLET
 JOIN SSTATUS C (NOLOCK) ON C.CODSTATUS = A.CODSTATUS
 JOIN SCONTRATO D (NOLOCK) ON D.RA = A.RA AND D.IDPERLET = A.IDPERLET AND D.IDHABILITACAOFILIAL = A.IDHABILITACAOFILIAL
 JOIN SPARCELA E (NOLOCK) ON E.RA = D.RA AND E.CODCONTRATO = D.CODCONTRATO AND E.IDPERLET = D.IDPERLET
 JOIN SSERVICO F (NOLOCK) ON F.CODSERVICO = E.CODSERVICO AND F.NOME LIKE '%MENSALIDADE%'
 LEFT JOIN SBOLSAALUNO G (NOLOCK) ON G.RA = D.RA AND G.CODCONTRATO = D.CODCONTRATO AND G.IDPERLET = D.IDPERLET
 LEFT JOIN SLAN H (NOLOCK) ON H.IDPARCELA = E.IDPARCELA
 JOIN SHABILITACAOFILIAL I (NOLOCK)  ON I.IDHABILITACAOFILIAL = D.IDHABILITACAOFILIAL
 JOIN SCURSO J (NOLOCK) ON J.CODCURSO = I.CODCURSO AND J.CODTIPOCURSO = 6
 LEFT JOIN SBOLSA K (NOLOCK) ON K.CODBOLSA = G.CODBOLSA 
 LEFT JOIN FLAN L (NOLOCK) ON L.IDLAN = H.IDLAN
 LEFT JOIN SBOLSALAN M (NOLOCK) ON E.IDPARCELA = M.IDPARCELA AND M.CODBOLSA = K.CODBOLSA
 LEFT JOIN FLANBAIXA N (NOLOCK) ON N.IDLAN = L.IDLAN AND N.DATACANCELBAIXA IS NULL


WHERE D.TIPOCONTRATO <> 'A' AND E.DTVENCIMENTO >= '01/01/2019' AND L.STATUSLAN NOT IN (2)--AND L.IDLAN=1533062 --/*B.CODPERLET = '2019/1' L.STATUSLAN NOT IN (2,3) AND*/ AND L.CODCFO <> '006747'
 

 GROUP BY J.NOME,A.CODTURMA,A.RA,C.DESCRICAO,D.STATUS,E.DTVENCIMENTO,K.VALIDADELIMITADA,K.NOME,G.DESCONTO,K.VALOR,N.VALOROP3,A.CODTIPOMAT,N.VALORDESCONTO
 ,N.VALORDESCONTOACORDO,N.VALOROP7,N.VALOROP2,N.VALOROP4,N.VALOROP8,D.TIPOCONTRATO,F.NOME,L.CODCXA,L.STATUSLAN,N.DATABAIXA,L.VALORORIGINAL,L.VALORBAIXADO
 ,E.PARCELA,H.IDLAN,A.IDPERLET,E.VALOR,K.CODBOLSA,E.IDPARCELA,A.CODFILIAL,D.RA,D.CODCONTRATO,L.MESDECOMPETENCIA,M.VALORBAIXA,M.VALOR,N.VALORBAIXA,E.VALOR,L.VALOROP2
 ,D.STATUS,D.DTCANCELAMENTO

 ),

 TABB AS(
    SELECT DISTINCT
    TABA.CURSO,
	TABA.CODTURMA,
	TABA.RA,
	TABA.SITUACAO,
	STATUS_CONTRATO,
	TABA.VENCIMENTO_PARCELA,
	   --TABA.CANCELAMENTO_CONTRATO,
	' MENSALIDADE' AS NOME_BOLSA,
	0 AS DESC_BOLSA,
	ISNULL(TABA.VALORBOLSA,0) AS VALORBOLSA,
	ISNULL(TABA.DESC_PONTUALIDADE_BX,0) AS DESC_PONTUALIDADE_BX, /*ISNULL( CONVERT(SMALLMONEY, ( VALORORIGINAL * (DESC_BOLSA / 100))),'')*/ 
	TABA.TIPOMATRICULA,
	TABA.DESCONTO_TOTAL,
	TABA.TIPOCONTRATO,
	TABA.SERVICO,
	TABA.CONTA_CX,
	TABA.STATUSLAN,
	ISNULL(TABA.DATABAIXA,CONVERT(VARCHAR,'') )AS DATABAIXA,
	TABA.VALORORIGINAL,
	TABA.VALORBAIXADO,
	0 AS VALIDADELIMITADA,
	TABA.PARCELA,
	TABA.IDLAN,
	TABA.IDPERLET,
	CONVERT(SMALLMONEY,TABA.VALOR) AS VALOR,
	0 AS CODBOLSA,
	'' AS NOME_BOLSA1,
	TABA.IDPARCELA,
	TABA.CODFILIAL,
	/*ISNULL(CONVERT(SMALLMONEY,(CASE WHEN TABA.NOME_BOLSA1 NOT LIKE '%FIES%' AND TABA.VALIDADELIMITADA=1 THEN (SELECT SUM(VALOR) FROM SBOLSALAN WHERE SBOLSALAN.IDLAN =TABA.IDLAN ) ELSE 0 END)),0)*/0 AS BOLSAS_INCONDICIONAIS
	--,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE N.VALOROP8 END),'') AS BOLSAS_INCONDICIONAIS

	,--ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
	ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
	--,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANOCOMPETENCIA
	,CASE TABA.STATUSLAN WHEN 'ABERTO' THEN TABA.VALORORIGINAL ELSE 0 END AS ABERTO
	,ISNULL(CASE WHEN TABA.STATUSLAN = 'ACORDO' THEN 0 ELSE TABA.VALORBAIXADO END,0) AS VALORBX_SBLAN
	,ISNULL(CASE WHEN TABA.STATUS_CONTRATO = 'ATIVO' THEN VALORORIGINAL -  BOLSAS_INCONDICIONAIS - ISNULL((CASE WHEN STATUSLAN = 'ACORDO' THEN 0 ELSE VALOROP2 END),0) END ,VAL_PARCELA) AS FATURAMENTO
        
	--	,VALOROP2

	-- ,  VLR_SBLAN
          
	  FROM TABA WHERE CODBOLSA  IS NOT NULL   -- AND IDLAN = 1553312 --1532977 -- 1554430
 ),

  TABC AS (
 SELECT DISTINCT
TABA.CURSO,
TABA.CODTURMA,
TABA.RA,
TABA.SITUACAO,
STATUS_CONTRATO,
TABA.VENCIMENTO_PARCELA,
    --TABA.CANCELAMENTO_CONTRATO,
TABA.NOME_BOLSA,
TABA.DESC_BOLSA,
ISNULL(TABA.VALORBOLSA,0) AS VALORBOLSA,
ISNULL(CASE WHEN NOME_BOLSA LIKE '%MENSALIDADE%' THEN TABA.DESC_PONTUALIDADE_BX ELSE 0 END,0) AS DESC_PONTUALIDADE_BX, /*ISNULL( CONVERT(SMALLMONEY, ( VALORORIGINAL * (DESC_BOLSA / 100))),'')*/ 
TABA.TIPOMATRICULA,
TABA.DESCONTO_TOTAL,
TABA.TIPOCONTRATO,
TABA.SERVICO,
TABA.CONTA_CX,
TABA.STATUSLAN,
ISNULL(TABA.DATABAIXA,CONVERT(VARCHAR,'') )AS DATABAIXA,
TABA.VALORORIGINAL,
TABA.VALORBAIXADO,
TABA.VALIDADELIMITADA,
TABA.PARCELA,
TABA.IDLAN,
TABA.IDPERLET,
CONVERT(SMALLMONEY,TABA.VALOR) AS VALOR,
ISNULL(TABA.CODBOLSA,'') AS CODBOLSA,
ISNULL(TABA.NOME_BOLSA1,'')AS NOME_BOLSA1,
TABA.IDPARCELA,
TABA.CODFILIAL,
ISNULL(CONVERT(SMALLMONEY,(CASE WHEN TABA.NOME_BOLSA1 NOT LIKE '%FIES%' AND TABA.VALIDADELIMITADA=1 THEN (SELECT SUM(VALOR) FROM SBOLSALAN WHERE SBOLSALAN.IDLAN =TABA.IDLAN ) ELSE 0 END)),0) AS BOLSAS_INCONDICIONAIS
--,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE N.VALOROP8 END),'') AS BOLSAS_INCONDICIONAIS
,--ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
	ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
	--,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANOCOMPETENCIA
,CASE  WHEN TABA.STATUSLAN='ABERTO' AND NOME_BOLSA LIKE '%MENSALIDADE%' THEN TABA.VALORORIGINAL ELSE 0 END AS ABERTO
,ISNULL(CASE WHEN NOME_BOLSA LIKE '%MENSALIDADE%' AND STATUSLAN <> 'ACORDO' THEN VALORBAIXADO ELSE (CASE WHEN TABA.STATUSLAN ='ACORDO' THEN 0 ELSE 0 END )END,0) AS VALORBX_SBLAN
--,CASE WHEN VALIDADELIMITADA = 1 THEN CASE WHEN DESC_BOLSA = 100 THEN VALORBAIXADO ELSE /*BOLSAS_INCONDICIONAIS*/VALORBX_SBLAN END WHEN VALIDADELIMITADA=0 THEN VALORBX_SBLAN ELSE CASE WHEN STATUSLAN = 'ABERTO' THEN 0 ELSE CASE WHEN NOME_BOLSA  LIKE '%MENSALIDADE%' THEN VALORBAIXADO ELSE VALORBX_SBLAN END END END  AS VALORBX_SBLAN
,ISNULL(( CASE WHEN STATUS_CONTRATO = 'ATIVO'  THEN ( CASE WHEN NOME_BOLSA  LIKE '%MENSALIDADE%' THEN ISNULL((TABA.VALORORIGINAL - (CASE WHEN STATUSLAN = 'ACORDO' THEN 0 ELSE VALOROP2 END )/*VLR_SBLAN*/ - TABA.BOLSAS_INCONDICIONAIS),TABA.VAL_PARCELA)  ELSE CASE WHEN NOME_BOLSA LIKE '%MENSALIDADE%' AND STATUSLAN = 'ABERTO' THEN VAL_PARCELA ELSE CASE WHEN STATUSLAN ='ABERTO' OR STATUSLAN ='ACORDO'  THEN 0 ELSE VLR_SBLAN END END END ) ELSE CASE WHEN NOME_BOLSA LIKE '%BOLSA%' THEN VLR_SBLAN ELSE VALORORIGINAL END END),0) AS FATURAMENTO

    -- ,VALOROP2
 FROM TABA

 --WHERE TABA.IDLAN = 1854005 --1532977 -- 1554430 --AND TABA.CODBOLSA IS NULL

 ),

  TABCONTA AS (
  SELECT  CURSO,VENCIMENTO_PARCELA AS MES
  ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM')),'') AS MESDECOMPETENCIA
  ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANO
  ,RA
  ,COUNT (DISTINCT RA) AS CONTA
  ,STATUS_CONTRATO 
  ,VENCIMENTO_PARCELA
  ,IDPARCELA

  FROM TABA GROUP BY CURSO,MESDECOMPETENCIA,RA,STATUS_CONTRATO,VENCIMENTO_PARCELA,IDPARCELA 
 ),

 
 TABBOLSAS AS(
  SELECT CURSO,NOME_BOLSA
   ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM')),'') AS MESDECOMPETENCIA
   ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANO
  ,RA
  ,ISNULL(CASE WHEN VALIDADELIMITADA = 0 THEN VALORBOLSA ELSE BOLSAS_INCONDICIONAIS END,0) AS VALOR_BOLSA
  FROM TABA  WHERE CODBOLSA IS NOT NULL
 )

 ------------------------FATURAMENTO------------------------------------------------------------------------------------------------------------------------
 /*
 SELECT * FROM TABC -- WHERE IDLAN=1533387
-- 1533250
--1532926
 --1533387
 --RA='00024856' -- idlan=1533250
 --1532630
 --1533006
  --1532785
 --IDLAN IN (1533066,1533062)--PROBLEMA VRSBOLSALAN
--1533062
 --1532785
 --1532871
 --/* SITUACAO LIKE 'MAT%' AND*/ RA= '00005647'--'00024826' --'00024488' --'00024826'--'00005647' --AND IDPERLET =277 



 UNION ALL

 SELECT * FROM TABB -- WHERE IDLAN =1533387
 --1533250
--1532926
 --1533387
--RA='00024856' --IDLAN =1533250

 --1532630
--1533006
 --1532785
 -- IN (1533066,1533062)
 --1533062
--1532785
 --1532871
 --/*SITUACAO LIKE 'MAT%' AND*/ RA= '00005647'--'00024826' --'00024488' --'00024826'--'00005647' --AND IDPERLET =277 
 

ORDER BY TABC.CURSO, TABC.RA,PARCELA, NOME_BOLSA
 */
 
 ------------------------CONTAGEM------------------------------------------------------------------------------------------------------------------------
 
 SELECT CURSO, MESDECOMPETENCIA AS MÊS_COMPETÊNCIA,RA,ANO --,CONTA AS QTDE_ALUNOS
  FROM TABCONTA WHERE STATUS_CONTRATO='ATIVO' ORDER BY CURSO,MES
  
  
  ------------------------BOLSAS------------------------------------------------------------------------------------------------------------------------
 --SELECT * FROM TABBOLSAS ORDER BY CURSO,NOME_BOLSA,MESDECOMPETENCIA,RA

 --SELECT * FROM TABB WHERE IDLAN=1533062

   ------------------------TESTE------------------------------------------------------------------------------------------------------------------------
   /*
  SELECT * FROM (SELECT CURSO ,SITUACAO,STATUS_CONTRATO,MESDECOMPETENCIA AS MES, CONVERT(SMALLMONEY,FATURAMENTO) AS FATURAMENTO FROM TABC) AS TAB
  
  PIVOT(SUM(FATURAMENTO) FOR MES IN ([JANEIRO],[FEVEREIRO],[MARÇO],[ABRIL]) ) AS PVT -- WHERE IDLAN=1533387 
  */

              /*
  UNION ALL

  SELECT * FROM TABB -- WHERE IDLAN =1533387

  ORDER BY TABC.CURSO, TABC.RA,PARCELA, NOME_BOLSA
             */
  /*
  Função TRANSFORM ( [ campo para o cálculo ] ) como variablename1SELECT [ campo de linha] , function ( [ campo para o cálculo ] ) como variablename2from [ nome_da_tabela ] GROUP BY [ campo de linha] PIVOT [ campo para colunas ] 
" " função é o cálculo que deseja realizar para o corpo da tabela . Neste caso , será soma " , " como você quer um total de comissões. Você poderia usar " " média função ou qualquer outra que lhe dá os resultados que você precisa .
  */