SET LANGUAGE PORTUGUÍS
SET DATEFORMAT DMY

;WITH TABA AS(

SELECT DISTINCT J.NOME CURSO
,A.CODTURMA
,A.RA
,C.DESCRICAO AS SITUACAO
,CASE D.STATUS WHEN 'N' THEN 'ATIVO'
               WHEN 'S' THEN 'CANCELADO' END AS STATUS_CONTRATO
,CONVERT(VARCHAR,E.DTVENCIMENTO,103) AS VENCIMENTO_PARCELA
,ISNULL(CASE K.VALIDADELIMITADA WHEN 0 THEN 'BOLSA COMERCIAL' ELSE K.NOME END ,' MENSALIDADE') ACORDO
 
 -- ,CASE WHEN A.RA IN (SELECT RA FROM SBOLSAALUNO WHERE SBOLSAALUNO.RA = A.RA) THEN 'TEST MENSAL' ELSE NULL END AS TESTMENSL

,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE G.DESCONTO END),'') DESC_BOLSA
,CONVERT(SMALLMONEY,N.VALOROP2) VALORBOLSA
,CONVERT(SMALLMONEY,/*L.VALOROP3BX*/N.VALOROP3) DESC_PONTUALIDADE_BX
,(SELECT DESCRICAO FROM STIPOMATRICULA WHERE CODTIPOMAT =  A.CODTIPOMAT) AS TIPOMATRICULA
,ISNULL(CONVERT(SMALLMONEY,(N.VALORDESCONTO+N.VALORDESCONTOACORDO+N.VALOROP3+N.VALOROP7+N.VALOROP2+N.VALOROP4+N.VALOROP8)),0) AS DESCONTO_TOTAL
--flb.valordesconto + valordescontoacordo + valorop3 + valorop7 + valorop2 + valorop4 + valorop8
,D.TIPOCONTRATO
,F.NOME AS SERVICO
,L.CODCXA AS CONTA_CX
,CASE STATUSLAN 
WHEN 0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
WHEN 3 THEN 'ACORDO'
WHEN 4 THEN 'BX_PARCIAL' END AS STATUSLAN
,CONVERT(VARCHAR,N.DATABAIXA,103) AS DATABAIXA
,CONVERT(MONEY,L.VALORORIGINAL) AS VALORORIGINAL
,CONVERT(MONEY, N.VALORBAIXA) AS VALORBAIXADO
,K.VALIDADELIMITADA 
  ,E.PARCELA
  ,H.IDLAN
  --,L.STATUSLAN AS STSLAN
  ,A.IDPERLET
  ,E.VALOR
  ,K.CODBOLSA
  ,E.IDPARCELA
  ,A.CODFILIAL
  ,CONVERT(SMALLMONEY,N.VALOROP8) AS BOLSAS_INCONDICIONAIS
  ,CONVERT(VARCHAR,E.DTVENCIMENTO,103) AS MESDECOMPETENCIA
  ,ISNULL(CONVERT(SMALLMONEY,M.VALORBAIXA),0) AS VALORBX_SBLAN 
  ,ISNULL(CONVERT(SMALLMONEY,M.VALOR),0) AS VLR_SBLAN
  ,CONVERT(SMALLMONEY,E.VALOR) AS VAL_PARCELA
  
 
FROM SMATRICPL A (NOLOCK)

 JOIN SPLETIVO B (NOLOCK) ON B.IDPERLET = A.IDPERLET
 JOIN SSTATUS C (NOLOCK) ON C.CODSTATUS = A.CODSTATUS
 JOIN SCONTRATO D (NOLOCK) ON D.RA = A.RA AND D.IDPERLET = A.IDPERLET AND D.IDHABILITACAOFILIAL = A.IDHABILITACAOFILIAL
 JOIN SPARCELA E (NOLOCK) ON E.RA = D.RA AND E.CODCONTRATO = D.CODCONTRATO AND E.IDPERLET = D.IDPERLET
 JOIN SSERVICO F (NOLOCK) ON F.CODSERVICO = E.CODSERVICO AND F.NOME LIKE '%MENSALIDADE%'
 LEFT JOIN SBOLSAALUNO G (NOLOCK) ON G.RA = D.RA AND G.CODCONTRATO = D.CODCONTRATO AND G.IDPERLET = D.IDPERLET
 LEFT JOIN SLAN H (NOLOCK) ON H.IDPARCELA = E.IDPARCELA
 JOIN SHABILITACAOFILIAL I (NOLOCK)  ON I.IDHABILITACAOFILIAL = D.IDHABILITACAOFILIAL
 JOIN SCURSO J (NOLOCK) ON J.CODCURSO = I.CODCURSO AND J.CODTIPOCURSO = 4
 LEFT JOIN SBOLSA K (NOLOCK) ON K.CODBOLSA = G.CODBOLSA 
 LEFT JOIN FLAN L (NOLOCK) ON L.IDLAN = H.IDLAN
 LEFT JOIN SBOLSALAN M (NOLOCK) ON E.IDPARCELA = M.IDPARCELA AND M.CODBOLSA = K.CODBOLSA
 LEFT JOIN FLANBAIXA N (NOLOCK) ON N.IDLAN = L.IDLAN AND N.DATACANCELBAIXA IS NULL


 WHERE B.CODPERLET = '2019/1'  AND /*D.TIPOCONTRATO='A'*/L.CLASSIFICACAO=15 AND L.MESDECOMPETENCIA BETWEEN '01/01/2019' AND '30/06/2019' AND L.STATUSLAN NOT IN (2) AND L.CODCFO <> '006747'
 

 GROUP BY J.NOME,A.CODTURMA,A.RA,C.DESCRICAO,D.STATUS,E.DTVENCIMENTO,K.VALIDADELIMITADA,K.NOME,G.DESCONTO,K.VALOR,N.VALOROP3,A.CODTIPOMAT,N.VALORDESCONTO
 ,N.VALORDESCONTOACORDO,N.VALOROP7,N.VALOROP2,N.VALOROP4,N.VALOROP8,D.TIPOCONTRATO,F.NOME,L.CODCXA,L.STATUSLAN,N.DATABAIXA,L.VALORORIGINAL,L.VALORBAIXADO
 ,E.PARCELA,H.IDLAN,A.IDPERLET,E.VALOR,K.CODBOLSA,E.IDPARCELA,A.CODFILIAL,D.RA,D.CODCONTRATO,L.MESDECOMPETENCIA,M.VALORBAIXA,M.VALOR,N.VALORBAIXA,L.HISTORICO,L.CLASSIFICACAO

 ),

  TABB AS(
    SELECT DISTINCT
    TABA.CURSO,
	TABA.CODTURMA,
	TABA.RA,
	TABA.SITUACAO,
	TABA.STATUS_CONTRATO,
	TABA.VENCIMENTO_PARCELA,
	' MENSALIDADE' AS ACORDO,
	0 AS DESC_BOLSA,
	ISNULL(TABA.VALORBOLSA,0) AS VALORBOLSA,
	ISNULL(TABA.DESC_PONTUALIDADE_BX,0) AS DESC_PONTUALIDADE_BX, /*ISNULL( CONVERT(SMALLMONEY, ( VALORORIGINAL * (DESC_BOLSA / 100))),'')*/ 
	TABA.TIPOMATRICULA,
	TABA.DESCONTO_TOTAL,
	TABA.TIPOCONTRATO,
	TABA.SERVICO,
	TABA.CONTA_CX,
	TABA.STATUSLAN,
	ISNULL(TABA.DATABAIXA,CONVERT(VARCHAR,'') )AS DATABAIXA,
	TABA.VALORORIGINAL,
	TABA.VALORBAIXADO,
	0 AS VALIDADELIMITADA,
	TABA.PARCELA,
	TABA.IDLAN,
	TABA.IDPERLET,
	CONVERT(SMALLMONEY,TABA.VALOR) AS VALOR,
	0 AS CODBOLSA,
	TABA.IDPARCELA,
	TABA.CODFILIAL
	--/*ISNULL(CONVERT(SMALLMONEY,(CASE WHEN TABA.ACORDO1 NOT LIKE '%FIES%' AND TABA.VALIDADELIMITADA=1 THEN (SELECT SUM(VALOR) FROM SBOLSALAN WHERE SBOLSALAN.IDLAN =TABA.IDLAN ) ELSE 0 END)),0)*/0 AS BOLSAS_INCONDICIONAIS
	--,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE N.VALOROP8 END),'') AS BOLSAS_INCONDICIONAIS

	,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
	,CASE TABA.STATUSLAN WHEN 'ABERTO' THEN TABA.VALORORIGINAL ELSE 0 END AS ABERTO
	,ISNULL(CASE WHEN STATUS_CONTRATO = 'ATIVO' THEN TABA.VALORBAIXADO ELSE 0 END,0) AS VALORBX_SBLAN
	,ISNULL((CASE WHEN STATUS_CONTRATO = 'ATIVO' THEN (VALORORIGINAL - VALORBOLSA - BOLSAS_INCONDICIONAIS) ELSE 0 END),VAL_PARCELA) AS FATURAMENTO
  
	  FROM TABA WHERE CODBOLSA  IS NOT NULL   -- AND IDLAN = 1553312 --1532977 -- 1554430
 ),

  TABC AS (
 SELECT DISTINCT
TABA.CURSO,
TABA.CODTURMA,
TABA.RA,
TABA.SITUACAO,
TABA.STATUS_CONTRATO,
TABA.VENCIMENTO_PARCELA,
TABA.ACORDO,
TABA.DESC_BOLSA,
ISNULL(TABA.VALORBOLSA,0) AS VALORBOLSA,
ISNULL(CASE WHEN ACORDO LIKE '%MENSALIDADE%' THEN TABA.DESC_PONTUALIDADE_BX ELSE 0 END,0) AS DESC_PONTUALIDADE_BX, /*ISNULL( CONVERT(SMALLMONEY, ( VALORORIGINAL * (DESC_BOLSA / 100))),'')*/ 
TABA.TIPOMATRICULA,
TABA.DESCONTO_TOTAL,
TABA.TIPOCONTRATO,
TABA.SERVICO,
TABA.CONTA_CX,
TABA.STATUSLAN,
ISNULL(TABA.DATABAIXA,CONVERT(VARCHAR,'') )AS DATABAIXA,
TABA.VALORORIGINAL,
TABA.VALORBAIXADO,
TABA.VALIDADELIMITADA,
TABA.PARCELA,
TABA.IDLAN,
TABA.IDPERLET,
CONVERT(SMALLMONEY,TABA.VALOR) AS VALOR,
ISNULL(TABA.CODBOLSA,'') AS CODBOLSA,
TABA.IDPARCELA,
TABA.CODFILIAL
--ISNULL(CONVERT(SMALLMONEY,(CASE WHEN TABA.ACORDO1 NOT LIKE '%FIES%' AND TABA.VALIDADELIMITADA=1 THEN (SELECT SUM(VALOR) FROM SBOLSALAN WHERE SBOLSALAN.IDLAN =TABA.IDLAN ) ELSE 0 END)),0) AS BOLSAS_INCONDICIONAIS
--,ISNULL(CONVERT(SMALLMONEY, CASE K.VALIDADELIMITADA WHEN 0 THEN (SELECT SUM(DESCONTO) FROM SBOLSAALUNO SB WHERE SB.RA=D.RA AND SB.CODCONTRATO=D.CODCONTRATO AND K.CODBOLSA = SB.CODBOLSA ) ELSE N.VALOROP8 END),'') AS BOLSAS_INCONDICIONAIS
,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM/yyyy')),'') AS MESDECOMPETENCIA
,CASE  WHEN TABA.STATUSLAN='ABERTO' AND ACORDO LIKE '%MENSALIDADE%' THEN TABA.VALORORIGINAL ELSE 0 END AS ABERTO
,ISNULL(CASE WHEN STATUS_CONTRATO = 'ATIVO' THEN (CASE WHEN ACORDO LIKE '%MENSALIDADE%' THEN VALORBAIXADO ELSE 0 END) ELSE 0 END,0) AS VALORBX_SBLAN
--,CASE WHEN VALIDADELIMITADA = 1 THEN CASE WHEN DESC_BOLSA = 100 THEN VALORBAIXADO ELSE /*BOLSAS_INCONDICIONAIS*/VALORBX_SBLAN END WHEN VALIDADELIMITADA=0 THEN VALORBX_SBLAN ELSE CASE WHEN STATUSLAN = 'ABERTO' THEN 0 ELSE CASE WHEN ACORDO  LIKE '%MENSALIDADE%' THEN VALORBAIXADO ELSE VALORBX_SBLAN END END END  AS VALORBX_SBLAN
,ISNULL(( CASE WHEN STATUS_CONTRATO = 'ATIVO'  THEN ( CASE WHEN ACORDO  LIKE '%MENSALIDADE%' THEN ISNULL((TABA.VALORORIGINAL - TABA.VALORBOLSA - TABA.BOLSAS_INCONDICIONAIS),TABA.VAL_PARCELA)  ELSE CASE WHEN ACORDO LIKE '%MENSALIDADE%' AND STATUSLAN = 'ABERTO' THEN VAL_PARCELA ELSE VLR_SBLAN END END ) ELSE 0 END),0) AS FATURAMENTO


 FROM TABA

 --WHERE TABA.IDLAN = 1854005 --1532977 -- 1554430 --AND TABA.CODBOLSA IS NULL

 ),

  TABCONTA AS (
  SELECT  CURSO,VENCIMENTO_PARCELA AS MES
  ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM')),'') AS MESDECOMPETENCIA
  ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANO
  ,RA
  ,COUNT (DISTINCT RA) AS CONTA
  ,STATUS_CONTRATO 
  ,VENCIMENTO_PARCELA
  ,IDPARCELA

  FROM TABA GROUP BY CURSO,MESDECOMPETENCIA,RA,STATUS_CONTRATO,VENCIMENTO_PARCELA,IDPARCELA 
 ),

 
 TABBOLSAS AS(
  SELECT CURSO,ACORDO
   ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'MMMM')),'') AS MESDECOMPETENCIA
   ,ISNULL(UPPER(FORMAT(CONVERT(DATE,TABA.VENCIMENTO_PARCELA),'yyyy')),'') AS ANO
  ,RA
  ,ISNULL(CASE WHEN VALIDADELIMITADA = 0 THEN VALORBOLSA ELSE BOLSAS_INCONDICIONAIS END,0) AS VALOR_BOLSA
  FROM TABA  WHERE CODBOLSA IS NOT NULL
 )
 ------------------------FATURAMENTO------------------------------------------------------------------------------------------------------------------------
 /*
 SELECT 'GRAD' AS TIPO_CURSO,* FROM TABC  --WHERE STATUS_CONTRATO ='CANCELADO' --IDLAN =1555397 --IN  (1532111,1529713)  --  1531608
 -- 1529713
 -- 1541205 --1532111  -- IDPARCELA=1815220 -- IDLAN = 1532977
 --1529713
 --IN (1533663,1542120) --IDPARCELA=1864203 --IDLAN = 1532128 --IDLAN = 1553312 --1551235 --RA='00003135'
--1554430 --1540422--1554430 --1532977-- 1553312 -- -- 1554430
--WHERE IDLAN=1565444--1540448

  
 UNION ALL

 SELECT 'GRAD' AS TIPO_CURSO,* FROM TABB  --WHERE STATUS_CONTRATO ='CANCELADO'--IDLAN =1555397 --IN (1532111,1529713) --1531608
 --1529713
--1541205 --1532111  --IDPARCELA=1815220
--IDLAN = 1532977
--1529713
 --(1533663,1542120)
--IDPARCELA=1864203
--IDLAN = 1532128
--1553312--1551235 --RA='00003135'

--WHERE IDLAN=1565444--1540448



 ORDER BY TABC.CURSO, TABC.RA, TABC.IDLAN, ACORDO
 */
 
 ------------------------CONTAGEM------------------------------------------------------------------------------------------------------------------------

 SELECT 'GRAD' AS TIPO_CURSO,CURSO,MESDECOMPETENCIA AS M S_COMPET NCIA,RA,ANO--,CONTA AS QTDE_ALUNOS
  FROM TABCONTA ORDER BY CURSO,MES
  

  ------------------------BOLSAS------------------------------------------------------------------------------------------------------------------------
 --SELECT 'GRAD' AS TIPO_CURSO,* FROM TABBOLSAS ORDER BY CURSO,ACORDO,MESDECOMPETENCIA,RA

