SET LANGUAGE PORTUGUÊS
SET DATEFORMAT DMY

SELECT  
		SPLETIVO.CODPERLET,
		FLAN.IDLAN,
		CONVERT(VARCHAR,FLAN.MESDECOMPETENCIA,103) AS MESDECOMPETENCIA,
		CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS DATAVENCIMENTO,
		SALUNO.RA,
		PPESSOA.NOME NOMEALUNO,
		convert(decimal(18,2),FLAN.VALORORIGINAL) VALORORIGINAL,
				CASE FLAN.STATUSLAN WHEN 0 THEN 'Em Aberto' 
							WHEN 4 THEN 'Baixado Parcialmente'
							WHEN 1 THEN 'Baixado'
		END STATUSLAN,
		CONVERT(VARCHAR,FLAN.DATABAIXA,103) AS DATABAIXA,
		FLAN.CODFILIAL,
		FLANBAIXA.VALORBAIXA VALORBAIXADO,	
		FLAN.HISTORICO,
		   FLAN.CODTB1FLX,
		   FTB1.DESCRICAO AS FLX_CX,
		   

		FLANBAIXA.VALORACRESCIMOACORDO,
		FLANBAIXA.VALORDESCONTOACORDO,
		FLANBAIXA.VALOROP7 APURAMENOR,
		FLANBAIXA.VALOROP6 APURAMAIOR,
		FLANBAIXA.VALOROP5 AUMENTALIQUIDO,
		FLANBAIXA.VALOROP4 DIMINUILIQUIDO,
		FLAN.VALOROP8 BOLSAINCONDICIONAL
		
	
		FROM FLAN WITH (NOLOCK)
		INNER JOIN SLAN WITH (NOLOCK) ON SLAN.IDLAN = FLAN.IDLAN
		INNER JOIN SPARCELA WITH (NOLOCK) ON SLAN.IDPARCELA = SPARCELA.IDPARCELA
		INNER JOIN SALUNO WITH (NOLOCK) ON SALUNO.RA = SPARCELA.RA
		INNER JOIN PPESSOA WITH (NOLOCK) ON SALUNO.CODPESSOA = PPESSOA.CODIGO
		INNER JOIN FCFO ON FCFO.CODCFO = FLAN.CODCFO
		AND FCFO.NOME NOT LIKE '%CAIX%ECON%'
		INNER JOIN SPLETIVO ON SPARCELA.IDPERLET = SPLETIVO.IDPERLET	
		INNER JOIN SSERVICO WITH (NOLOCK) ON SPARCELA.CODSERVICO = SSERVICO.CODSERVICO
		INNER JOIN FLANBAIXA ON FLAN.IDLAN = FLANBAIXA.IDLAN
		JOIN FTB1 ON FTB1.CODTB1FLX = FLAN.CODTB1FLX
		
		WHERE 
		
		FLAN.DATABAIXA BETWEEN '01/01/2018' AND '31/12/2018' --:DATA_INICIAL AND :DATA_FINAL
		/*AND SPLETIVO.CODPERLET LIKE '2018'--:CODPERLET*/
		AND FLAN.CODFILIAL = 5 --:CODFILIAL
		AND SSERVICO.NOME LIKE '%'--:NOME_SERVICO
		AND SSERVICO.CODTIPOCURSO = 1 --:COD_TIPO_CURSO
		AND FLAN.STATUSLAN = '1'
		AND FLANBAIXA.STATUS = 0
		AND FLANBAIXA.CODCXA <> '885'

		ORDER BY PPESSOA.NOME, FLAN.DATAVENCIMENTO 

		/*
		Filial	5
Período Letivo	2018
Nível de Ensino	1
Serviço	%
Data Inicial	01/03/2018
Data Final	31/03/2018

		*/

	--	SELECT * FROM FCXA WHERE CODCXA =  'IT_08159'


	--	SELECT * FROM FLAN

	--SELECT * FROM FTB1