
SET LANGUAGE PORTUGUÍS

SELECT DISTINCT FLAN.IDLAN
,CONVERT(VARCHAR,FLAN.MESDECOMPETENCIA,103) AS  MES_COMPETENCIA
,CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS DATAVENCIMENTO
,CONVERT(SMALLMONEY,FLAN.VALORORIGINAL) AS VALORORIGINAL
,CASE WHEN FLAN.STATUSLAN = 3 THEN 0 ELSE CONVERT(SMALLMONEY,FLAN.VALORBAIXADO) END AS VALORBAIXADO
,SCURSO.NOME AS CURSO
,SMATRICPL.RA
,CASE FLAN.STATUSLAN WHEN  0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
WHEN 3 THEN 'ACORDO'
WHEN 4 THEN 'BX_PARCIAL' 
END AS STATUSLAN


 FROM FLAN 
LEFT JOIN SLAN ON SLAN.IDLAN = FLAN.IDLAN
LEFT JOIN SPARCELA ON SPARCELA.IDPARCELA = SLAN.IDPARCELA
LEFT JOIN SCONTRATO ON SCONTRATO.RA = SPARCELA.RA AND SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO  AND SPARCELA.IDPERLET = SCONTRATO.IDPERLET
LEFT JOIN SMATRICPL ON SMATRICPL.RA = SCONTRATO.RA AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET AND SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
LEFT JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
LEFT JOIN SCURSO ON SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO
LEFT JOIN SSERVICO ON SSERVICO.CODSERVICO = SPARCELA.CODSERVICO

WHERE MESDECOMPETENCIA BETWEEN CONVERT(DATETIME,'01/01/2019') AND CONVERT(DATETIME,'30/06/2019')-- AND SCURSO.NOME LIKE 'CST EM GEST√O DA TECNOLOGIA DA INFORMA«√O'
AND FLAN.CLASSIFICACAO = 0 AND FLAN.STATUSLAN <> 2 AND SSERVICO.NOME LIKE '%MENSALIDADE%' AND FLAN.CODFILIAL = 18 AND SCURSO.CODTIPOCURSO = 4 /*GRADUA«√O*/

--**********************************************************-- TESTES
--AND FLAN.IDLAN = 1540032 --IN (1541640,1541641)
--**********************************************************--

ORDER BY CURSO,IDLAN
--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SMATRICPL'


--SELECT TOP 10 * FROM FLAN


--SELECT * FROM SMATRICPL WHERE RA='00017531'


--SELECT * FROM SHABILITACAOFILIAL WHERE IDHABILITACAOFILIAL = 335

