SET LANGUAGE BRAZILIAN

SELECT 
  FUNC.CODFILIAL
 ,PFUNCAO.NOME AS FUNCAO
 ,ABT.CHAPA
 ,FUNC.NOME AS FUNCIONARIO
 ,CONVERT(VARCHAR,ABT.DATA,103) AS DATA_JUST
,CONVERT(VARCHAR,DATA,103) AS DATA
,BATIDA
,STATUS
,CASE ABT.NATUREZA WHEN 0 THEN 'ENTRADA'
	               WHEN 1 THEN 'SAÍDA' END AS NATUREZA
,CONVERT(VARCHAR,DATAINSERCAO,120) AS DTINSERCAO
,CONVERT(VARCHAR,AAFDT.DATAHORA,120) AS DTHORA
,CASE AAFDT.TIPO WHEN 'I' THEN 'INCLUÍDA'
                 WHEN 'O' THEN 'ORIGINAL' END AS TIPO
,AAFDT.PROCESSO
,JUSTIFICATIVA

 ,ABT.RECCREATEDBY AS CRIADO_POR
 ,CONVERT(VARCHAR,ABT.RECCREATEDON,103) AS DT_CRIACAO
 ,ISNULL(CREAT.NOME,(SELECT NOME FROM GUSUARIO WHERE CODUSUARIO = ABT.RECCREATEDBY)) AS CRIADOR     
 

FROM PFUNC (NOLOCK) AS FUNC
JOIN (SELECT * FROM ABATFUN UNION ALL SELECT * FROM ABATFUNAM) AS ABT  ON FUNC.CHAPA = ABT.CHAPA
LEFT JOIN PFUNC(NOLOCK) AS CREAT ON CREAT.CHAPA = ABT.RECCREATEDBY
left JOIN PFUNCAO (NOLOCK) ON PFUNCAO.CODIGO = FUNC.CODFUNCAO
left JOIN AAFDT ON AAFDT.ID = ABT.IDAAFDT AND DESCONSIDERADA = 0

WHERE ABT.CHAPA = /*'060249'*/'010066' AND ABT.DATA BETWEEN '01/09/2019' AND '30/10/2019' --'010066'--'060249'

ORDER BY DTHORA




--SELECT * FROM ABATFUN WHERE CHAPA ='010066'  -- AJORNADACALCULADA

--   SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'ABATFUN'

--SELECT * FROM PFUNC WHERE CHAPA ='010066'

--SELECT * FROM ABATFUN WHERE STATUS <> 'C' AND DATA BETWEEN '2019-01-01' AND '2019-10-30' --CHAPA ='010066' --AND STATUS <> 'C'


--SELECT * FROM ABATFUNAM WHERE CHAPA = '010066' AND DATA BETWEEN '01/09/2019' AND '30/10/2019'