--     SELECT IDHABILITACAOFILIAL,* FROM MAT WHERE RA='00025448'


SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA='00025448' -- NÃO

SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA='00025448' -- NÃO

SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA='00025448' -- NÃO   

SELECT * FROM SHISTDISCEQUIVEMCURSO WHERE RA='00025448'    -- NÃO 

SELECT * FROM SHISTDISCFAC WHERE RA='00025448'             -- NÃO  DISCIPLINAS EQUIVALENTES

----------------------------------------------------------------------------------------------
SELECT * FROM SHISTDISCEQUIVCONCLUIDAS WHERE RA='00025448' ORDER BY CODDISC

SELECT * FROM SHISTORICO WHERE RA= '00025448' ORDER BY CODDISC

SELECT * FROM SHISTDISCCONCLUIDAS WHERE RA= '00025448' ORDER BY CODDISC

SELECT * FROM SHISTDISCEQUIVEMCURSO WHERE RA= '00025448' ORDER BY CODDISC

SELECT * FROM SEQUIVALENCIAHABILITACAOALUNO WHERE RA= '00025448'




SELECT * FROM MAT WHERE RA=  '009976'


 
----------------------------------------------------------------------------------------------

SELECT * FROM MAT WHERE RA= '00026633'



SELECT * FROM SPLANOPGTO WHERE CODPLANOPGTO = '001'



SELECT * FROM SBOLSA WHERE CODBOLSA = 69


select * from GUSUARIO where CODUSUARIO = '00026186'


select cpf,* from PPESSOA  where nome = 'LEA DUARTE STRINGHINI'