SELECT 
	DISTINCT 
/*DADOS GERAIS*/
 ISNULL(SPLETIVO.CODPERLET,'') AS CODPERLET
,UPPER(ISNULL(SCURSO.NOME,'')) AS CURSO
,ISNULL(SMATRICPL.CODTURMA,'') AS CODTURMA
,ISNULL(SMATRICPL.PERIODO,'') AS PERIODO
,ISNULL(SMATRICPL.RA, '') AS RA 
,ISNULL(PPESSOA.NOME,'') AS NOME
,ISNULL(PPESSOA.CPF,'') AS CPF
,ISNULL(PPESSOA.CARTIDENTIDADE,'') AS RG
,ISNULL(PPESSOA.DTNASCIMENTO,'') AS DATANASCIMENTO
,ISNULL (FCFO.CGCCFO, '') CPFRESPONSAVEL
,ISNULL (FCFO.EMAIL, '') EMAILRESPONSAVEL
,ISNULL (FCFO.NOMEFANTASIA, '') RESPONSAVELFINANCEIRO
,ISNULL (FCFO.CEP,'') CEP_RESP_FINAN
,ISNULL (FCFO.RUA,'') RUA_RESP_FINAN
,ISNULL (FCFO.NUMERO,'') NUM_RESP_FINAN
,ISNULL (FCFO.COMPLEMENTO,'') COMPL_RESP_FINAN
,ISNULL (FCFO.BAIRRO,'') BAIRRO_RESP_FINAN
,ISNULL (FCFO.CIDADE,'') CIDADE_RESP_FINAN
,ISNULL (FCFO.CODETD,'') UF_RESP_FINAN
,ISNULL (FCFO.TELEFONE,'') FONE_RES_RESP_FINAN
,ISNULL (FCFO.TELEX,'') CELULAR_RESP_FINAN
,ISNULL(CONVERT(VARCHAR(11),FCFO.DTNASCIMENTO,103),'') DTNASC_RESP_FINAN
,ISNULL(PPESSOA.EMAIL,'') AS EMAIL
,ISNULL(SINSTITUICAO.NOME,'') AS COLEGIO2GRAU
,ISNULL(SPESSOA.ANOULTIMAINST,'') AS ANO2GRAU
,ISNULL(SPESSOA.EMPRESANOME,'') AS NOMEEMPRESA
,ISNULL(PPESSOA.TELEFONE1,'') AS TELEFONE1, ISNULL(PPESSOA.TELEFONE2,'') AS TELEFONE2, ISNULL(PPESSOA.TELEFONE3,'') AS TELEFONE3
,ISNULL(SSTATUS.DESCRICAO, '') AS SITUACAO
,ISNULL(STIPOMATRICULA.DESCRICAO, '') AS TIPOMATRICULA
,SALUNOMEC.CODINEPALUNO
,(SELECT 
	TOP 1(CODPERLET)
		FROM 
			SMATRICPL SM (NOLOCK)
			INNER JOIN 
			SPLETIVO (NOLOCK) 
				ON SM.IDPERLET = SPLETIVO.IDPERLET
					WHERE 
						SM.RA = SMATRICPL.RA
					AND 
						SM.CODFILIAL = :COD_FILIAL
								ORDER BY CODPERLET) ANOENTROUFACUL
,FLAN.CODFILIAL
,ISNULL(PPESSOA.RUA,'') + ', ' + ISNULL(PPESSOA.NUMERO, '') + ' ' + ISNULL(PPESSOA.COMPLEMENTO, '') 
	+ 
		' - CEP: ' + ISNULL(PPESSOA.CEP, '') + ' - BAIRRO: ' + ISNULL(PPESSOA.BAIRRO, '') 
			ENDERECO

, ISNULL(PPESSOA.CIDADE, '') + ' - ' + ISNULL(PPESSOA.ESTADO, '') CIDADEESTADO
, ISNULL(PPESSOA.CIDADE, '') CIDADE, ISNULL(PPESSOA.ESTADO, '') ESTADO
,ISNULL(PPESSOA.BAIRRO, '') BAIRRO
,GCCUSTO.CODCCUSTO CODIGO_CENTRO_CUSTO
,GCCUSTO.NOME NOME_CENTRO_CUSTO
,SALUNOCOMPL.CARTEIRINHA 
,SALUNOCOMPL.DEPUBLICA ESCOLAPUBLICA
,PPESSOA.ESTADONATAL
,PPESSOA.NATURALIDADE
,SMATRICPL.DTMATRICULA
,CASE 
	PPESSOA.CORRACA WHEN '0' THEN 'Indígena'
					WHEN '2' THEN 'Branca'
					WHEN '4' THEN 'Negra'
					WHEN '6' THEN 'Amarela'
					WHEN '8' THEN 'Parda'
					WHEN '9' THEN 'Não Informado'
					WHEN '10' THEN 'Não Declarado'
						END AS 'COR/RAÇA'
,
	CASE 
		WHEN 
			FLAN.CODFILIAL IN (5,19) 
				THEN 
					CASE WHEN SUBSTRING(SMATRICPL.CODTURMA, 3, 1) BETWEEN '1' AND '5' AND SMATRICPL.CODTURMA NOT LIKE 'EM%' THEN 'Fundamental I'
						 WHEN SUBSTRING(SMATRICPL.CODTURMA, 3, 1) BETWEEN '6' AND '9' AND SMATRICPL.CODTURMA NOT LIKE 'EM%'THEN 'Fundamental II'
						 WHEN SUBSTRING(SMATRICPL.CODTURMA, 3, 1) BETWEEN '1' AND '2' AND SMATRICPL.CODTURMA LIKE 'EM%'THEN 'Médio 1 e 2'
						 WHEN SUBSTRING(SMATRICPL.CODTURMA, 3, 1) = '3' AND SMATRICPL.CODTURMA LIKE 'EM%'THEN 'Terceirão'
							ELSE SMATRICPL.CODTURMA
	END
END NÍVEL_ENSINO
,PAI.NOME NOME_PAI
,MAE.NOME NOME_MAE
,STIPOALUNO.DESCRICAO TIPO_ALUNO

/*CONTRATO*/
,ISNULL(CONVERT(VARCHAR, SCONTRATO.DTCONTRATO,103),'') AS DATACONTRATO
,CASE 
	ISNULL(SCONTRATO.STATUS,'') 
		WHEN 'N' THEN 'ATIVO' 
		WHEN 'S' THEN 'CANCELADO'	
			ELSE '' 
				END AS STATUSCONTRATO
,ISNULL(SCONTRATO.CODCONTRATO,'') AS CODCONTRATO
,ISNULL(SCONTRATO.CODPLANOPGTO, '') PLANO
,CONVERT(VARCHAR(11),SCONTRATO.DTCANCELAMENTO,103) DTCANCELAMENTO_CONTRATO
,SSERVICO.NOME SERVIÇO
,SCONTRATO.DIAVENCIMENTO
,STURNO.NOME TURNO

,CASE 
	SCONTRATO.TIPOCONTRATO 
		WHEN 'A' THEN 'ACORDO'
		WHEN 'P' THEN 'PARCELA' 
			END AS 'TIPOCONTRATO'
/**/

/*DADOS FINANCEIROS*/
,FLAN.IDLAN

,ISNULL(REPLACE(SBOLSALAN.VALOR, '.', ','), '') VALORBOLSA
,ISNULL(CONVERT(VARCHAR, SPARCELA.DTVENCIMENTO,103),'') VENCIMENTOPARCELA

,CASE 
	ISNULL(SBOLSAALUNO.TIPODESC,'') 
		WHEN 'P' THEN 'PERCENTAGEM' 
		WHEN 'V' THEN 'VALOR' 
			ELSE '' 
				END AS TIPODESCONTOBOLSA




,CASE 
	FLANBAIXA.STATUS 
		WHEN 0 THEN 'Baixado'
		WHEN 1 THEN 'Cancelado'
		WHEN 4 THEN 'Cheque'
		WHEN 5 THEN 'Remetido'
		WHEN 6 THEN 'Borderô' 
			END 
				AS STATUS_BAIXA

,ISNULL(SBOLSA.NOME,'') AS NOMEBOLSA
,ISNULL(SPARCELA.PARCELA,'') AS PARCELA


,ISNULL(CONVERT(VARCHAR, FLAN.DATAVENCIMENTO, 103), '') AS DATAVENCIMENTO
,ISNULL(CONVERT(VARCHAR(15), FLAN.DATABAIXA, 	103), '') AS DATABAIXA
,CASE 
	FLAN.STATUSLAN 
		WHEN 0 THEN 'ABERTO' 
		WHEN 1 THEN 'BAIXADO'
		WHEN 2 THEN 'CANCELADO'
		WHEN 3 THEN 'ACORDO'
		WHEN 4 THEN 'BAIXA PARCIAL' ELSE '' 
			END STATUSPARCELA

,MONTH(FLAN.DATAVENCIMENTO) AS 'MESVENCIMENTO'
,YEAR(FLAN.DATAVENCIMENTO) AS 'ANOVENCIMENTO'
,ISNULL(CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103), '') AS 'DATA_COMPETENCIA'
,FLANBAIXA.CODCXA 'CONTA/CAIXA DA BAIXA'

,CASE 
FLAN.STATUSLAN 
	WHEN '0' THEN 'Em Aberto'
	WHEN '1' THEN 'Baixado'
	WHEN '2' THEN 'Cancelado'
	WHEN '3' THEN 'Baixado por Acordo' 
		END AS STATUSLAN

,FLAN.DATABAIXA
,FLAN.VALORORIGINAL
,FLAN.VALORBAIXADO
,FLANBAIXA.VALOROP8 AS TOTALDESCONTOS
,FLANBAIXA.VALORBAIXA
,FLAN.VALORJUROS JUROSLANÇAMENTO
,FLAN.VALORMULTA MULTALANÇAMENTO
,FLANBAIXA.VALORJUROS JUROSBAIXA
,FLANBAIXA.VALORMULTA MULTABAIXA
,FLANBAIXA.VALOROP3 DESC_PONTUALIDADE_BX
,FLAN.VALOROP6 APURAPGTOMAIOR
,FLAN.VALOROP7 APURAPGTOMENOR
,FLAN.VALOROP5 AUMENTALIQUIDO
,FLAN.VALOROP4 DIMINUILIQUIDO
,FLANBAIXA.VALOROP5 AUMENTALIQUIDO_BAIXA
,FLANBAIXA.VALOROP4 DIMINUILIQUIDO_BAIXA
,FLANBAIXA.VALOROP6 APURAPGTOMAIOR_BAIXA
,FLANBAIXA.VALOROP7 APURAPGTOMENOR_BAIXA
,FLANBAIXA.VALOROP2 BOLSACOND_BX
,FLANBAIXA.VALOROP8 BOLSAINCOD_BX
,FLAN.VALORORIGINAL AS VALOR
,FLAN.VALORDESCONTO AS DESCONTO_LAN
,FLANBAIXA.VALORDESCONTO AS DESCONTO_BAIXA
,FLAN.DATAEMISSAO 
,FLAN.MESDECOMPETENCIA
/*DADOS ACORDO*/
,FLANBAIXA.VALORACRESCIMOACORDO
,FLANBAIXA.VALORDESCONTOACORDO


,MAX(CASE 
		WHEN (SPARCELA.DTVENCIMENTO BETWEEN SBOLSAALUNO.DTINICIO AND SBOLSAALUNO.DTFIM) 
					OR 
					(SPARCELA.PARCELA BETWEEN SBOLSAALUNO.PARCELAINICIAL AND SBOLSAALUNO.PARCELAFINAL )
							THEN ISNULL(REPLACE(SBOLSAALUNO.DESCONTO, '.', ','), '') 
									ELSE '0'
		END) DESCONTOBOLSA
		
,FBOLETO.NOSSONUMERO


/*CONTADOR CUBO*/
,1 QTDE, 1 QTDADE
,PPESSOA.SEXO
,PPESSOA.ESTADOCIVIL



FROM 
	SMATRICPL 
INNER JOIN 
	SALUNO (NOLOCK) 
		ON
			SMATRICPL.CODCOLIGADA = SALUNO.CODCOLIGADA 
		AND 
			SMATRICPL.RA = SALUNO.RA
INNER JOIN 
	PPESSOA (NOLOCK) 
				ON 
					SALUNO.CODPESSOA = PPESSOA.CODIGO
INNER JOIN 
	SPLETIVO (NOLOCK) 
		ON 
			SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
LEFT JOIN 
	SHABILITACAOFILIAL (NOLOCK) 
		ON 
			SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
LEFT JOIN 
	SCURSO (NOLOCK) 
		ON 
			SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
INNER JOIN 
	SHABILITACAO (NOLOCK) 
		ON 
			SCURSO.CODCURSO = SHABILITACAO.CODCURSO
		AND 
			SHABILITACAOFILIAL.CODHABILITACAO = SHABILITACAO.CODHABILITACAO
/*CONTRATOS E PARCELAS*/
LEFT JOIN 
	SCONTRATO (NOLOCK) 
		ON 
			SMATRICPL.RA = SCONTRATO.RA
		AND 
			SALUNO.RA = SMATRICPL.RA
		AND 
			SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		AND 
			SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		AND 
			SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
LEFT JOIN 
	SPARCELA (NOLOCK) 
		ON 
			SPARCELA.CODCONTRATO = SCONTRATO.CODCONTRATO
		AND 
			SPARCELA.RA = SALUNO.RA
		AND 
			SPARCELA.IDPERLET = SCONTRATO.IDPERLET
LEFT JOIN 
	SLAN (NOLOCK) 
		ON 
			SPARCELA.IDPARCELA = SLAN.IDPARCELA
/**/
/*LANÇAMENTOS , BAIXAS E BOLSAS*/
LEFT JOIN 
	FLAN (NOLOCK) 
		ON 
			SLAN.CODCOLIGADA = FLAN.CODCOLIGADA
		AND 
			SLAN.IDLAN = FLAN.IDLAN
LEFT JOIN 
	FBOLETO (NOLOCK)
		ON 
			FBOLETO.CODCOLIGADA = FLAN.CODCOLIGADA
		AND 
			FBOLETO.IDBOLETO = FLAN.IDBOLETO
		AND 
			FBOLETO.STATUS <>2
LEFT JOIN 
	FLANBAIXA (NOLOCK) 
		ON 
			FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
		AND 
			FLAN.IDLAN = FLANBAIXA.IDLAN
		AND 
			FLANBAIXA.STATUS<>1
LEFT JOIN 
	SBOLSAALUNO (NOLOCK) 
		ON 
			SALUNO.RA = SBOLSAALUNO.RA
		AND 
			SBOLSAALUNO.CODCONTRATO = SCONTRATO.CODCONTRATO
		AND 
			SBOLSAALUNO.CODSERVICO = SPARCELA.CODSERVICO
LEFT JOIN 
	SBOLSA (NOLOCK) 
		ON 
			SBOLSAALUNO.CODCOLIGADA= SBOLSA.CODCOLIGADA
		AND			
			SBOLSAALUNO.CODBOLSA = SBOLSA.CODBOLSA
LEFT JOIN 
	SSERVICO (NOLOCK) 
		ON 
			SSERVICO.CODCOLIGADA = SPARCELA.CODCOLIGADA
		AND 
			SSERVICO.CODSERVICO = SPARCELA.CODSERVICO 
LEFT JOIN 
	SBOLSALAN (NOLOCK) 
		ON 
			FLAN.IDLAN = SBOLSALAN.IDLAN
		AND 
			SPARCELA.IDPARCELA = SBOLSALAN.IDPARCELA
		AND 
			SPARCELA.IDPERLET = SBOLSALAN.IDPERLET
		AND 
			SBOLSA.CODBOLSA = SBOLSALAN.CODBOLSA
/**/
INNER JOIN 
	STIPOMATRICULA (NOLOCK) 
		ON 
			SMATRICPL.CODTIPOMAT = STIPOMATRICULA.CODTIPOMAT
INNER JOIN 
	SSTATUS (NOLOCK) 
		ON 
			SMATRICPL.CODSTATUS = SSTATUS.CODSTATUS
LEFT JOIN 
	FCFO (NOLOCK) 
		ON 
			FLAN.CODCFO = FCFO.CODCFO
INNER JOIN 
	SPESSOA (NOLOCK) 
		ON 
			SPESSOA.CODIGO = PPESSOA.CODIGO
LEFT JOIN 
	SINSTITUICAO (NOLOCK) 
		ON 
			SPESSOA.CODINST2GRAU = SINSTITUICAO.CODINST
INNER JOIN 
	SALUNOMEC (NOLOCK) 
		ON 
			SALUNOMEC.RA = SALUNO.RA
LEFT JOIN 
	GCCUSTO 
		ON 
			GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO
INNER JOIN 
	STURNO 
		ON 
			STURNO.CODTURNO = SHABILITACAOFILIAL.CODTURNO
LEFT JOIN 
	SALUNOCOMPL 
		ON 
			SALUNOCOMPL.RA = SALUNO.RA
LEFT JOIN 
	PPESSOA PAI 
		ON 
			PAI.CODIGO = SPESSOA.CODPESSOAPAI
LEFT JOIN 
	PPESSOA MAE 
		ON 
			MAE.CODIGO = SPESSOA.CODPESSOAMAE
LEFT JOIN 
	STIPOALUNO 
		ON 
			STIPOALUNO.CODTIPOALUNO = SALUNO.CODTIPOALUNO

/*Abaixo, alterado de 'SPLETIVO.CODPERLET LIKE' para 'SPLETIVO.CODPERLET =' por motivo de performance. Augusto Ambrozio*/
			WHERE 
				SPLETIVO.CODPERLET LIKE :COD_PERLET
			AND 
				SMATRICPL.CODFILIAL = :COD_FILIAL
			AND 
				SPLETIVO.CODTIPOCURSO = :TIPO_CURSO
				
			


					GROUP BY 
						SMATRICPL.RA
					  ,	SCONTRATO.DTCONTRATO
					  , SCURSO.NOME
					  , SCONTRATO.STATUS
					  , SCONTRATO.CODCONTRATO
					  , SBOLSAALUNO.TIPODESC
				      , SBOLSA.NOME
					  , SPARCELA.PARCELA
					  , FLAN.DATAVENCIMENTO
					  , FLAN.DATABAIXA
					  , FLAN.VALORORIGINAL
					  , FLAN.VALORDESCONTO
					  , FLAN.VALORBAIXADO
					  , PPESSOA.NOME
					  , PPESSOA.TELEFONE1
					  , PPESSOA.TELEFONE2
					  , PPESSOA.TELEFONE3
					  , SPLETIVO.CODPERLET
					  , SMATRICPL.CODTURMA
					  , STIPOMATRICULA.DESCRICAO
					  , SSTATUS.DESCRICAO
					  , FLAN.STATUSLAN
					  , PPESSOA.EMAIL
					  , SPARCELA.PARCELA
					  , FLAN.VALORORIGINAL
					  , FLAN.CODFILIAL
					  , SCONTRATO.CODPLANOPGTO
					  , PPESSOA.CPF
					  , SBOLSALAN.VALOR
					  , FCFO.NOMEFANTASIA
					  , FCFO.CGCCFO
					  , SMATRICPL.PERIODO
					  , SINSTITUICAO.NOME
					  , SPESSOA.EMPRESANOME
					  , SPESSOA.ANOULTIMAINST
					  , PPESSOA.CARTIDENTIDADE
					  , PPESSOA.RUA
					  , PPESSOA.NUMERO
					  , PPESSOA.BAIRRO
					  , PPESSOA.CIDADE
					  , PPESSOA.ESTADO
					  , PPESSOA.COMPLEMENTO
					  , PPESSOA.CEP
					  , PPESSOA.DTNASCIMENTO
					  , FCFO.EMAIL
					  , FLAN.IDLAN
					  , FLAN.DATABAIXA
					  , FLAN.VALORORIGINAL
					  , FLAN.VALORBAIXADO
					  , FLANBAIXA.VALOROP8
					  , SALUNOMEC.CODINEPALUNO
					  , SPARCELA.DTVENCIMENTO
					  , SCONTRATO.DTCANCELAMENTO
					  , SSERVICO.NOME
					  , SCONTRATO.TIPOCONTRATO
					  , GCCUSTO.CODCCUSTO
					  , GCCUSTO.NOME
					  , FLANBAIXA.CODCXA
					  , FLAN.DATAVENCIMENTO
					  , FLANBAIXA.VALORBAIXA
					  , FLANBAIXA.STATUS
					  , SCONTRATO.DIAVENCIMENTO
					  , STURNO.NOME
					  , FCFO.DTNASCIMENTO
					  , FCFO.CEP
					  , FCFO.RUA
					  , FCFO.NUMERO
					  , FCFO.COMPLEMENTO
					  , FCFO.BAIRRO
					  , FCFO.CIDADE
					  , FCFO.CODETD
					  , FCFO.TELEFONE
					  , FCFO.TELEX
					  , SALUNOCOMPL.CARTEIRINHA
					  , SALUNOCOMPL.DEPUBLICA
					  , PPESSOA.NATURALIDADE
					  , PPESSOA.ESTADONATAL
					  , SMATRICPL.DTMATRICULA
					  , PPESSOA.CORRACA
					  , FLAN.VALORJUROS 
					  , FLAN.VALORMULTA 
					  , FLANBAIXA.VALORJUROS 
					  , FLANBAIXA.VALORMULTA
					  , FLANBAIXA.VALOROP3
					  , FLAN.VALOROP6
					  ,	FLAN.VALOROP7
					  , FLAN.VALOROP5
					  , FLAN.VALOROP4
					  , FLANBAIXA.VALOROP5
					  , FLANBAIXA.VALOROP4
					  , FLANBAIXA.VALOROP6
					  , FLANBAIXA.VALOROP7
					  , FLANBAIXA.VALOROP2
					  , PAI.NOME
					  , MAE.NOME
					  , STIPOALUNO.DESCRICAO
					  , FLANBAIXA.VALORACRESCIMOACORDO
					  ,	FLANBAIXA.VALORDESCONTOACORDO
					  , FBOLETO.NOSSONUMERO
					  , FLAN.DATAEMISSAO 
					  , FLAN.MESDECOMPETENCIA
					  , FLANBAIXA.VALORDESCONTO
					  , PPESSOA.SEXO
                      , PPESSOA.ESTADOCIVIL