SELECT DISTINCT 
      SMC.CODFILIAL
      ,CODPERLET
	  ,SM.RA
	  ,PP.NOME AS ALUNO
	  ,SC.CODCURSO
	  ,SC.NOME AS CURSO
	  ,SMC.CODTURMA
	  ,CASE SP.CODTIPOCURSO WHEN 4 THEN 'GRAD' WHEN 6 THEN 'PÓS' END AS TIPOCURSO
	  ,SD.CODDISC
	  ,SD.NOME AS DISCIPLINA
	  ,SM.CODSTATUS
	  ,ST.DESCRICAO AS STATUS
	  ,SM.IDTURMADISC
	  ,SN.CODETAPA
	  ,SN.NOTAFALTA
	  ,SE.DESCRICAO
	  ,SMC.PERIODO
	  

	  FROM SMATRICULA SM

JOIN SALUNO AS SA ON SA.RA = SM.RA 
JOIN SMATRICPL AS SMC ON SMC.RA = SM.RA AND SMC.IDPERLET = SM.IDPERLET AND SMC.IDHABILITACAOFILIAL = SM.IDHABILITACAOFILIAL
JOIN SSTATUS AS ST ON ST.CODSTATUS = SM.CODSTATUS
JOIN SPLETIVO AS SP ON SP.IDPERLET = SM.IDPERLET
JOIN PPESSOA AS PP ON PP.CODIGO = SA.CODPESSOA
LEFT JOIN SNOTAETAPA AS SN ON SN.IDTURMADISC = SM.IDTURMADISC AND SN.RA = SM.RA AND SN.TIPOETAPA = 'N'
LEFT JOIN SETAPAS AS SE ON SE.CODETAPA = SN.CODETAPA AND SE.IDTURMADISC =SM.IDTURMADISC AND SE.CODETAPA = SN.CODETAPA
JOIN STURMADISC AS STD ON STD.IDTURMADISC = SM.IDTURMADISC
JOIN SDISCIPLINA AS SD ON SD.CODDISC = STD.CODDISC
JOIN SHABILITACAOFILIAL AS SHF ON SHF.IDHABILITACAOFILIAL = SM.IDHABILITACAOFILIAL
JOIN SCURSO AS SC ON SC.CODCURSO = SHF.CODCURSO

WHERE SM.RA LIKE '%' AND CODPERLET = '2020/1' AND SP.CODTIPOCURSO = 4 AND SMC.CODTURMA LIKE 'PE10.2AM'

ORDER BY CURSO,ALUNO,PERIODO,DISCIPLINA,CODETAPA

--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SMATRICULA'