/*RELAÇÃO DE BOLETOS/LANÇAMENTOS - CANCELADOS CONTEXTO 4 E 6 - ONDE TEM OU LANÇAMENTO OU BOLETO CANCELADO DE UM VENCIMENTO*/

SET LANGUAGE BRAZILIAN

DECLARE @MESCOMP AS VARCHAR(10)

SET @MESCOMP = '01/12/2020' 

SELECT DISTINCT
  FLAN.CODFILIAL
, SCONTRATO.CODTIPOCURSO
, SPARCELA.RA
, PPESSOA.NOME
, FLAN.IDLAN
, CASE FLAN.STATUSLAN
WHEN 0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
WHEN 3 THEN 'ACORDO'
WHEN 4 THEN 'BX_PARCIAL' 
END AS STATUSLAN
,FLAN.HISTORICO
,CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS DTVENCIMENTO
, CASE FBOLETO.STATUS
WHEN 0 THEN 'ABERTO'
WHEN 1 THEN 'PAGO'
WHEN 2 THEN 'CANCELADO'
END AS STATUSBOL
,SPARCELA.CODSERVICO
,SSTATUS.DESCRICAO AS STATUS
,FLAN.MESDECOMPETENCIA
,CODTDO
FROM FLAN

JOIN SLAN ON SLAN.IDLAN = FLAN.IDLAN
JOIN FLANBOLETO ON FLANBOLETO.IDLAN = FLAN.IDLAN
JOIN FBOLETO ON FBOLETO.IDBOLETO = FLANBOLETO.IDBOLETO
JOIN SPARCELA ON SPARCELA.IDPARCELA = SLAN.IDPARCELA
JOIN SALUNO ON SALUNO.RA = SPARCELA.RA
JOIN PPESSOA ON PPESSOA.CODIGO = SALUNO.CODPESSOA
JOIN SCONTRATO ON SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
JOIN SMATRICPL ON SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET AND SMATRICPL.RA = SCONTRATO.RA AND SMATRICPL.CODFILIAL = SCONTRATO.CODFILIAL
JOIN SSTATUS ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS AND SSTATUS.DESCRICAO LIKE '%MAT%'

WHERE MESDECOMPETENCIA = @MESCOMP AND FLAN.CODFILIAL = 18 AND SCONTRATO.CODTIPOCURSO IN (4,6) AND FLAN.STATUSLAN <> 3  AND (FLAN.STATUSLAN = 2 OR FBOLETO.STATUS = 2) AND CODTDO = '1.01.1' /*Boletos de Mensalidades*/
AND SPARCELA.RA NOT IN (SELECT SPARCELA.RA FROM SPARCELA 

JOIN SLAN ON SLAN.IDPARCELA = SPARCELA.IDPARCELA
JOIN FLAN ON FLAN.IDLAN = SLAN.IDLAN
JOIN SCONTRATO ON SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO

WHERE MESDECOMPETENCIA = @MESCOMP AND FLAN.CODFILIAL = 18 AND SCONTRATO.CODTIPOCURSO IN (4,6) AND FLAN.STATUSLAN NOT IN (2))

ORDER BY NOME