DECLARE @ACC AS INT
DECLARE @LANS AS VARCHAR(MAX)

SET @ACC = 39524 --:IDACORDO

SET DATEFORMAT DMY

SELECT @LANS = COALESCE(@LANS +',','') + CONVERT(VARCHAR,FACORDOREL.IDACORDO) +'-'+ CONVERT(VARCHAR,FACORDOREL.IDLAN)
FROM FACORDOREL (NOLOCK) JOIN FLAN (NOLOCK) ON FLAN.IDLAN = FACORDOREL.IDLAN WHERE FACORDOREL.IDLAN IN (SELECT IDLAN FROM FACORDOREL WHERE IDACORDO=@ACC AND FLAN.CLASSIFICACAO=15 AND STATUSLAN=3) 
GROUP BY FACORDOREL.IDLAN,FACORDOREL.IDACORDO


/*----------------------------------------------- WITH -----------------------------------------------*/
; WITH TAB_LIG AS (
SELECT *

 FROM 

(

SELECT 
* 
,CASE WHEN ACORDO_ANT <> 0 THEN CONVERT(VARCHAR,DD.ACORDO_ANT)+CONVERT(VARCHAR,DD.QTD_ACORDOS-1) ELSE CONVERT(VARCHAR,DD.IDACORDO)+CONVERT(VARCHAR,DD.QTD_ACORDOS) END  AS ACORDOSS      
,CASE IDLAN WHEN (SELECT IDLAN WHERE @LANS LIKE '%'+ CONVERT(VARCHAR,IDLAN) +'%' AND STATUSLAN='ACORDO') THEN @LANS  END AS ACORD_LANS
,CASE WHEN CLASFLAN = 15 THEN  ' ACORDO - '+CONVERT(VARCHAR,IDACORDO) ELSE SERVICO1 END AS SERVICO
,(VALORORIGINAL+JUROSBX+MULTABX+ACRE_ACORDO-DESCONTOS_GERAL) AS VALOR_TOTAL

FROM
(
 
SELECT CASE WHEN CLASFLAN=0 THEN NULL 
ELSE ISNULL((SELECT MAX(FACORDO.IDACORDO) FROM FACORDO WHERE  CODCFO = CC.CODCFO AND QTD_ACORDOS > 1 AND IDACORDO < CC.IDACORDO ),0) END AS ACORDO_ANT
,CASE WHEN  (QTD_ACORDOS = 0 AND VERIFICADOR = '0' AND CLASFLAN=15) 
 THEN 'NDA'
 
 ELSE CONVERT(VARCHAR,QTD_ACORDOS)+'-'+CONVERT(VARCHAR,QTD_ACORDOS+1) END
 AS INDEXADOR

, * 
,CASE WHEN DESC_ACORDO>0 THEN CAST(DESC_ACORDO AS MONEY) ELSE CAST(VALORDESCONTOBX AS MONEY) END AS DESCONTOS_GERAL
  
FROM

(
SELECT DENSE_RANK()OVER(/*PARTITION BY IND*/ ORDER BY VERIFICADOR ASC)-1 AS QTD_ACORDOS,BB.* 

FROM

(
 SELECT AA.*,RIGHT(CODESP,2) CODAA
,CASE RIGHT(CODESP,2) WHEN '2A' THEN CONVERT(VARCHAR,IND)+'2A' ELSE '0' END AS VERIFICADOR
 
 FROM
(

SELECT 
A.CODCOLIGADA, 
CASE WHEN F.NOME='LIVROS DIDÁTICOS INTEGRADOS - MAT DID' THEN 'MATERIAL DIDÁTICO' ELSE F.NOME END AS SERVICO1,
CONVERT(VARCHAR(10),A.DATAVENCIMENTO,103) VENCIMENTO,
A.CODFILIAL,
B.IDACORDO,A.IDLAN,A.NUMERODOCUMENTO,A.CLASSIFICACAO CLASFLAN,B.CLASSIFICACAO CLASSACORDO,
CASE A.STATUSLAN WHEN 0 THEN 'ABERTO'
                 WHEN 1 THEN 'PAGO'
				 WHEN 3 THEN 'ACORDO' 
				 WHEN 4 THEN 'BX_PARCIAL' ELSE CONVERT(VARCHAR,A.STATUSLAN) END AS STATUSLAN
				   
,FORMAT(A.MESDECOMPETENCIA,'MM/yyyy') MES_COMP,A.CODCFO
	,CASE WHEN A.CLASSIFICACAO = 15 THEN B.IDACORDO ELSE 0 END IND
	,E.IDPARCELA, E.TIPOPARCELA ,E.PARCELA
	,CONVERT(VARCHAR,B.IDACORDO)+CONVERT(VARCHAR,B.CLASSIFICACAO)+E.TIPOPARCELA CODESP
	,CAST(/*COALESCE(H.VALORORIGINAL,*/A.VALORORIGINAL/*)*/ AS MONEY) VALORORIGINAL
	,CAST(A.VALORBAIXADO AS MONEY) VALORBAIXADO
	,CAST(A.VALORORIGINALBX AS MONEY) VALORORIGINALBX
	,CAST(A.VALOROP3BX AS MONEY) VALORDESCONTOBX
	,CAST(A.VALORJUROSBX AS MONEY) JUROSBX
	,CAST(A.VALORMULTABX AS MONEY) MULTABX
	,CAST(A.VALORDESCONTOACORDO AS MONEY) DESC_ACORDO
	,CAST(A.VALORACRESCIMOACORDO AS MONEY) ACRE_ACORDO
	,CAST(H.VALOROP3 AS MONEY) HDESCONTOACORDO
	,CAST(H.VALORACRESCIMOACORDO AS MONEY) HACRESCIMOACORDO
	,(SELECT COUNT (DISTINCT IDACORDO) FROM FACORDOREL (NOLOCK) WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL (NOLOCK) WHERE IDACORDO = B.IDACORDO)) AS CONTA
	,E.RA
	,B.RECCREATEDON BREC 
	,A.DATAEMISSAO
	,C.DATA FACORDODATA
	,ISNULL(H.DATABAIXA,A.DATAEMISSAO) AS DATABAIXA
	
FROM FACORDOREL B (NOLOCK)


LEFT JOIN FLAN A (NOLOCK) ON A.IDLAN = B.IDLAN
LEFT JOIN SLAN D (NOLOCK) ON A.IDLAN = D.IDLAN
LEFT JOIN SPARCELA E (NOLOCK) ON E.IDPARCELA = D.IDPARCELA
LEFT JOIN SSERVICO F (NOLOCK) ON F.CODSERVICO = E.CODSERVICO
LEFT JOIN FACORDO C (NOLOCK) ON C.IDACORDO = B.IDACORDO
LEFT JOIN FCFO G (NOLOCK) ON C.CODCFO = G.CODCFO
LEFT JOIN FLANBAIXA H (NOLOCK) ON  H.IDLAN = A.IDLAN

WHERE

 E.RA = '00008963'--:RA
AND B.IDACORDO IN (SELECT DISTINCT IDACORDO FROM FACORDOREL (NOLOCK) WHERE IDLAN IN (SELECT IDLAN FROM FACORDOREL (NOLOCK) WHERE IDACORDO = @ACC))

)AA
 )BB 
  )CC
   )DD
 
    )EE
   GROUP BY RA,DATABAIXA,BREC,DATAEMISSAO,FACORDODATA,QTD_ACORDOS,INDEXADOR,ACORDOSS,ACORDO_ANT,ACORD_LANS,CODCFO,IDACORDO,CODCOLIGADA,CODCOLIGADA,SERVICO,SERVICO1,VENCIMENTO,CODFILIAL,IDACORDO,IDLAN,NUMERODOCUMENTO,CLASFLAN,CLASSACORDO,STATUSLAN,MES_COMP,CODCFO,IND,IDPARCELA,TIPOPARCELA,PARCELA,CODESP,VALORORIGINAL,VALORBAIXADO,VALORORIGINALBX,VALORDESCONTOBX,JUROSBX,MULTABX,DESC_ACORDO,ACRE_ACORDO,CONTA,CODAA,VERIFICADOR,HDESCONTOACORDO,HACRESCIMOACORDO,VALOR_TOTAL,DESCONTOS_GERAL
	HAVING  COUNT(IDLAN)=1


   /*--HAVING INDEXADOR LIKE '%'+AQTD_ACC+'%'             --(QTD_ACORDOS = CONTA OR QTD_ACORDOS = CONTA -1) AND (ACORDOSS = (SELECT CONVERT(VARCHAR,EE.ACORDO_ANT)+CONVERT(VARCHAR, EE.QTD_ACORDOS-1)) OR ACORDOSS = (SELECT CONVERT(VARCHAR,EE.IDACORDO)+CONVERT(VARCHAR, EE.QTD_ACORDOS))) --AND QTD_ACORDOS =  CASE QTD_ACORDOS WHEN 1 THEN 0 WHEN 2 THEN IDACORDO /*(IDACORDO <= @ACC) */ END   --AND IDACORDO=@ACC --AND  --QTD_ACORDOS = (SELECT TOP 1 MAX(QTD_ACORDOS) WHERE VERIFICADOR = (CONVERT(NVARCHAR,IDACORDO)+CODAA) ORDER BY QTD_ACORDOS DESC )*/
   )
/*
   ----------------------------------------------- FIM WITH -----------------------------------------------

   ----------------------------------------------- SELECT PRINCIPAL -----------------------------------------------
 */
(SELECT 

*
,dbo.fn_numero_por_extenso(VALORTOTAL2) AS VALOREXTENSO

 FROM
      (
       SELECT  *
	   ,(SELECT MAX(QTD_ACORDOS) FROM TAB_LIG  WHERE IDACORDO=@ACC) AS MAX_ACC
	   ,(SELECT CONVERT(DECIMAL(18,2),SUM(VALOR_TOTAL)) FROM TAB_LIG  WHERE IDACORDO=@ACC AND CLASSACORDO=2 /*AND CONVERT(VARCHAR,DATABAIXA,103)<=CONVERT(VARCHAR,RECCREATEDON,103)*/) AS VALORTOTAL2
	   
	  
	    FROM TAB_LIG

		
      ) AA2
       WHERE  IDACORDO = @ACC AND INDEXADOR LIKE '%'+CONVERT(VARCHAR,MAX_ACC)+'%' /*AND STATUSLAN = 'ACORDO' */ /*AND QTD_ACORDOS = MAX_ACC*/
	   
	   GROUP BY IDLAN,ACORDO_ANT,INDEXADOR,DATABAIXA,DATAEMISSAO,FACORDODATA,QTD_ACORDOS,CODCOLIGADA,SERVICO1,VENCIMENTO,CODFILIAL,IDACORDO,NUMERODOCUMENTO,CLASFLAN,CLASSACORDO,STATUSLAN,MES_COMP,CODCFO,IND,IDPARCELA,TIPOPARCELA,PARCELA,CODESP,VALORORIGINAL,VALORBAIXADO,VALORORIGINALBX,VALORDESCONTOBX,JUROSBX,MULTABX,DESC_ACORDO,ACRE_ACORDO,HDESCONTOACORDO,CONTA,RA,BREC,CODAA,VERIFICADOR,DESCONTOS_GERAL,ACORDOSS,ACORD_LANS,SERVICO,VALOR_TOTAL,MAX_ACC,VALORTOTAL2,HACRESCIMOACORDO --,RECCREATEDON,ACORDOSS,RA,ACORD_LANS,CODCFO,SERVICO,MES_COMP,CODCFO,IND,IDPARCELA,TIPOPARCELA,PARCELA,CODESP,VALORORIGINAL,VALORBAIXADO,VALORORIGINALBX,VALORDESCONTOBX,JUROSBX,MULTABX,DESC_ACORDO,ACRE_ACORDO,CONTA,CODAA,VERIFICADOR,HDESCONTOACORDO,HACRESCIMOACORDO,VALOR_TOTAL,DESCONTOS_GERAL,MAX_ACC,VALORTOTAL2
	
	  -- HAVING  CONVERT(VARCHAR,DATABAIXA,103)<=CONVERT(VARCHAR,DATAEMISSAO,103)
	   ) 

	   ORDER BY PARCELA
	   