--SELECT * FROM SMATRICPL WHERE CODTURMA LIKE '%BERC/NIVA%' --AND IDPERLET=229
--SELECT * FROM SPLETIVO WHERE CODPERLET = '2018' AND CODFILIAL=5--IDPERLET =265

--SELECT * FROM SHABILITACAOFILIAL WHERE IDHABILITACAOFILIAL=1338

--SELECT * FROM SSTATUS WHERE CODSTATUS IN (2,1)

DECLARE @CODPERLETANTERIOR AS VARCHAR(4)
DECLARE @DTFIM AS DATE
DECLARE @CODTURMA AS VARCHAR(20)
DECLARE @DDD AS DATE


--SET DATEFORMAT DMY

--SET LANGUAGE PORTUGUÊS


SET @CODPERLETANTERIOR='2017'
SET @DTFIM='03/12/2018'
SET @CODTURMA ='CPVMA';
SET @DDD = (CONVERT(VARCHAR,CONVERT(VARCHAR,DATEPART(D,@DTFIM))+'/'+CONVERT(VARCHAR,DATEPART(M,@DTFIM))+'/'+@CODPERLETANTERIOR,103))

SELECT 

SMATRICPL.CODTURMA SERIE,
COUNT(*) ALUNOSEM,
sum(case SMATRICPL.CODTIPOMAT when 1 then 1 else 0 end) MATRICULAS,
sum(case SMATRICPL.CODTIPOMAT when 2 then 1 else 0 end) REMATRICULAS,
STURMA.MAXALUNOS NUMVAGAS,
STURMA.MAXALUNOS - COUNT(*) FALTA,
@DDD DDD

FROM SMATRICPL

INNER JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICPL.IDPERLET
INNER JOIN SSTATUS ON SSTATUS.CODSTATUS = SMATRICPL.CODSTATUS
INNER JOIN SHABILITACAOFILIAL ON SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
INNER JOIN SCURSO ON SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
INNER JOIN STURMA ON STURMA.CODTURMA = SMATRICPL.CODTURMA
	   AND STURMA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	   AND STURMA.IDPERLET = SMATRICPL.IDPERLET

WHERE SPLETIVO.CODPERLET = @CODPERLETANTERIOR AND (SMATRICPL.DTMATRICULA <= (CONVERT(VARCHAR,CONVERT(VARCHAR,DATEPART(D,@DTFIM))+'/'+CONVERT(VARCHAR,DATEPART(M,@DTFIM))+'/'+@CODPERLETANTERIOR,103)))
AND SMATRICPL.CODFILIAL IN ('5','19')
 AND(SSTATUS.DESCRICAO LIKE '%MAT%') OR (SSTATUS.DESCRICAO LIKE 'PRE%')
AND SMATRICPL.CODTURMA = @CODTURMA
AND (SMATRICPL.CODTURMA NOT LIKE 'PAN%' AND SMATRICPL.CODTURMA NOT LIKE 'PAE%' AND SMATRICPL.CODTURMA NOT LIKE 'PSA%'
AND SMATRICPL.CODTURMA NOT LIKE 'SCHOOL%' AND SMATRICPL.CODTURMA NOT LIKE 'PABER%'
)
AND (SCURSO.NOME NOT LIKE 'VOLEI%' AND SCURSO.NOME NOT LIKE 'HAND%' AND SCURSO.NOME NOT LIKE 'FUTS%' AND SCURSO.NOME NOT LIKE 'BASQ%')


GROUP BY SMATRICPL.CODTURMA, STURMA.MAXALUNOS

ORDER BY SMATRICPL.CODTURMA

