-- SELECT * FROM XPARAMETROSCOLIGADA --WHERE CHAPA = '180420'
-- SELECT * FROM PSIMULADEMISSAO WHERE CHAPA = '180420'


-- SELECT * FROM GCAMPOS WHERE COLUNA LIKE '%INSS%'

--  PPARAM
--  PSIMULADEMISSAO


SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'PSIMULADEMISSAO'


--SELECT * FROM DPARAMETROS -- WHERE CHAPA = '180420'


SELECT * FROM GCAMPOS WHERE DESCRICAO LIKE '%PASSIVO%'


SELECT * FROM PSIMULADEMISSAO