SELECT TOP 1
ISNULL((CASE WHEN D.CODTURMA LIKE ('%EM1%') OR D.CODTURMA LIKE('%EM2%') THEN 'L.E.M - Espanhol - Disciplina Facultativa' ELSE 'A.OBS' END), '') AS OBS

FROM SMATRICPL D (NOLOCK)

LEFT JOIN SHABILITACAOFILIAL C (NOLOCK) ON C.IDHABILITACAOFILIAL=D.IDHABILITACAOFILIAL AND D.CODTURMA = 'EM1MA'
JOIN SPLETIVO E (NOLOCK) ON D.IDPERLET = E.IDPERLET


WHERE 
 D.CODTURMA = 'EM1MA' -- :CODTURMA
AND E.CODPERLET = '2018'  --:CODPERLET


--L.E.M - Espanhol - Disciplina Facultativa



--select * from smatricpl WHERE RA=007326                    CODTURMA LIKE '%EM.1B.M%' AND IDPERLET=235

--SELECT * FROM SPLETIVO WHERE IDPERLET=235

/*RA
007326
007350
007359
007360
007366
007376*/


--SELECT * FROM SHISTALUNOCOL