SELECT DISTINCT SMATRICULA.CODCOLIGADA,SMATRICULA.IDTURMADISC,SMATRICULA.RA,SNOTAS.CODETAPA,SNOTAS.CODPROVA,SNOTAS.CODCOLIGADA 
, STURMADISCGERENCIADA.IDTURMADISC AS IDTURMAGERENCIAL

FROM SNOTAS 

JOIN SMATRICULA ON SMATRICULA.IDTURMADISC = SNOTAS.IDTURMADISC
JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
/* ATIVAR QUANDO TIVER TURMA GERENCIADA*/
LEFT JOIN STURMADISCGERENCIADA ON STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = SMATRICULA.IDTURMADISC

WHERE SNOTAS.RA LIKE '%'  AND CODPERLET = '2020/2' AND CODFILIAL = 18 AND CODTIPOCURSO = 4 --AND SNOTAS.CODETAPA = 3 --:CODETAPA
--AND SNOTAS.IDTURMADISC LIKE  '%' + :IDTURMADISC + '%'
/* ATIVAR QUANDO TIVER TURMA GERENCIADA*/
AND STURMADISCGERENCIADA.IDTURMADISC = 73741 --:IDTGERENCIADA


--SELECT * FROM SMATRICULA WHERE RA='00001554' AND IDPERLET = 303


--SELECT * FROM STURMADISC WHERE IDTURMADISC = 73741



--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'STURMADISC'


--SELECT * FROM STURMADISCGERENCIADA WHERE IDTURMADISC = 73741