BEGIN TRAN

UPDATE GCCUSTO SET RECMODIFIEDON = '2018-01-01' WHERE RECMODIFIEDON > '2019-01-01'

--SELECT * FROM GCCUSTO WHERE RECMODIFIEDON > '2019-01-01' --CODCCUSTO = '1.18.01.01.01'  --'1.05.02.10.01'


--SELECT * FROM CGERENCIA WHERE CODCONTA = '1.05.02.10.01'



--SELECT DISTINCT MASTERTABLE FROM GLINKSREL WHERE MASTERTABLE LIKE '%CUSTO%'


--SELECT * FROM GCCUSTOHIST WHERE CODCCUSTO = '1.18.01.01.01' --'1.05.02.10.01'

/*

GCSTCUSTOM
IALOCACAOCENTROCUSTO
ICALCULORAZAOCENTROCUSTO
IPATRIMONIOCENTROCUSTO
KATVORDEMCUSTOEQP
KATVORDEMCUSTOIND
KATVORDEMCUSTOMAOOBRA
KATVORDEMCUSTOMP
KATVORDEMCUSTOPERDAMP
KATVORDEMCUSTOPOSTO
KATVORDEMHISTORICOCUSTO
KATVORDEMSUBPRODUTOCUSTO
KCUSTOEQP
KCUSTOINDESTR
KCUSTOINDMO
KCUSTOINDMOCOMPL
KCUSTOMO
KCUSTOPOSTO
KESTRCUSTOPADRAO
KITEMRDEMCUSTOIND
MAVAINDICESCCUSTO
MCNTCCUSTO
MCUSTODIRETOEQUIPAMENTO
MCUSTOEQUIPAMENTOAPONT
MCUSTOINDIRETOEQUIPAMENTO
MITMCNTCCUSTO
MTRFCCUSTO
OFHISTCUSTOMAOOBRA
OFOBJOFICINACCUSTO
PCCUSTO
SZ0CENTROCUSTO
SZ0CENTROCUSTOCOMPL
SZ0CONTACUSTO
SZ0CONTACUSTOCOMPL
SZ0CUSTOUNITARIO
SZ0LEITOSCENTROCUSTO
SZ0PRODUTOCENTROCUSTO
SZ0PRODUTOCUSTO
SZ0SALDOCENTROCUSTORATEIO
SZATENDRESUMOCOMPCCUSTOESPEC
SZCCUSTOSOLICITEXAME
SZCENTROCUSTO
SZCENTROCUSTOINTEGRA
SZITEMALTOCUSTO
TAGRUPACCUSTO
TCCUSTOCONT
TCCUSTORAT
TPRDCUSTO
TPRDCUSTOFILIAL
TPRDCUSTOFILIALANT
TPRDCUSTOFILIALTERCEIROS
TTBCLASSIFCCUSTO
TTBORCAMENTOCCUSTO
TUSUARIOCCUSTO
VCUSTOEPI
*/