 -- NUMERAÇÃO DE TURMA MANUALMENTE OURINHOS

DECLARE @CODFILIAL INT, @CODTURMA VARCHAR(50), @COPERLET VARCHAR(10)

,@RA1 AS VARCHAR(12) = '00026895'
,@RA2 AS VARCHAR(12) = '00027270'
,@RA3 AS VARCHAR(12) = '00027235'
,@RA4 AS VARCHAR(12) = '00027307'
,@RA5 AS VARCHAR(12) = '00027199'
,@RA6 AS VARCHAR(12) = '00026926'
,@RA7 AS VARCHAR(12) = '00027231'
,@RA8 AS VARCHAR(12) = '00027183'
,@RA9 AS VARCHAR(12) = '00027089' 
,@RA10 AS VARCHAR(12) = '00027002'
,@RA11 AS VARCHAR(12) = '00026910'
,@RA12 AS VARCHAR(12) = '00026870'
,@RA13 AS VARCHAR(12) = '00026976'
,@RA14 AS VARCHAR(12) = '00027424'
,@RA15 AS VARCHAR(12) = '00027615'

SET @CODFILIAL = 21
SET @CODTURMA = 'EF9MA'
SET @COPERLET = '2020'

BEGIN TRAN

UPDATE SMATRICULA SET NUMDIARIO = TAB.NEW_NUM 


  FROM(
	SELECT DISTINCT M.RA
		  ,P.NOME
		  ,M.IDTURMADISC
		  ,SD.NOME AS DISC
		  ,M.IDPERLET
		  ,M.IDHABILITACAOFILIAL
		  ,M.NUMDIARIO
		  ,STD.CODTURMA
		  ,ST.DESCRICAO AS STATUS
		  ,CASE M.RA WHEN @RA1 THEN 1
		             WHEN @RA2 THEN 2
					 WHEN @RA3 THEN 3
					 WHEN @RA4 THEN 4
					 WHEN @RA5 THEN 5
					 WHEN @RA6 THEN 6
					 WHEN @RA7 THEN 7
					 WHEN @RA8 THEN 8
					 WHEN @RA9 THEN 9
					 WHEN @RA10 THEN 10
					 WHEN @RA11 THEN 11
					 WHEN @RA12 THEN 12
					 WHEN @RA13 THEN 13
					 WHEN @RA14 THEN 14
					 WHEN @RA15 THEN 15 END AS NEW_NUM

	FROM SMATRICULA AS M

	JOIN STURMADISC AS STD ON STD.IDTURMADISC = M.IDTURMADISC AND STD.CODTURMA = @CODTURMA AND STD.CODFILIAL = @CODFILIAL
	JOIN SALUNO AS AL ON AL.RA =M.RA
	JOIN PPESSOA AS P ON P.CODIGO = AL.CODPESSOA
	JOIN SSTATUS AS ST ON ST.CODSTATUS = M.CODSTATUS AND (ST.DESCRICAO LIKE '%MAT%' OR ST.DESCRICAO = 'TRANSFERIDO')
	JOIN SDISCIPLINA AS SD ON SD.CODDISC = STD.CODDISC

	-- ORDER BY NOME
	) TAB 


	WHERE SMATRICULA.IDTURMADISC = TAB.IDTURMADISC AND SMATRICULA.RA = TAB.RA

   
   

   UPDATE SMATRICPL SET NUMALUNO = TAB2.NEW_NUM  

   FROM
   (
   SELECT DISTINCT SMC.RA
		  ,P.NOME
		  ,SMC.NUMALUNO
		  ,SMC.IDPERLET
		  ,STD.CODFILIAL
		  ,STD.CODTURMA
		  ,SMC.IDHABILITACAOFILIAL
		  ,ST.DESCRICAO AS STATUS
		  ,CASE SMC.RA WHEN @RA1 THEN 1
		               WHEN @RA2 THEN 2
					   WHEN @RA3 THEN 3
					   WHEN @RA4 THEN 4
					   WHEN @RA5 THEN 5
					   WHEN @RA6 THEN 6
					   WHEN @RA7 THEN 7
					   WHEN @RA8 THEN 8
					   WHEN @RA9 THEN 9
					   WHEN @RA10 THEN 10
					   WHEN @RA11 THEN 11
					   WHEN @RA12 THEN 12
					   WHEN @RA13 THEN 13
					   WHEN @RA14 THEN 14
					   WHEN @RA15 THEN 15 END AS NEW_NUM

	FROM SMATRICPL AS SMC

	JOIN STURMADISC AS STD ON SMC.CODFILIAL = STD.CODFILIAL AND SMC.CODTURMA = STD.CODTURMA AND SMC.IDPERLET = STD.IDPERLET AND SMC.IDHABILITACAOFILIAL = STD.IDHABILITACAOFILIAL  
	JOIN SALUNO AS AL ON AL.RA =SMC.RA
	JOIN PPESSOA AS P ON P.CODIGO = AL.CODPESSOA
	JOIN SSTATUS AS ST ON ST.CODSTATUS = SMC.CODSTATUS AND (ST.DESCRICAO LIKE '%MAT%' OR ST.DESCRICAO = 'TRANSFERIDO')
	JOIN SPLETIVO AS SPL ON SPL.IDPERLET = SMC.IDPERLET

	WHERE STD.CODTURMA = @CODTURMA AND STD.CODFILIAL = @CODFILIAL  AND CODPERLET = @COPERLET
	-- ORDER BY NOME
   ) TAB2 

   WHERE SMATRICPL.CODFILIAL = TAB2.CODFILIAL AND SMATRICPL.CODTURMA = TAB2.CODTURMA AND SMATRICPL.IDPERLET = TAB2.IDPERLET AND SMATRICPL.IDHABILITACAOFILIAL = TAB2.IDHABILITACAOFILIAL 
   AND SMATRICPL.RA = TAB2.RA


   --ROLLBACK

  -- COMMIT