BEGIN TRAN


UPDATE SBOLSACONT  SET CODCONTA = '5.2.1.1.01.01' WHERE EXISTS

(
SELECT 
 CODFILIAL
,SBC.CODBOLSA
,SBC.CODCCUSTO
,SBC.CODCONTA
,SBC.PERCENTUAL
,SBOLSA.NOME
,SBOLSA.VALOR
,SBOLSA.ATIVA
,SBOLSA.TIPODESC
,SBOLSA.VALIDADELIMITADA
,CCONTA.REDUZIDO
,SBOLSA.FIES
 FROM SBOLSACONT (NOLOCK) AS SBC

JOIN SBOLSA ON SBOLSA.CODBOLSA = SBC.CODBOLSA
JOIN CCONTA ON CCONTA.CODCONTA = SBC.CODCONTA

 WHERE  SBOLSACONT.CODBOLSA = SBC.CODBOLSA AND VALIDADELIMITADA = 0 AND REDUZIDO = 257 AND FIES = 0 AND SBOLSACONT.CODCONTA = '3.1.2.3.01.01'

)

--ROLLBACK
--SELECT * FROM CCONTA WHERE REDUZIDO IN ('257','1257')     5.2.1.1.01.01

--SELECT * FROM GLINKSREL WHERE MASTERTABLE ='SBOLSA'



--SELECT * FROM SBOLSA

--SELECT * FROM SBOLSACONT WHERE CODBOLSA = 464

