BEGIN TRAN


UPDATE SBOLSAFILIAL SET TIPODESCONTONFE = 1 WHERE SBOLSAFILIAL.CODBOLSA IN(


SELECT DISTINCT
 SB.CODBOLSA
--,SB.NOME
--,SB.ATIVA
--,SB.CODCLASSIFICACAO
--,SB.FIES
--,SB.NOME
--,SB.VALIDADELIMITADA
--,SBOLSAFILIAL.CODFILIAL
--,SBOLSAFILIAL.TIPODESCONTONFE

FROM SBOLSA AS SB
JOIN SBOLSAFILIAL ON SB.CODBOLSA = SBOLSAFILIAL.CODBOLSA

WHERE (FIES = 1 OR VALIDADELIMITADA = 1) AND SBOLSAFILIAL.TIPODESCONTONFE = 0

--ORDER BY SB.CODBOLSA,CODFILIAL
)

AND TIPODESCONTONFE = 0
COMMIT
--ROLLBACK