  -- UPDATE PARARESOLVER PROBLEMA DE MATRICULAS DO CONTEXTO 10 COM STATUS CONTEXTO 4, IMPEDIDINDO REMATRICULA DO ALUNO
  BEGIN TRAN

  UPDATE SMATRICULA  SET CODSTATUS = 179, CODSTATUSRES = 179

  FROM SMATRICULA AS SM

  JOIN (
 SELECT SMATRICULA.IDHABILITACAOFILIAL 
,SMATRICULA.RA
,SMATRICULA.CODSTATUS
,SSTATUS.DESCRICAO AS STATUS
,SPLETIVO.CODPERLET
,SPLETIVO.CODFILIAL
,SPLETIVO.CODTIPOCURSO
,SMATRICULA.IDPERLET

FROM SMATRICULA  

JOIN SPLETIVO ON SPLETIVO.IDPERLET = SMATRICULA.IDPERLET
JOIN SSTATUS ON SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS AND SSTATUS.CODTIPOCURSO <> 10


WHERE SPLETIVO.CODFILIAL = 18 AND SPLETIVO.CODTIPOCURSO = 10
) TAB ON TAB.RA = SM.RA AND TAB.IDHABILITACAOFILIAL = SM.IDHABILITACAOFILIAL AND TAB.IDPERLET = SM.IDPERLET AND TAB.CODSTATUS = SM.CODSTATUS


  --WHERE RA = '00000133' AND IDHABILITACAOFILIAL = 1915 AND CODSTATUS  = 43

  -- COMMIT

  -- ROLLBACK
