BEGIN TRAN
UPDATE SBOLSAALUNO SET PARCELAFINAL=12 , CODSERVICO=11 WHERE
CODCONTRATO IN (

SELECT 
SCONTRATO.CODCONTRATO

FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY SBOLSAALUNO.RA ASC) + (SELECT MAX(IDBOLSAALUNO) FROM SBOLSAALUNO) AS ID,  SMATRICPL.CODTURMA, /* SEMPRE ALTERAR O ID, COLOCAR UM ID VALIDO*/
		SBOLSAALUNO.*
		FROM SBOLSAALUNO (NOLOCK)
		JOIN SCONTRATO (NOLOCK)
		  ON SCONTRATO.CODCOLIGADA = SBOLSAALUNO.CODCOLIGADA
		 AND SCONTRATO.CODCONTRATO = SBOLSAALUNO.CODCONTRATO
		 AND SCONTRATO.RA = SBOLSAALUNO.RA
		JOIN SPLETIVO (NOLOCK)
		  ON SPLETIVO.CODCOLIGADA = SCONTRATO.CODCOLIGADA
		 AND SPLETIVO.CODFILIAL = SCONTRATO.CODFILIAL
		 AND SPLETIVO.IDPERLET = SCONTRATO.IDPERLET 
		 JOIN SMATRICPL (NOLOCK) ON SCONTRATO.IDPERLET = SMATRICPL.IDPERLET
		 AND SCONTRATO.RA = SMATRICPL.RA 
		 AND SCONTRATO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		WHERE SCONTRATO.CODFILIAL IN (6)
		  AND SPLETIVO.CODPERLET = '2018'
		  AND SBOLSAALUNO.CODBOLSA = 82
		  AND CODSERVICO = 11
		  AND DTCANCELAMENTO IS NULL
	
		 
		  ) AA
JOIN SCONTRATO (NOLOCK)
  ON SCONTRATO.CODCOLIGADA = AA.CODCOLIGADA
 AND SCONTRATO.RA = AA.RA
JOIN SPLETIVO (NOLOCK)
  ON SPLETIVO.CODCOLIGADA = SCONTRATO.CODCOLIGADA
 AND SPLETIVO.CODFILIAL = SCONTRATO.CODFILIAL
 AND SPLETIVO.IDPERLET = SCONTRATO.IDPERLET 
WHERE SPLETIVO.CODPERLET = '2019'
  AND SPLETIVO.CODFILIAL IN (6)
  AND SCONTRATO.CODCONTRATO IN (SELECT SBOLSAALUNO.CODCONTRATO FROM SBOLSAALUNO)
  )
  COMMIT