begin tran
update SOCORRENCIATIPO set DISPONIVELWEB = 1 from SOCORRENCIATIPO A  

LEFT JOIN SOCORRENCIAGRUPO ON A.CODOCORRENCIAGRUPO = SOCORRENCIAGRUPO.CODOCORRENCIAGRUPO

WHERE SOCORRENCIAGRUPO.CODTIPOCURSO = 12 AND A.DISPONIVELWEB IS NULL