BEGIN TRAN
UPDATE SBOLSAALUNO SET CODSERVICO=59 WHERE SBOLSAALUNO.CODCONTRATO IN (SELECT AA.CODCONTRATO FROM 
(  SELECT DISTINCT SBOLSAALUNO.CODCONTRATO,SGRADE.CODCURSO, SGRADE.CODGRADE,SMATRICPL.RA,
   SMATRICPL.CODTURMA,SMATRICPL.IDPERLET,SBOLSAALUNO.CODBOLSA,SBOLSAALUNO.CODSERVICO,SSERVICO.NOME NOME_SERV 
   FROM SMATRICPL 
   LEFT JOIN SHABILITACAOFILIAL ON (SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL)
   RIGHT JOIN SGRADE ON (SGRADE.CODCURSO = SHABILITACAOFILIAL.CODCURSO AND SGRADE.CODGRADE=SHABILITACAOFILIAL.CODGRADE)
   INNER JOIN SBOLSAALUNO ON (SBOLSAALUNO.RA=SMATRICPL.RA AND SBOLSAALUNO.IDPERLET=SMATRICPL.IDPERLET)
   INNER JOIN SSERVICO ON (SSERVICO.CODSERVICO=SBOLSAALUNO.CODSERVICO)

   WHERE  SGRADE.CODCURSO='003' AND SGRADE.CODGRADE ='0017' AND SBOLSAALUNO.CODSERVICO=57 AND SMATRICPL.IDPERLET = 270 
) AS AA) AND CODSERVICO=57
COMMIT
--ROLLBACK

 

  
/*
SELECT * FROM SGRADE

SELECT * FROM SPARCELA WHERE CODCONTRATO=181762 -- CODCONTRATO 

SELECT * FROM SSTATUS

SELECT * FROM SHABILITACAOFILIAL WHERE CODFILIAL=6 -- CODTIPOCURSO = 6

SELECT * FROM SCONTRATO WHERE RA=009476 AND IDPERLET IN(270,235) AND CODCONTRATO=181762 --CODPLANOPGTO 00005 E IDPERLET 270

SELECT * FROM SPLANOPGTO WHERE IDPERLET = 270 --CODPLANOPGTO E NOME

SELECT * FROM SSERVICO WHERE CODSERVICO IN (57,59) -- NOME E CODSERVICO

SELECT * FROM STIPOCURSO
*/