--SELECT * FROM SALUNO WHERE RA= '00016845'



--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'SMATRICPL' AND CHILDTABLE = 'SALUNO'



SELECT DISTINCT MAT.CODFILIAL,MAT.CURSO,MAT.CODTURMA,MAT.RA,MAT.ALUNO,MAT.CODPERLET
,MAT.CODUSUARIO,SU.ACESSO, GU.CODPERFIL,GU.CODSISTEMA,GUSUARIO.STATUS,SU.CODFILIAL

 FROM MAT 

LEFT JOIN GUSUARIO ON GUSUARIO.CODUSUARIO = MAT.CODUSUARIO AND GUSUARIO.STATUS = 0
LEFT JOIN SUSUARIOFILIAL SU ON SU.CODUSUARIO = MAT.CODUSUARIO --AND SU.CODFILIAL = 5
LEFT JOIN GUSRPERFIL GU ON GU.CODUSUARIO = MAT.CODUSUARIO AND GU.CODSISTEMA = 'S' --AND GU.CODPERFIL = '05_ALUNO' 

WHERE  MAT.CODFILIAL = 5 and CODPERLET = '2020' and CODSERVICO =1 and MAT.STATUS like 'mat%' /*RA = '00016845' AND*/  -- 00014191

GROUP BY CODPERFIL,MAT.CODFILIAL,MAT.CURSO,MAT.CODTURMA,MAT.RA,MAT.ALUNO,MAT.CODPERLET
,MAT.CODUSUARIO,SU.ACESSO,GU.CODSISTEMA,GUSUARIO.STATUS,SU.CODFILIAL

--HAVING SU.CODFILIAL <> 5

ORDER BY ALUNO


--SELECT * FROM GLINKSREL WHERE MASTERTABLE = 'GUSUARIO'


--SELECT * FROM SUSUARIOFILIAL


--SELECT * FROM GUSRPERFIL